### ISSUE TITLE
Flows potentially wrong in EpiModel Web DCM model

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#210]
Parameters:

* s.num = 28650
* i.num = 100
* TS = 10
* dt = 1
* inf.prob = 0.2
* act.rate = 3.4

Closed-pop, SI model

**Comment by smjenness** [comment]
@sgoodreau I figured out "the what" of this, which relates to methods for numerical integration of the ODE, and Emily is going to help provide some mathematical guidance to explain "the why".

@martinamorris I know you will be interested in this as well

@ebey I will bestow a thumbs-up emoji upon you if you can help explain this.


## The Issue

Consider the following deterministic compartmental model in EpiModel:
```r
param <- param.dcm(inf.prob = 0.2, act.rate = 3.4)
init <- init.dcm(s.num = 28650, i.num = 100)
control <- control.dcm(type = "SI", nsteps = 2)
mod <- dcm(param, init, control)
```

This EpiModel function runs this ODE under the hood:
```r
mod <- function(t, t0, parms) {
  with(as.list(c(t0, parms)), {

    # Derivations
    num <- s.num + i.num

    # Parameters
    lambda <- inf.prob * act.rate * i.num / num

    # ODEs
    dS <- -lambda * s.num
    dI <- lambda * s.num

    # Output
    list(c(dS, dI),
         num = num,
         si.flow = lambda * s.num)
  })
}
```

The output from the model is:
```r
as.data.frame(mod)
  time    s.num    i.num   num   si.flow
1    1 28650.00 100.0000 28750  67.76348
2    2 28553.41 196.5892 28750 132.76656
```
The `si.flow` column should show the number of infections that have occurred between time 1 and time 2. Since this is a closed population where the only flows are between susceptible and infected, the `i.num` at time 2 should equal the `i.num` at time 1 plus the `si.flow` "during" time 1. In fact, it is off by nearly 30 people.

Solving the system in discrete time by hand, the formula for the number of new infection in that interval is:
```r
lambda <- 3.4*0.2*(100/28750)
100 + (28650*lambda)
```
which equals 167.76, consistent with expectations. 

## The What
Now, the default integration method for dcm is the Runge-Kutta 4 method, which I set as the default because it seems like people use this method the most in mathematical epidemiology, and it is the default in numerical systems solves like Berkley Madonna. However, it may be changed using the `odemethod` control setting in `control.dcm`. So when we run the model using the "Euler" method, here's what we get:
```r
param <- param.dcm(inf.prob = 0.2, act.rate = 3.4)
init <- init.dcm(s.num = 28650, i.num = 100)
control <- control.dcm(type = "SI", nsteps = 2, odemethod = "euler")
mod <- dcm(param, init, control)
as.data.frame(mod)

  time    s.num    i.num   num   si.flow
1    1 28650.00 100.0000 28750  67.76348
2    2 28582.24 167.7635 28750 113.41348
```

So that's the expectation, but I'm not clear why the RK4 method is not performing as expected in this case.

**Comment by martinamorris** [comment]
just a first response, tho not a complete one.

looking online at the difference between the two approaches i see this:

The main reason that Euler's method has such a large truncation error 
per step is that in evolving the solution from $x_n$ to $x_{n+1}$ the 
method only evaluates derivatives at the beginning of the interval: 
i.e., at $x_n$. The method is, therefore, very asymmetric with respect 
to the beginning and the end of the interval. We can construct a more 
symmetric integration method by making an Euler-like trial step to the 
midpoint of the interval, and then using the values of both $x$ and $y$ 
at the midpoint to make the real step across the interval.

so, if i'm reading this correctly, your "by hand" calculation is exactly 
what Euler's method returns:  based on the start of the interval.  but if 
the interval has any real length, this effectively assumes that only those 
infected at the start of the interval can transmit.  the alternative is to 
allow those infected "within step" to start transmitting also, which would 
lead to a compound interest type of formula, and and a larger si.flow 
during the interval.


On Wed, 29 Apr 2015, Samuel Jenness wrote:

> 
> @sgoodreau I figured out "the what" of this, which relates to methods for numerical
> integration of the ODE, and Emily is going to help provide some mathematical guidance to
> explain "the why".
> 
> @martinamorris I know you will be interested in this as well
> 
> @ebey I will bestow a thumbs-up emoji upon you if you can help explain this.
> 
> THE ISSUE
> 
> Consider the following deterministic compartmental model in EpiModel:
> 
> param <- param.dcm(inf.prob = 0.2, act.rate = 3.4)
> init <- init.dcm(s.num = 28650, i.num = 100)
> control <- control.dcm(type = "SI", nsteps = 2)
> mod <- dcm(param, init, control)
> 
> This EpiModel function runs this ODE under the hood:
> 
> mod <- function(t, t0, parms) {
>   with(as.list(c(t0, parms)), {
>
>     # Derivations
>     num <- s.num + i.num
>
>     # Parameters
>     lambda <- inf.prob * act.rate * i.num / num
>
>     # ODEs
>     dS <- -lambda * s.num
>     dI <- lambda * s.num
>
>     # Output
>     list(c(dS, dI),
>          num = num,
>          si.flow = lambda * s.num)
>   })
> }
> 
> The output from the model is:
> 
> as.data.frame(mod)
>   time    s.num    i.num   num   si.flow
> 1    1 28650.00 100.0000 28750  67.76348
> 2    2 28553.41 196.5892 28750 132.76656
> 
> The si.flow column should show the number of infections that have occurred between time 1 and
> time 2. Since this is a closed population where the only flows are between susceptible and
> infected, the i.num at time 2 should equal the i.num at time 1 plus the si.flow "during" time
> 1. In fact, it is off by nearly 30 people.
> 
> Solving the system in discrete time by hand, the formula for the number of new infection in
> that interval is:
> 
> lambda <- 3.4*0.2*(100/28750)
> 100 + (28650*lambda)
> 
> which equals 167.76, consistent with expectations.
> 
> THE WHAT
> 
> Now, the default integration method for dcm is the Runge-Kutta 4 method, which I set as the
> default because it seems like people use this method the most in mathematical epidemiology,
> and it is the default in numerical systems solves like Berkley Madonna. However, it may be
> changed using the odemethod control setting in control.dcm. So when we run the model using the
> "Euler" method, here's what we get:
> 
> param <- param.dcm(inf.prob = 0.2, act.rate = 3.4)
> init <- init.dcm(s.num = 28650, i.num = 100)
> control <- control.dcm(type = "SI", nsteps = 2, odemethod = "euler")
> mod <- dcm(param, init, control)
> as.data.frame(mod)
>
>   time    s.num    i.num   num   si.flow
> 1    1 28650.00 100.0000 28750  67.76348
> 2    2 28582.24 167.7635 28750 113.41348
> 
> So that's the expectation, but I'm not clear why the RK4 method is not performing as expected
> in this case.
> 
> —
> Reply to this email directly or view it on
> GitHub.[AH0J4rrpTHQMmiRDe0RcGiEsmMWYhR51ks5oEWNpgaJpZM4EHHhJ.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by smjenness** [comment]
Hmm... so it looks like there was an error in calculating incidence, `si.flow`, rather than the compartment size `i.num`.

**Comment by martinamorris** [comment]
I'm not sure what you mean by "error" here.  Both Euler and RK are discrete time approximations of a continuous time process.  If the rate of events is low, there should be little difference between them.  Otherwise, RK is the better approximation.  Neither is an "error".

**Comment by smjenness** [comment]
I mean that the si.flow (the number of new infections within that time interval) should be consistent with the difference in compartment sizes over that interval, regardless of the integration method used. For example, using the RK4 method, we get this:
```r
as.data.frame(mod)
  time    s.num    i.num   num   si.flow
1    1 28650.00 100.0000 28750  67.76348
2    2 28553.41 196.5892 28750 132.76656
```
So 96.6 infections occurred in the interval and that should be the value in the `si.flow` for row 1 (it's arbitrary whether that 96.6 should be listed on row 1 or row 2, but that's another matter).

It's looking like the underlying ODE solver, the `deSolve` package, does not evaluate secondary calculations derived from the derivatives within the DCM function as it does for the derivatives themselves.
```r
    list(c(dS, dI),
         num = num,
         si.flow = lambda * s.num)
```

And... I just found another case whether that calculation method breaks down, even for the Euler method, where dt is fractional. Oy vey.
```r
param <- param.dcm(inf.prob = 0.2, act.rate = 3.4)
init <- init.dcm(s.num = 28650, i.num = 100)
control <- control.dcm(type = "SI", nsteps = 3, odemethod = "euler", dt = 0.5)
mod <- dcm(param, init, control)
as.data.frame(mod)

  time    s.num    i.num   num   si.flow
1  1.0 28650.00 100.0000 28750  67.76348
2  1.5 28616.12 133.8817 28750  90.61563
3  2.0 28570.81 179.1896 28750 121.08945
4  2.5 28510.27 239.7343 28750 161.65996
5  3.0 28429.44 320.5643 28750 215.55317
```

**Comment by sgoodreau** [comment]
Thanks all for jumping on this.

My original plan was to pass out a homework assignment tomorrow, due a 
week later, that makes heavy use of EpiModel web.  But it'd require the 
students to have to look under the hood here, and with this issue I 
don't think I can.  What are your guesses about the timeline to fix 
this?  If it can't be in the next few days then I need to re-write the 
assignment - OK if necessary, but just let me know.


On 4/29/2015 10:18 PM, Samuel Jenness wrote:
>
> I mean that the si.flow (the number of new infections within that time 
> interval) should be consistent with the difference in compartment 
> sizes over that interval, regardless of the integration method used. 
> For example, using the RK4 method, we get this:
>
> as.data.frame(mod)
>    time     s.num     i.num    num    si.flow
> 1     1  28650.00  100.0000  28750   67.76348
> 2     2  28553.41  196.5892  28750  132.76656
>
> So 96.6 infections occurred in the interval and that should be the 
> value in the |si.flow| for row 1 (it's arbitrary whether that 96.6 
> should be listed on row 1 or row 2, but that's another matter).
>
> It's looking like the underlying ODE solver, the |deSolve| package, 
> does not evaluate secondary calculations derived from the derivatives 
> within the DCM function as it does for the derivatives themselves.
>
>      list(c(dS,dI),
>           num  =  num,
>           si.flow  =  lambda  *  s.num)
>
> And... I just found another case whether that calculation method 
> breaks down, even for the Euler method, where dt is fractional. Oy vey.
>
> param  <-  param.dcm(inf.prob  =  0.2,act.rate  =  3.4)
> init  <-  init.dcm(s.num  =  28650,i.num  =  100)
> control  <-  control.dcm(type  =  "SI",nsteps  =  3,odemethod  =  "euler",dt  =  0.5)
> mod  <-  dcm(param,init,control)
> as.data.frame(mod)
>
>    time     s.num     i.num    num    si.flow
> 1   1.0  28650.00  100.0000  28750   67.76348
> 2   1.5  28616.12  133.8817  28750   90.61563
> 3   2.0  28570.81  179.1896  28750  121.08945
> 4   2.5  28510.27  239.7343  28750  161.65996
> 5   3.0  28429.44  320.5643  28750  215.55317
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/statnet/EpiModel/issues/210#issuecomment-97664879>.
>

-- 
*******************************************************************
"We cannot overstate the role of behavioral science in our effort
  to get ahead of the curve with emerging infections."
   --David Satcher, Director, US Centers for Disease Control, 1995
*******************************************************************
Steven M. Goodreau / Assoc. Professor / Dept. of Anthropology
University of Washington / Denny Hall 423 / Campus Box 353100
Seattle WA 98195 / 1-206-685-3870 (phone)/ 1-206-543-3285 (fax)
http://faculty.washington.edu/goodreau
*******************************************************************

**Comment by smjenness** [comment]
@sgoodreau I think an acceptable short-term fix is to switch the shiny app to use the Euler method under the hood, even if this imposes unsatisfactory mathematical solutions. But it would be important to test these against your HW examples, as the Euler has its own problems. If that fix is acceptable to you and made the update this morning, would you have sufficient time to test your HW?

**Comment by sgoodreau** [comment]
Yes, plenty of time.  Awesome.  Even if it has issues, if the stocks and 
flows match up then it should avoid major confusion / a riot among the 
students :-)

On 4/30/2015 8:38 AM, Samuel Jenness wrote:
>
> @sgoodreau <https://github.com/sgoodreau> I think an acceptable 
> short-term fix is to switch the shiny app to use the Euler method 
> under the hood, even if this imposes unsatisfactory mathematical 
> solutions. But it would be important to test these against your HW 
> examples, as the Euler has its own problems. If that fix is acceptable 
> to you and made the update this morning, would you have sufficient 
> time to test your HW?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/statnet/EpiModel/issues/210#issuecomment-97842863>.
>

-- 
*******************************************************************
"We cannot overstate the role of behavioral science in our effort
  to get ahead of the curve with emerging infections."
   --David Satcher, Director, US Centers for Disease Control, 1995
*******************************************************************
Steven M. Goodreau / Assoc. Professor / Dept. of Anthropology
University of Washington / Denny Hall 423 / Campus Box 353100
Seattle WA 98195 / 1-206-685-3870 (phone)/ 1-206-543-3285 (fax)
http://faculty.washington.edu/goodreau
*******************************************************************

**Comment by martinamorris** [comment]
ah math.

On Thu, 30 Apr 2015, Steven Goodreau wrote:

> Yes, plenty of time. Awesome. Even if it has issues, if the stocks and
> flows match up then it should avoid major confusion / a riot among the
> students :-)
> 
> On 4/30/2015 8:38 AM, Samuel Jenness wrote:
> >
> > @sgoodreau <https://github.com/sgoodreau> I think an acceptable
> > short-term fix is to switch the shiny app to use the Euler method
> > under the hood, even if this imposes unsatisfactory mathematical
> > solutions. But it would be important to test these against your HW
> > examples, as the Euler has its own problems. If that fix is acceptable
> > to you and made the update this morning, would you have sufficient
> > time to test your HW?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/statnet/EpiModel/issues/210#issuecomment-97842863>.
> >
> 
> --
> *******************************************************************
> "We cannot overstate the role of behavioral science in our effort
> to get ahead of the curve with emerging infections."
> --David Satcher, Director, US Centers for Disease Control, 1995
> *******************************************************************
> Steven M. Goodreau / Assoc. Professor / Dept. of Anthropology
> University of Washington / Denny Hall 423 / Campus Box 353100
> Seattle WA 98195 / 1-206-685-3870 (phone)/ 1-206-543-3285 (fax)
> http://faculty.washington.edu/goodreau
> *******************************************************************
> 
> —
> Reply to this email directly or view it on
> GitHub.[AH0J4unattpBB8fSH5bIuVlFIaXDPFRAks5oEkVdgaJpZM4EHHhJ.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by martinamorris** [comment]
it would be nice to have Emily look at this, and get an applied math perspective on it.  

note that the fractional dt of 0.5 results in half the expected number of new infected in the next step (seems consistent), but the expected number for a dt of 1.0 for the si.flow.  that strikes me as an inappropriate inconsistency -- aka, a bug in the desolve software (or EpiModel, not sure where these numbers are coming from).

**Comment by smjenness** [comment]
It's a bug in EpiModel

**Comment by ebey** [comment]
Chiming in now!

I think Martina gave a good synopsis of the difference between Euler and RK4: Euler basically assumes a constant slope throughout the interval (based on the population at the beginning) but RK4 uses a weighted average of what the slopes would be at the beginning, middle and end of the interval. Neither of these is wrong, they are both discrete approximations to the continuous process. 

The "error" arises because defining `si.flow = lambda * s.num` assumes a constant flow over the time step. This is exactly what the Euler method with `dt = 1` would return! So setting the method or time step to anything else will always create a mismatch between the difference in s.num across a time step and the si.flow, because you have defined them as different discrete approximations. I wouldn't be surprised if most of the time this error is small though.

I think allowing the user to set different ode methods is really nice, so the si.flow should account for which method is being used.

**Comment by sgoodreau** [comment]
Thanks.

The issue is that even when dt = 1 the difference between the reported 
si.flow and the reported change in the compartment sizes was massive.  
It's not the discrete approximation to a continuous time approximation 
that's an issue - it's the fact that the three quantities in the model 
that have to be consistent with one another, regardless of the method 
used, were widely inconsistent.

On 4/30/2015 11:06 AM, ebey wrote:
>
> Chiming in now!
>
> I think Martina gave a good synopsis of the difference between Euler 
> and RK4: Euler basically assumes a constant slope throughout the 
> interval (based on the population at the beginning) but RK4 uses a 
> weighted average of what the slopes would be at the beginning, middle 
> and end of the interval. Neither of these is wrong, they are both 
> discrete approximations to the continuous process.
>
> The "error" arises because defining |si.flow = lambda * s.num| assumes 
> a constant flow over the time step. This is exactly what the Euler 
> method with |dt = 1| would return! So setting the method or time step 
> to anything else will always create a mismatch between the difference 
> in s.num across a time step and the si.flow, because you have defined 
> them as different discrete approximations. I wouldn't be surprised if 
> most of the time this error is small though.
>
> I think allowing the user to set different ode methods is really nice, 
> so the si.flow should account for which method is being used.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/statnet/EpiModel/issues/210#issuecomment-97900389>.
>

-- 
*******************************************************************
"We cannot overstate the role of behavioral science in our effort
  to get ahead of the curve with emerging infections."
   --David Satcher, Director, US Centers for Disease Control, 1995
*******************************************************************
Steven M. Goodreau / Assoc. Professor / Dept. of Anthropology
University of Washington / Denny Hall 423 / Campus Box 353100
Seattle WA 98195 / 1-206-685-3870 (phone)/ 1-206-543-3285 (fax)
http://faculty.washington.edu/goodreau
*******************************************************************

**Comment by ebey** [comment]
Right. The inconsistency is precisely because there are different approximation methods underlying those quantities. Setting si.flow = lambda * s.num is only ever going to be consistent with the Euler method with dt = 1.

![rk4_euler](https://cloud.githubusercontent.com/assets/7977899/7420612/b4b49d14-ef32-11e4-9366-0f75238874ea.png)

**Comment by smjenness** [comment]
@ebey do you know if there's a way to calculate si.flow in deSolve that is consistent with the non-Euler methods or lower dt values? I fear that I will only be able to do it after the ode is returned (ie subtracting the lagged differences in size of I.num)

**Comment by martinamorris** [comment]
Out of curiousity, is there a problem with using the lagged diffs?

**Comment by ebey** [comment]
@smjenness I don't think it's possible because the t0 object in each of your mod functions just contains the numbers for that time step. But I agree with Martina that it wouldn't be hard or problematic to take the differences after the fact. We can't use the flow quantities as a "check" for the integration anyway, because we have to do the integration to get them.

**Comment by smjenness** [comment]
Ok, my main concern is that we have quite a few embedded DCMs within EpiModel, and the more complex DCMs have many internal flows. So for example, calculating si.flow for an SIR model with births and deaths would be: diff(i.num) + diff(r.num) + diff(deaths) - diff(births). Not tricky, just a bit of work.

**Comment by smjenness** [comment]
@martinamorris Emily and I just found out that it is impossible to calculate the flow sizes from the lagged differences in compartment sizes for many models, including SIS and SI/SIR models with births and deaths. Consider for the SIS how you calculate the S->I flow versus the I->S flow from the differences in state sizes alone. We're doing to research today to see if there are alternative methods within deSolve to handle this.

**Comment by ebey** [comment]
@smjenness For a few moments of despair I thought about writing a whole new function to replace ode, but I figured out a much easier solution. Huzzah!

We don't want to output the dS or dI quantities at each time step because they include all sources of change to the population numbers (vital dynamics, etc.), but we can't output the si.flow separate from the integration because it won't get updated in the same way as s.num and i.num when integration methods change (our original problem), SO we can tease out the parts of the dS and dI equations that we are interested in and integrate those as well. 

For example the SI model with an open population:

```{r}
param <- param.dcm(inf.prob = 0.4, act.rate = 0.25, b.rate = 1/100, 
                                   ds.rate = 1/100, di.rate = 1/50)
init <- init.dcm(s.num = 20000, i.num = 100)
control <- control.dcm(type = "SI", nsteps = 3, dt = 1)
```
We just have to include initial flow values in the initial conditions vector (I changed the name from t0 to y0 here).
```{r}
y0 <- setNames(c(as.numeric(init),0,0,0,0), 
               c(names(init), "si.flow", "b.flow",
                 "ds.flow", "di.flow"))
```

The functions for each model don't have to change much because you were already defining those flows in the output, we just include them in the vector of derivatives now.
```{r}
mod_op <- function(t, y, parms) {
  with(as.list(c(y, parms)), {
    
    # Derivations
    num <- s.num + i.num
    
    # Parameters
    lambda <- inf.prob * act.rate * i.num / num
    if (!is.null(parms$inter.eff) && t >= inter.start) {
      lambda <- lambda * (1 - inter.eff)
    }
    
    # ODEs
    dS <- -lambda * s.num + b.rate * num - ds.rate * s.num
    dI <- lambda * s.num - di.rate * i.num
    si.flow <- lambda * s.num
    b.flow <- b.rate * num
    ds.flow <- ds.rate * s.num
    di.flow <- di.rate * i.num
    
    # Output
    list(c(dS, dI, si.flow, b.flow, ds.flow, di.flow),
         num = num)
  })
}
```

But the inital output of ode will have cumulative flows in each time step so we still have to clean up with some subtraction.
```{r}
df <- as.data.frame(ode(y = y0,  times = times, func = mod_op,  parms = param, method = "rk4"))
df

  time    s.num    i.num  si.flow   b.flow  ds.flow  di.flow      num
1    1 20000.00 100.0000  0.00000   0.0000   0.0000 0.000000 20100.00
2    2 19990.69 108.2726 10.35426 200.9949 199.9540 2.081637 20098.96
3    3 19980.61 117.2246 21.56002 401.9789 399.8112 4.335432 20097.83

for (j in (control$nsteps*control$dt):2){
  df$si.flow[j] <- df$si.flow[j]-df$si.flow[j-1]
  df$b.flow[j] <- df$b.flow[j]-df$b.flow[j-1]
  df$ds.flow[j] <- df$ds.flow[j]-df$ds.flow[j-1]
  df$di.flow[j] <- df$di.flow[j]-df$di.flow[j-1]
}

df
  time    s.num    i.num  si.flow   b.flow  ds.flow  di.flow      num
1    1 20000.00 100.0000  0.00000   0.0000   0.0000 0.000000 20100.00
2    2 19990.69 108.2726 10.35426 200.9949 199.9540 2.081637 20098.96
3    3 19980.61 117.2246 11.20576 200.9840 199.8571 2.253795 20097.83
```

In this case, we can confirm that `b.flow - ds.flow - di.flow` equals the total change in the population for each time step, and that `si.flow - di.flow` is the change in the infected population.

**Comment by smjenness** [comment]
@ebey :+1: :star: :+1:
