### ISSUE TITLE
Dendogram/phylo trees for transmission chains from epidemic simulations

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#230]
@skyebend Here is a simple test case for getting started. Thanks for your help!

```r
library(EpiModel)
nw <- network.initialize(n = 100, directed = FALSE)
formation <- ~edges
target.stats <- 50
coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 20)
est1 <- netest(nw, formation, target.stats, coef.diss, verbose = FALSE)

param <- param.net(inf.prob = 0.5)
init <- init.net(i.num = 1)
control <- control.net(type = "SI", nsteps = 40, nsims = 1, verbose.int = 0, use.pids = FALSE)
mod1 <- netsim(est1, param, init, control)

tm <- get_transmat(mod1)
tm
```

The parent for any tree branch would be the ID in `inf` and the child would be the id in `sus`.

**Comment by skyebend** [comment]
Ouch, this is much harder than anticipated, took me 3 days!   The plot.phylo code is pretty fragile and seems to depend on lots of undocumented elements of how it parses trees from its textual input syntax, crashes R on any errors.  Sort of have it figured out to at least render a tree.

https://github.com/statnet/EpiModel/tree/dendo_plot

Some things I've learned:  

All of the 'tips' (end vertices) must be numbered starting from 1.  The 'nodes' (vertices with children) must have ids > tips, and the 'root' must have id = length(tips)+1.  This requires walking through the tree to relabel the internal phylo node ids. 

Problems:

1) phylo representation  prohibits nodes that don't split (i.e. they have only one child).  This means that a linear sequence of infections can't be shown (A->B->C) and they happen a lot.  This can be avoided by adding a `collapse.singles()` call, but that seems to scramble the names. Possibly we can solve this by adding some dummy tips?.  Or I can try to set it up to merge the two elements and give them a combined name?

2) still need to correctly handle common cases of multiple trees

3) I'd like to add a 'transmat' class to the transmat object so we can do S3 dispatch

4) add timing info

5) obviously docs and tests and such

**Comment by smjenness** [comment]
Thanks, Skye. I understand now why I was getting frustrated in doing this after an hour. I'm not sure the best way to handle linear sequences. Let me get back to you on that one.

Feel free to add a transmat class, probably should go here:
https://github.com/statnet/EpiModel/blob/master/R/saveout.R#L158-L165

**Comment by skyebend** [comment]
I have a feeling I've been thinking about this wrong, previously I'd tried a 'common ancestor' approach, Perhaps we should go back to that, now that I understand more of how the data structure works.   (If we want to show the actual chain of ties, we'd use a network tree view.)  

I think this view would be as if each network vertex had a 'gene' consisting of the list of ids of all its parents in the infection tree.  The phylo tree would be a map of the the relationships between these genes, so I think all 'sibling' nodes would be collapsed into a single node in the tree.   So we couldn't show timing in this mode.  But is this useful?

**Comment by smjenness** [comment]
I want to check tomorrow with one of our phylogenetic colleagues on the best approach. I'll get back to you.

**Comment by skyebend** [comment]
hi sam, can you check if dendo_plot branch gives functionality you want for now?  If so, I'll clean it up for merge

**Comment by smjenness** [comment]
@skyebend I finally checked this out. I think this is a great start and a good place to push at this point. I wonder if we could keep ape as a suggest rather than an import at this point? Thanks for all your work on this.

**Comment by skyebend** [comment]
I think I had to make ape an import for the S3 dispatch to work correctly.  Originally I had as.phylo.transmat  requireNamespace ape only when it was called, but  since the as.phylo S3 generic was only loaded when package loaded, it didn't work.    I think it would work if users call as.phylo.transmat(tm) instead of as.phylo(tm).  Should I set up the docs and tests that way instead?

**Comment by smjenness** [comment]
How does it work in `ape` for the `phylo` to `network` class conversion? `ape` doesn't have `network` listed as any form of dependency.

**Comment by skyebend** [comment]
calling `as.network`  on an object of class `phylo` similarly fails if `network` is not loaded to provide the `as.network(...)` S3 generic  (`as.network.phylo` of course still works)

**Comment by smjenness** [comment]
ok - can we do the same thing for now? I would like for now to keep it off the imports until we have more time to test and work on some more robust methods linking epi simulations and phylo tree analyses.
