### ISSUE TITLE
docs for control.net 'start' and 'nsteps' params need corrections

### ISSUE THREAD

**Issue by skyebend** [statnet/EpiModel#233]
"start	 For dependent simulations, time point to start up simulation."  default value is 1, but seems like it is effectively set internally to 2.  User can set it greater, but not less

```
 ### TIME LOOP
    for (at in max(2, control$start):control$nsteps) 
```

"nsteps Number of time steps to simulate the model over. This must be a positive integer."  

It seems like this is actually the ending timestep of the sim, not the number of steps in the sim?  

From the docs, I would expect that
```
control <- control.net(type = "SI", start=0, nsteps = 10, nsims = 1)
```
would run from 0 to 9, but if I look at the transmat

```
> head(get_transmat(episim))
  at sus inf transProb actRate finalProb
1  2 169  10         1       1         1
2  2  93  10         1       1         1
3  3 418 169         1       1         1
4  3 947  93         1       1         1
5  3 792 169         1       1         1
6  4 326 418         1       1         1
> tail(get_transmat(episim))
   at sus inf transProb actRate finalProb
6   4 326 418         1       1         1
7   5 156 326         1       1         1
8   6 944 156         1       1         1
9   7 250 944         1       1         1
10  8 309 250         1       1         1
11  9  13 309         1       1         1
```

and I would think that if I don't change nsteps, but start later, it should still run the same number of steps, from 5 to 15.  But it actually runs from 5 to 10. 

```
control <- control.net(type = "SI", start=5, nsteps = 10)
```

```
> head(get_transmat(episim))
  at sus inf transProb actRate finalProb
1  5 169  10         1       1         1
2  5  93  10         1       1         1
3  6 792 169         1       1         1
4  6 418 169         1       1         1
5  6 947  93         1       1         1
6  7 326 418         1       1         1
> tail(get_transmat(episim))
  at sus inf transProb actRate finalProb
4  6 418 169         1       1         1
5  6 947  93         1       1         1
6  7 326 418         1       1         1
7  8 156 326         1       1         1
8  9 944 156         1       1         1
9 10 250 944         1       1         1
```

**Comment by smjenness** [comment]
Thanks, I agree I need to clarify the documentation. In our simulations, time always starts at 1 (so start must be >= 1), at which the initialization module is run, and the earliest transmission would occur is time step 2. If you choose a start that is > 1, this is designed for restarting an existing prior sim (so you would run from steps 1 to 10, change something up, then set start to 11 and nsteps to 20, for example).
