### ISSUE TITLE
calculation of new births in network tutorial (very small point)

### ISSUE THREAD

**Issue by jtm6** [statnet/EpiModel#236]
Steve pointed out that
  exptPopSize <- dat$epi$num[1] * (1 + growth.rate * at)
probably should be
  exptPopSize <- dat$epi$num[1] * ((1 + growth.rate)^ at)

**Comment by smjenness** [comment]
@sgoodreau The point here was to have population growth as modeled as a linear process (not necessary a demographic one -- need to remove all references to birth in our code!), so the original code was correct.
