### ISSUE TITLE
bad url in param.net docs

### ISSUE THREAD

**Issue by skyebend** [statnet/EpiModel#239]
the statnet checks came up with the following note:

Found the following (possibly) invalid URLs:
  URL: http://statnet.csde.washington.edu/EpiModel/nme/d4-tut3.html
    From: man/param.net.Rd
    Status: 404
    Message: Not Found

Looks like much of the contents in the EpiModel/nme directory were deleted?

**Comment by smjenness** [comment]
Fixed in ad34eca84c7f5238cd5048e22b68208dc09c9d0c
