### ISSUE TITLE
Unexpected behavior from get_formula_terms when `offset` included?

### ISSUE THREAD

**Issue by skyebend** [statnet/EpiModel#248]
I'm debugging a model initialization problem and finding that for a formation model `~edges + offset(nodematch("role", diff = TRUE, keep = 1:2))`  the  `copy_toall_attr` doesn't seem to be copying the initial values of the 'role' network attribute into `dat$attr$role`.  This appears to be because it is expecting a list of attribute names to copy from `get_formula_terms` , but it is returning `NULL` .    It seems like the problem is the `offest` in the formula

```
> get_formula_terms(formula(~edges + offset(nodematch("role", diff = TRUE, keep = 1:2))))
NULL

> get_formula_terms(formula(~edges + nodematch("role", diff = TRUE, keep = 1:2)))
[1] "role"
```

**Comment by smjenness** [comment]
This was fixed in https://github.com/statnet/tergmLite
