### ISSUE TITLE
Add grid = TRUE/FALSE toggle for all plots

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#252]
This would go in the arguments of all the plot functions within EpiModel. If `grid = TRUE` then after plotting the plot but before adding the legend, we would add:

```r
grid()
```

**Comment by kweiss2** [comment]
@smjenness Do you want this option added to the tutorials as well (e.g. functions like renderPlot outside of the plot.R file?

**Comment by kweiss2** [comment]
They show up in the shiny app - server files

**Comment by smjenness** [comment]
Oh right -- no you don't need to have toggles for this in the Shiny apps
