### ISSUE TITLE
Support diagnostics for heterogeneous dissolution models

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#258]

**Comment by sgoodreau** [comment]
Hey @netterie - @martinamorris thinks you may have written some code for this (where *this* means code that will calculate and plot mean relational duration according to the different subsets of ties implied by different dissolution models).  Is that right? Here we need the code to be general, but even if you've done it for just your specific case it would help as a starting point.

**Comment by netterie** [comment]
@sgoodreau, @martinamorris :
Yes - there are two functions in the egonet package that may be useful, for **edges + nodefactor** dissolution:
1. ```egonet::edgelist_meanage_hetdiss``` - extension of ```EpiModel::edgelist_meanage```
2. ```egonet::plot_hetdiss``` - plotting function for the output, sort of like ```EpiModel::plot.netdx``` but much simpler

See the help files for these functions - there's an example using a _faux.mesa.high_ model. In the example, I turn it into egodata, run an ergm.ego model, and then construct a netest object. But in theory it should work for a traditional netest object with **edges + nodefactor** dissolution. No other dissolution model is coded up. The general structure may be useful for adding other dissolution terms, but I'm not sure - it may be too simple.

To install egonet, use an auth_token:
```devtools::install_github("statnet/SHAMP/egonet", auth_token="[insert]")```

You can also just view the code for both functions at [egonet/R/edgelist_meanage_hetdiss.R](https://github.com/statnet/SHAMP/blob/master/egonet/R/edgelist_meanage_hetdiss.R). There are comments indicating how ```egonet::edgelist_meanage_hetdiss``` differs from [```EpiModel:edgelist_meanage```](https://github.com/statnet/EpiModel/blob/master/R/net.utils.R). 

Here's what the plot looks like for the edges+nodefactor("Race") dissolution in the example. Dashed lines are the targets.

![image](https://user-images.githubusercontent.com/4825649/44481028-a2b4d580-a5f9-11e8-9965-e969f00dd0fd.png)

**Comment by smjenness** [comment]
Earlier version of #459 by @martinamorris. Closing this one.
