### ISSUE TITLE
Initial infection time assignment behaves poorly in network models when both recovery and deaths are present

### ISSUE THREAD

**Issue by sgoodreau** [statnet/EpiModel#264]
Lines 262-264 of `net.mod.init.R` are:

```r
# If vital=TRUE, infTime is a uniform draw over the duration of infection
  if (dat$param$vital == TRUE && dat$param$di.rate > 0) {
    infTime[idsInf] <- -rgeom(n = length(idsInf), prob = dat$param$di.rate) + 2
```
If both vital dynamics and recovery are present, then this is the code run to assign `infTime` (since `vital==TRUE`). But then the calculation for the probability distribution on `infTime` only involves `di.rate`, not `rec.rate`. 

(FYI This came up as a real issue when Emily P was using `EpiModel` for her class project in Ruanne B's class, since she was modeling partner services for chlamydia among young adults.  The very high recovery rate and very low mortality rate yielded crazy infection times.  She overrode it for her project easily enough, but it should also be easy to fix in the code itself, at least when recovery is memoryless, since you can just do a geometric distribution with parameter equal to the `di.rate + (1-di.rate)*rec.rate`.  (Just taking the sum is fine when rates are low, but this form accounts for competing risks and is a bit safer for higher rates).  It might get tricky if recovery is deterministic and death is stochastic though.

**Comment by smjenness** [comment]
There are so many different variations across the different disease types, with and without vital dynamics, with both recovery and mortality in the infected state possible to be both stochastic and deterministic. 

And lookie what I found here: #63 

I think the answer is to adopt your general approach above as the default, but for maximum flexibility to add a recov.vector for a user to pass in an externally defined infection time (relative to $t_1$), which would align with how we allow users to pass in a vector of disease statuses: https://github.com/statnet/EpiModel/blob/master/R/init.R#L155-L158
