### ISSUE TITLE
Fix netdx simulation with dynamic=FALSE

### ISSUE THREAD

**Issue by martinamorris** [statnet/EpiModel#269]
It turns out this argument does not start a new independent simulation from the observed network for each of the nsims, as one might assume.  Instead,  each new sim is started where the prior sim left off, and this can lead to temporal correlation (that become visible in the plots). 

The reason is that there is a argument in simulate.ergm and simulate.formula "sequential" that defaults to TRUE.

I think the best solution would be to have dynamic=FALSE automatically invoke sequential=FALSE.  Can't see a use case for dynamic=F and sequential=T...

h/t to @dth2 for tracking this down

**Comment by smjenness** [comment]
Thanks for finding this. The `dynamic=FALSE` diagnostics are an attempt to easily mimic the MCMC diagnostics, so the line plots from `netdx` are MCMC traces, not temporal patterns. Given that, should we still be using `sequential=FALSE`?

**Comment by martinamorris** [comment]
If you think there is a use case for sequential=TRUE -- e.g., a version that mimics MCMC diagnostics -- then what we need is an argument to netdx that allows us to access the sequential=T/F options.

For us, and perhaps for others, our expectation was that sequential=F would trigger a new simulation from the original network each time, not a new simulation from the final network produced by the previous simulation.   There's a longer discussion here about why that is important for our current application, but for now, I think there's a reasonable argument to be made that it should be possible to access that functionality from netdx.

So, maybe a new argument "sequential" where T means start the next sim from the last prev net, and F means start each sim from the original net?

**Comment by smjenness** [comment]
@martinamorris: Sequential argument to `netdx` added as requested!

Example code:
```r
nw <- network.initialize(100, directed = FALSE)
formation <- ~edges
target.stats <- 50
coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 25)

est <- netest(nw, formation, target.stats, coef.diss, verbose = FALSE)

dx1 <- netdx(est, nsims = 1000, dynamic = FALSE,
             nwstats.formula = ~edges + meandeg + concurrent,
             sequential = FALSE)
```

**Comment by martinamorris** [comment]
> @martinamorris: Sequential argument to netdx added as requested!

thank you!!
