### ISSUE TITLE
Update documentation and tutorials relating to the "death" correction to talk about "departures"

### ISSUE THREAD

**Issue by sgoodreau** [statnet/EpiModel#273]
We have a couple of applied projects where this point has confused people.  It may be that this is all as in-shape as it can be, but worth at least a review.

**Comment by martinamorris** [comment]
yeah, i'm thinking we really need to change our terminology.  the fact 
that we used to think of it as death is not a justification...

**Comment by martinamorris** [comment]
> And we should do the same with "births" -> "arrivals"

yep

**Comment by smjenness** [comment]
@andsv2 Could you please go through all of our Roxygen docs and make these changes on a new branch?

**Comment by smjenness** [comment]
Closed with #290
