### ISSUE TITLE
Standardize and clearly document how relational durations/ages are calculated and presented in print.netdx and plot.netdx

### ISSUE THREAD

**Issue by sgoodreau** [statnet/EpiModel#274]
Right now plot gives you the age (so exhibits boundary conditions at the start of the simulation) while print givens you final duration (so exhibits boundary conditions at the end of the simulation). This is more confusing than it needs to be.

@smjenness has proposed simply removing the plot.  @martinamorris and I favor finding a way to preserve them but make them a bit more useful and clear.

**Comment by smjenness** [comment]
@sgoodreau @martinamorris If we could come up with a consensus about how we should handle this, I can assign it or handle it myself. We want to keep the relational age plot, but how should we calculate the duration print to be consistent. Here's the current approach to printing:

```r
    ncens <- which(sim.df[[1]]$onset.censored == FALSE &
                     sim.df[[1]]$terminus.censored == FALSE)
    durVec <- sim.df[[1]]$duration[ncens]
```

That is only durations that are not left or right censored are retained.

**Comment by martinamorris** [comment]
I wonder if it makes sense to have two plots.  One for the mean age of extant ties, with the target stat.  The other with a pdf of the duration distribution, and the mean clearly shown.

**Comment by sgoodreau** [comment]
I wrote some code to remind myself of the issue, and think about options, with parameter values selected to illustrate the issue clearly:

```{r}
library(EpiModel)
n.nodes = 100
nedges = 75
mean.reldur = 25
nsteps_netdx = 200
nsteps_nsims = 10

mynet <- network.initialize(n.nodes, directed=FALSE)
mynet <- netest(nw=mynet, formation = ~edges, 

library(EpiModel)

n.nodes = 100
nedges = 75
mean.reldur = 25
nsteps_netdx = 200
nsteps_nsims = 10

mynet <- network.initialize(n.nodes, directed=FALSE)
mynet <- netest(nw=mynet, formation = ~edges, target.stats = nedges, 
                coef.diss = dissolution_coefs(~offset(edges), mean.reldur))
mynetdx <- netdx(mynet, nsims = nsteps_nsims, nsteps = nsteps_netdx)

plot(mynetdx, type = "duration")
mynetdx
```
The plot gives what I think is useful information in a helpful way - it asymptotes to the expected answer, thus emphasizing that running your models more than a short period of time is often a good thing. It's also complemented by type="dissolution" plot, which is what drives home that the models are actually behaving as expected form the very beginning.  I think from the comments in this thread that we're all good with this plot, but correct me if I'm wrong.

The issue is with the info provided in mynetdx, which implies that durations are still short relative to expected ,even as the plot on age tells us that we reached our target long back.  So users think there's a problem when there's not.  The question is what to do.  Again, the dissolution numbers below it tell us that all is just fine, and savvy users will get that.  My understanding was that Sam recommended simply eliminating the duration info. But I do think that it's useful to keep in some form since duration is how normal people think, and our age plot shows that we have run the model long enough to get where we want to be in some sense.

Martina's suggestion for a pdf is, I think, based on the idea of introducing an additional plot - but what I think what we're looking for here is a summary measure when the object is printed out. And I think that distribution would still be based on the same data that our current summary stat is, and would have the same issue -- it'll be off for a much longer time than the age number will be. Heading into survival analysis to fix it is a lot more fancy than I think we want to do for *this* situation.  (But definitely part of where we're heading in thinking about real vs simulated relational durations overall).

An alternative is printing the relational age info instead of the duration info, with the x axis representing the time at which extant ties are investigated.  This has three advantages: it's easy; it reaches expectation quicker; and it's consistent with the plot.  But, it has downsides too. As we see over and over, age doesn't match people's intuition in the same way that duration does. The mean relational age = mean relational duration equality is endlessly confusing. And it only works for memoryless dissolution processes, so if we ever add other dissolution models into EpiModel, we've painted ourselves further into a corner.

Another option is to reduce the bias by not removing those relationships that are onset_censored.  You don't remove them from the age calculations (effectively assuming they start at time 1), so why remove them from the duration calculations? The math works out with having all initial ties beginning at time 1 (since it's a memoryless process), so that would help your diagnostics.

Or just remove it :-)

**Comment by sgoodreau** [comment]
I take my last option back ("Another option") -- a quick exploration shows it doesn't help much, and I now see why.  But I may have a better idea. When you do the mean *ages* of the relationships, you're only counting those that are still existing at a given time (that's the definition), and  by the latter half of the simulation, these are all OK because you're far enough from the beginning that the effects have worn off.  You can do just the flip for durations:  only report the mean duration length for the ties that were in existence at the start of the simulation.  These are the ones that have the most time to dissolve naturally without getting censored by the end of the simulation, so will give the most unbiased signal. Will run some code now and get back to you all.

**Comment by sgoodreau** [comment]
Well, that also didn't help as much as I expected - in my example it brought the mean up from 22.1 to 22.9 when the target is 25.  Full code, for those interested, is: 

```{r}

library(EpiModel)

n.nodes = 100
nedges = 75
mean.reldur = 25
nsteps_netdx = 200
nsteps_nsims = 1


mynet <- network.initialize(n.nodes, directed=FALSE)
mynet <- netest(nw=mynet, formation = ~edges, 
                target.stats = nedges, 
                coef.diss = dissolution_coefs(~offset(edges), mean.reldur))
mynetdx <- netdx(mynet, nsims = nsteps_nsims, nsteps = nsteps_netdx, keep.tedgelist = TRUE)

plot(mynetdx, type = "duration")
mynetdx

sim.df <- mynetdx$tedgelist

# Current practice
ncens <- which(sim.df[[1]]$onset.censored == FALSE &
                 sim.df[[1]]$terminus.censored == FALSE)
durVec <- sim.df[[1]]$duration[ncens]
mean(durVec)

# What my first thought suggested we should do
ncens <- which(sim.df[[1]]$terminus.censored == FALSE)
durVec <- sim.df[[1]]$duration[ncens]
mean(durVec)

# What we actually should do
ncens <- which(sim.df[[1]]$onset.censored ==TRUE)
durVec <- sim.df[[1]]$duration[ncens]
mean(durVec)
```

**Comment by sgoodreau** [comment]
Actually, I thought about it another minute, decided my last idea really ought to work, especially of no relationships actually survive all the way from onset to terminus. So I just redid the above run , and got 21.6 for current practice, 22.0 for my first guess, and 25.0 for my new-and-improved approach  I think the first one may have just been stochastic variation from samplish samples.  And indeed, in this better run none of the relationships go from onset to terminus.  I will stop for the evening now :-)

**Comment by smjenness** [comment]
@sgoodreau I wonder if you would consider working on this issue for an interim EpiModel release 1.8.0 probably to be published in Feb 2020?

**Comment by sgoodreau** [comment]
Sure.  I see the steps as:
(1) Steve reviews past discussions and explorations.
(2) Steve ponders possible options, and makes a presentation of their behavior with positives and negatives.
(3) Steve presents presentation to Sam and Martina
(4) Team decides
(5) Steve implements

Sound right?

**Comment by smjenness** [comment]
@sgoodreau Looks good to me, thanks!

**Comment by sgoodreau** [comment]
@smjenness I see lots of package releases happening, so I'm curious if you have an updated date for when the next EpiModel will be released. now that my course seems to be vaguely under control, I can prioritize this over the seroadaptation paper if you want.

**Comment by smjenness** [comment]
Please focus on the mixing paper for now

**Comment by smjenness** [comment]
@sgoodreau : just pinging you for this open issue again, when you have time. Thanks

**Comment by sgoodreau** [comment]
@smjenness Thanks for the ping.  I will bring it up for discussion at NMG next week to get feedback, and then see if @chad-klumb wants to tackle it or I can once the serosorting draft is back off my plate (should be next week).

**Comment by sgoodreau** [comment]
@smjenness @martinamorris 

We discussed this in NMG and folks came up with some good ideas.  (Thanks to Emily, Adam, Chad, Deven and Martina!)

Reminder of the issue:

- print.netdx calculates mean relational duration, and handles censoring through brute-force (removing any relationships that are either onset-censured or terminus-censored) in a way that maximizes bias and typically produces an estimate well below the value that users parametrize the model with, and which is printed beside.  This problem can be minimized with very long simulations, but the approach is asymptotic and slow.
- in addition to producing results that are confusing for users, the method is also inconsistent with the type of output given with plot.netdx. This plots the mean relational age of extant ties, and exhibits boundary issues at the start, although the user can directly view if and when these issues are overcome, making the plot useful.
- the inclusion of the value (and plot) of mean dissolution rates ameliorates all of this somewhat, but the continued presence of these oddities begs for improvement (or removal).

Note that in this issue we are only pondering solutions for purely homogeneous memory-less dissolution models. Adding in diagnostics for other dissolution models is a separate task for a future date.

Previous suggestions for options, along with their positives and negatives, include:

1. Remove the print.netdx duration entry and only include the dissolution proportion entry.  Main strength: trivially easy to implement. Main weakness: leaves only the dissolution info which is not the way most normal people think about these things.

2. Provide the mean age of extant ties, averaged across all time periods *after* a certain burn-in period.  Main strength: matches existing plot in some ways, should closely match target stat. Main weakness: feels a bit arbitrary and confusing.

3. Provide the ultimate mean duration for relationships that were present at the start of the simulation. Here you would effectively assume these all start at time 0, which is OK in terms of calculating a diagnostic because of memorylessness. If the simulation is reasonably long these should start to come close to the desired value sooner than the current method does.  Main strengths: easy, presents in terms of duration, which is familiar to people. Main weaknesses: Throws away most of the data. Again uses different metric from plot. The idea of assuming all relationships present at time 0 started at time 0 may see odd and problematic to folks used to thinking more in terms of formal data analysis than memoryless process theory. 

None of those feel very satisfactory.  At our NMG meeting, Emily raised another idea, which then others expressed variations on:

4. Impute starting times (in negative time) for the relationships that are present at the outset, based on the underlying memoryless dissolution model. Then print the summary statistic of mean relational age averaged across all relationships across all time points in the simulation.  Main strengths:  makes maximum use of data, generally matches plot concept.  Indeed, we could even choose to update the plot to use the imputed start times, and then it would also start at the expected value instead of at 0. Main weaknesses:  people may find the imputation to be "fake" and untrustworthy. If someone doesn't simulate a problematic model for very long, it could look like there is not a problem when there is (although also agreed that once we settle on a method, we should have a standard warning if people's simulations are short, based on the mean relational duration).

Some variations on this theme are:

- 4a. Calculate these negative onset times upfront, but hide them away for just this purpose and don't make the users very aware of them.
- 4b. Calculate these negative onset times upfront, and actually highlight them as something that may be useful for users (and include them in the timed edgelist), as there may be other purposes users have for them. This would be a bit of a shift from current practice, though, and could break backward compatibility, unless they were added as a separate piece of info rather than replacing the 0 (imp.onset?)
- 4c. Calculate these times on the fly only when doing netdx (and possibly plot.dx).

My top 3 order of preference is currently:

- 4b (with imp.onset and onset both present somehow)
- 4c
- 2

4b is, of course, the most work.  There are surely other options that could be considered that we haven't thought of yet, if none of these is deemed satisfactory.

Note: Martina suggested an additional feature that would be useful, above and beyond the edits to the duration summary statistics.  This is to provide a means for users to print out a Kaplan-Meyer plot of relational survival. This would allow the user to see not just that the mean is being matched, but that indeed the curve looks right (i.e. is exponential), and would easily account for right censoring through traditional survival analysis methods.  It should also be fairly easy. If we like this idea then I can file a separate ticket for it. Note that it would only work with onset=0 for the initial relationships, thus providing another reason why, if we go with 4b, we should keep both times (0 and negative) around rather than just one.

**Comment by smjenness** [comment]
Thanks @sgoodreau. If option 4 is just imputing relational start times from a distribution at the individual-level based on statistical assumptions (which we know are present for TERGM simulations), it seems like an easier approach (maybe call this option 1b) is to simply do this at a population level by presenting an estimate of the average duration in the tables as the reciprocal of the simulated dissolution proportion tracked in netdx. What is gained by doing this for individual relations based on the the geometric distribution assumption versus doing it at this aggregate level? Furthermore, this aggregate approach might transfer more easily for non-homogenous dissolution models in which drawing the negative onset times gets even more complicated (see #459).

**Comment by sgoodreau** [comment]
It's a little bit more complicated than what (I think) you're saying, although your idea to just calculate a population mean rather than individual values still applies, and is a good one.

To clarify: we still use the observed relational age information that we have for all relationships that start after initialization.  But for relationships that are onset censored, we add an expected additional age onto the beginning.  In the version I was thinking of, we would draw a value for each individual relationship from the exponential distribution.  But you're right that instead of doing that we could just add the mean of the exponential distribution for all of them. In other words, at time t, the mean relational age is a weighted average of [mean observed relational age of non-onset-censored ties] and [mean observed relational age of onset-censored ties plus D].  This metric should start out right at the expected value, and stay there, and gradually transition over from being comprised of imputed values to observed values.  

Indeed, we could even revise the plot so that it had both values on it: you would see the same line you see now, coming up from zero to the expected value over time, and a second one starting out around the expected value and continuing there.  This latter one would progressively consist of more observed data and less imputed data.  The two would converge once the last onset-censored tie is broken.

The value of doing this over you 1b is that it still uses the observed relational ages as much as possible, rather than throwing out that info, and thus helps users to see the data from a second angle rather than just exactly the same info as in the dissolution.

Is that clearer? I could code up a mock-up if that helps.
