### ISSUE TITLE
Incorrect Population Size Displayed on Epidemic Simulation Progress (Verbose = TRUE) with SEIR Model

### ISSUE THREAD

**Issue by connor-vanmeter** [statnet/EpiModel#280]
The epidemic model control type may not be specified in the control.net control settings step of building the epidemic model when sourcing from a custom module. When the epidemic model control type (x$control$type) is not specified, 'Verbose.R' calculates the population of an SEIR model as if it was an SI model. (Possibly due to default setting when x$control$type is missing?)

As a result, the SEIR model population is being calculated by summing together the susceptible and infected individuals and is excluding exposed and resistant individuals. An enhancement may be to generalize the formula used to calculate population in Verbose.R by summing number of active nodes in the network rather than summing the population in each compartment of the model.

**Comment by smjenness** [comment]
@connor-vanmeter will correct this by calculating the population size as `sum(dat$attr$active == 1)`

**Comment by connor-vanmeter** [comment]
Closed with #289
