### ISSUE TITLE
Reorganization of built-in modules for network models

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#281]
- [ ] Split each module into two for bipartite models (one version for one-mode, one version for two-mode)
- [ ] `control.net` or check module automatically selects function associated with module
- [ ] Move all networkDynamic activity to a separate module that runs right before prevalence module
- [ ] Two versions of the network simulation module
- [ ] Run full (cadilac) version of the model versus tergmLite version flag 
- [ ] Meta documentation listing organization of major modules

**Comment by andsv2** [comment]
Note: Shiny will need to be looked at in depth.

**Comment by smjenness** [comment]
This issue is redundant with the various EpiModel 2.0 overhaul issues. Closing.
