### ISSUE TITLE
Add T/F skip.dissolution to netdx

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#311]
This would skip over the calculations of duration and dissolution stats in netdx, which can be time consuming for large models. The default would be FALSE. 

There also must be updates to the print and plot functions for netdx class objects to handle these objects that have no associated data.

**Comment by connor-vanmeter** [comment]
Including a plot.netdx fix for dissolution plots in this issue commit as well.
Please see below.

For this code block in plot.R for netdx dissolution plots:
`#Dynamic scaling based on sim.lines and smoothed or unsmoothed mean lines and quantile bands`
`    if (length(da) > 0 && !is.null(da$ylim) && dynamic == TRUE) {                                                       `
`      ylim <- da$ylim                                                                                                                                `
`    } else if (is.null(da$ylim) & sim.lines == FALSE & dynamic == TRUE & (mean.line == TRUE || qnts ==` `TRUE)) {                                                                                                                                                   `
`      ylim <- c(min(qnt.min * 0.9, mean.min * 0.9), max(qnt.max * 1.1, mean.max * 1.1))                        `
`    } else {                                                                                                                                                 `
`      ylim <- c(0, max(sapply(prop.diss, max, na.rm = TRUE)) * 1.1)                                                         `
`    }                                                                                                                                                           `

ylim <- c(min(qnt.min * 0.9, mean.min * 0.9), max(qnt.max * 1.1, mean.max * 1.1))
was originally set to
ylim <- c(min(qnt.min * 1.1, mean.min * 1.1), max(qnt.max * 1.1, mean.max * 1.1))

This resulted in the dissolution plot having incorrect lower bound ylim.

Code for reproduction of error:
`nw <- network.initialize(100, directed = FALSE)`
`formation <- ~edges`
`target.stats <- 50`
`coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 2)`
`est <- netest(nw, formation, target.stats, coef.diss, verbose = FALSE)`
`dx1 <- netdx(est, nsims = 1, nsteps = 500, skip.dissolution = FALSE)`
`plot(dx1, type = "dissolution")`


I did a quick search for similar types of errors in setting the ylim for formation and duration plots but those looked to be correctly set.

**Comment by connor-vanmeter** [comment]
Test Scripts:

```
nw <- network.initialize(100, directed = FALSE)
formation <- ~edges
target.stats <- 50
coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 2)
est <- netest(nw, formation, target.stats, coef.diss, verbose = FALSE)
```

##Tests

  #Case 1: skip.dissolution = FALSE
    #Expect netdx to calculate formation, duration, and dissolution statistics
    #Expect netdx to print both the Formation and Dissolution Diagnostics
    #Expect netdx duration and dissolution plots to succeed

    dx1 <- netdx(est, nsims = 1, nsteps = 500, skip.dissolution = FALSE)
    dx1

    plot(dx1, type = "duration")
    plot(dx1, type = "dissolution")

  #Case 2: skip.dissolution = TRUE
    #Expect netdx to calculate formation statistics only
    #Expect netdx to print only the Formation Diagnostics
    #Expect netdx duration and dissolution plots to fail

    dx2 <- netdx(est, nsims = 1, nsteps = 500, skip.dissolution = TRUE)
    dx2

    plot(dx2, type = "duration") #Expect error
    plot(dx2, type = "dissolution") #Expect error
