### ISSUE TITLE
Percent difference is 1/100th of what it should be

### ISSUE THREAD

**Issue by Shmelder** [statnet/EpiModel#314]
In some of the tables output by netdx columns report "pct diff", but are not percentages.  I think they should be multiplied by 100 to give percentages.  

I have found this in a few places: 

https://github.com/statnet/EpiModel/blob/ea6aa169138ef7099ff6a175a6dd07b7ff296e4f/R/netdx.R#L305-L308

https://github.com/statnet/EpiModel/blob/ea6aa169138ef7099ff6a175a6dd07b7ff296e4f/R/netdx.R#L404

https://github.com/statnet/EpiModel/blob/ea6aa169138ef7099ff6a175a6dd07b7ff296e4f/R/netdx.R#L410-L411

**Comment by smjenness** [comment]
Sure, do you want to take a crack at updating @Shmelder? You can branch and pull request the updates.

**Comment by Shmelder** [comment]
I am not sure I created the pull request correctly.  I was not able to make any changes to the actual repository (including creating new branches), so I forked, then submitted a pull request.

Let me know if I should do something different in the future.  Thanks!

**Comment by Shmelder** [comment]
I am not sure I created the pull request correctly.  I was not able to make any changes to the actual repository (including creating new branches), so I forked, then submitted a pull request.

Let me know if I should do something different in the future.  Thanks!
