### ISSUE TITLE
Network "bipartite" reference in net.mod.status

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#321]
https://github.com/statnet/EpiModel/blob/1a5b812f2be9193b615c5d4d603983daa0737900/R/net.mod.status.R#L236

**Comment by smjenness** [comment]
This is saying: if the susceptible person is in the first mode, then apply the `inf.prob` parameter, else if the person is in the second mode, apply the `inf.prob.g2` parameter. You will need to update that to look up the group number of each susceptible person in the discordant edgelist `del`.

**Comment by smjenness** [comment]
@andsv2 Can this be closed?
