### ISSUE TITLE
More informative errors in dissolution_coefs

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#326]
Currently the function `dissolution_coefs` returns an error if duration is too long relative to expected mortality rates. A more informative error on how to address this given the new ARTnet package is needed.

**Comment by smjenness** [comment]
@andsv2 Status update

**Comment by andsv2** [comment]
Right now, "informative" is simply what the `d.rate` in the `dissolution_coefs` function needs to be in order to be compatible with `duration`; in the case of multivariable dissolution model, gives the position of term that needs to be adjusted.

**Comment by smjenness** [comment]
So can this has been merged into master or _s4, and can be closed?

**Comment by andsv2** [comment]
Closed with: https://github.com/statnet/EpiModel/pull/331
