### ISSUE TITLE
Sensitivity analysis doesn't allow varying initial conditions?

### ISSUE THREAD

**Issue by henry-ngo** [statnet/EpiModel#329]
More of a question.

Passing a vector for a parameter in for example, `param.dcm()`, will cause multiple model runs, with each set of values in the vector.

However, this does not seem to work for parameters in `init.dcm()`. Looking at the source code, this seems by design---sensitivity analysis only checks for `params` with vector inputs. 

Is this intended behaviour? If I want to vary the number initial infected people, for example, should I just create and run different models?

**Comment by smjenness** [comment]
@henry-ngo Sorry, I did not see your issue until just now. Yes, that's right, the built-in sensitivity analyses are limited to sets of parameters, not initial conditions. If you want the latter, you will need to loop over the `dcm` function.

**Comment by henry-ngo** [comment]
Thanks for the tip! (Sorry also for the slow reply)
