### ISSUE TITLE
Checking a code block in netest.r

### ISSUE THREAD

**Issue by martinamorris** [statnet/EpiModel#330]
@smjenness  i'm looking at how you adjust the formation coefs for dissolution for the `edapprox` approach:

https://github.com/statnet/EpiModel/blob/1a609bead8a02393f6f1ee70bf7c026a13b76180/R/netest.R#L190-L194

Does this make assumptions about the order of the formation and dissolution coef vectors?  it seems like 
* it's assuming that the diss coefs are in the same order and same position as the formation coefs, and 
* that the formation coefs that need to be ajusted are all at the front of the formation coef vector.

If so, is that assumption always met?  Or does it require careful specification of the models to ensure the order is as expected?

**Comment by smjenness** [comment]
Yes, the `diss_check` function makes sure of that correct specification.

**Comment by martinamorris** [comment]
Ideally though we would want a more flexible approach that identifies the form coefs that match the diss coefs and adjusts, right?

**Comment by smjenness** [comment]
Essentially, yes that's what it does

**Comment by martinamorris** [comment]
From this

https://github.com/statnet/EpiModel/blob/18a2ac9e0ec36c6466fd628c70fed0ea799cbc4d/R/netest.R#L279-L281

It looks like the terms still need to be in the same order in both models.  Am I reading that right?

**Comment by smjenness** [comment]
That's right

**Comment by martinamorris** [comment]
Ok to reopen this issue then?  I'd like to ask Chad if he can update the code to allow for arbitrary order evaluation.

**Comment by smjenness** [comment]
ok, but with very low priority for MIDAS

**Comment by smjenness** [comment]
This was addressed in EDA work by @chad-klumb. Closing now...
