### ISSUE TITLE
Task 5: Add a flag to control settings for use.tergmLite to select full version of module function

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#334]
##### Goals
- Two main ways to run EpiModel 
   1. slow full-feature version, with tergm:  
       - any possible ergm term in formation and dissolution 
       - full functionality of networkDynamic object (ndtv) 
   2. Fast limited-feature version, with tergmLite 
       - set of ergm terms commonly used in our applied work
       - save out summary epi stats only (unless 7 is used) 
- Simple flag in the control settings to use tergmLite version or not 
-  If tergmLite = TRUE, then select the network resimulation and network update modules associated with tergmLite instead of tergm
#####  Steps
- [ ] Update control setting parameters 
- [ ] Selectively choose tergmLite version modules as replacements within control.net, unless we do Task 6 and it is up to the user

**Comment by smjenness** [comment]
Closing, as this is wrapped into work on Task 4 (#333)
