### ISSUE TITLE
Network Data Capture and Summary Stats API

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#335]
##### Goals
- With tergmLite approach, losing history of network structure and individual-level attributes 
- Although not useful for large, research-level simulations having a mechanism to track these for medium-level applications
##### Steps
- [ ] Add a new module that would capture and store edgelist and a limited set of individual attributes in matrix form 
- [ ] These would be captured only on the series of specified time steps 
- [ ] Process these back into networkDynamic objects at the end of the simulation or with an external utility function

**Comment by smjenness** [comment]
This is being addressed within Statnet and tergmLite by @chad-klumb
