### ISSUE TITLE
update_nwattr: random assignment of "group" parameter

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#340]
EpiModel Overhaul: Currently, when adding new arrivals to the network, network attributes are assigned randomly through the function `update_nwattr`. With the move from modes to groups in EpiModel Overhaul, `groups` is now a network attribute instead of a network feature. Thus, when arrivals enter into the network, instead of having their group assignment fixed it is instead randomized. This leads to imbalances in `test_net` and lack of equilibrium between CRAN and development versions of EpiModel.

Below is an example of the situation: at time step two there will be two arrivals, both in group 1. Once the the network attributes have been updated it will instead split group assignment between groups 1 and 2, with the first new arrival moving into group 1.

```
#Network setup 
num1 <- num2 <- 500
nw <- network::network.initialize(num1+num2, directed = FALSE)
nw <- network::set.vertex.attribute(nw, "group", rep(c(1,2), each = num1))
formation <- ~ edges + degree(0:1, by = "group") + nodematch("group")
target.stats <- c(330, 200, 275, 270, 155, 0)
coef.diss <- dissolution_coefs(dissolution = ~ offset(edges), duration = 50, d.rate = 0.01)
est <- netest(nw, formation, target.stats, coef.diss)

# Parameters
init <- init.net(i.num = 50, i.num.g2 = 50)
param <- param.net(inf.prob = 0.05, inf.prob.g2 = 0.05,
                   act.rate = 5, a.rate = 0.005, a.rate.g2 = 0.005,
                   di.rate = 0.005, ds.rate = 0.005,
                   di.rate.g2 = 0.005, ds.rate.g2 = 0.005)
control <- control.net(type = "SI", nsteps = 500, nsims = 100)

set.seed(123)

crosscheck.net(est, param, init, control)
dat0 <- initialize.net(est, param, init, control, s = 1)
dat <- dat0

at = 2

dat <- resim_nets(dat, at)
dat <- departures.net.grp(dat, at)
dat <- arrivals.net.grp(dat, at)
dat <- infection.net.grp(dat, at)
dat <- nw.update.net(dat, at)
dat <- get_prev.net.grp(dat, at)
```

**Comment by andsv2** [comment]
Note: Without random assignment, CRAN and development versions are in equilibrium and internally consistent across epistats.

**Comment by smjenness** [comment]
When you say:

>  instead of having their group assignment fixed it is instead randomized.

I think you mean, if for example there are 5 births/arrivals, 3 in group 1 and 2 in group 2, fixed means they get entered on the attribute list as:

`11122`

whereas random means they could get entered in any permutation of three 1's and two 2's. Right?
