### ISSUE TITLE
Network PIDS: Male, Female

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#341]
In `init_pids` does it make sense to change

https://github.com/statnet/EpiModel/blob/807bd5a7bdf88df7f194e48d1f314638cc0192b5/R/net.mod.init.R#L260

to "Grp1, Grp2" or something similar.

**Comment by andsv2** [comment]
Answer: no. However, how does `init_pids` work with `networkLite` object from `tergmLite`.

**Comment by andsv2** [comment]
Answer: It doesn't.

**Comment by martinamorris** [comment]
just my 2cents on this already closed issue.  there are other possible applications for diffucion on bipartite graphs (think kids and schools).  so for the purposes of generalization, it might be worth considering a generic bipartite labeling (b1 and b2 is what `ergm` uses).

**Comment by smjenness** [comment]
Yes, let's keep this open to revisit it once the tergmLite integration is complete.

**Comment by smjenness** [comment]
Closed in #354
