### ISSUE TITLE
Update EpiModel Gallery examples with new API

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#359]
When EpiModel 2.0 is released, these gallery examples all need to be updated.

https://github.com/EpiModel/EpiModel-Gallery

**Comment by martinamorris** [comment]
and if your CV19 cruise ship example is ready, getting a simple version of that up quickly would be great.

**Comment by smjenness** [comment]
It's here: https://github.com/EpiModel/COVID-CruiseShip

**Comment by smjenness** [comment]
Done!
