### ISSUE TITLE
Cancel dissolution edges

### ISSUE THREAD

**Issue by atilaajones** [statnet/EpiModel#387]
I want study a epidemic in a fixed graph. Is there a way to use the epimodel with a fixed graph, that is, without dissolving edges?

**Comment by martinamorris** [comment]
you can set the dissolution probability to -Inf

On Mon, 20 Apr 2020, atilaajones wrote:

> 
> I want study a epidemic in a fixed graph. Is there a way to use the epimodel with a fixed graph, that is,
> without dissolving edges?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AB6QTYVVKKWBDWRR7SKD473RNSXURA5CNFSM4MMYEIQ2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4
> I7ZAO7A.gif]
> 
> 
>

****************************************************************
  Professor Emerita of Sociology and Statistics
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by atilaajones** [comment]
Hello,

But I don't know where I set this probability. I put a long duration, but in the first step the graph changed. Sorry if my question is trivial. But I'm starter in R and this Package.

**Thank for your answer**

**I'll write the part of my test code to learn this library:**
_nw = graph with 5 vertices
est <- netest(nw, formation = ~ edges, target.stats = 6, coef.diss = dissolution_coefs(~ offset(edges),50))
param <- param.net(inf.prob = 0.5, act.rate = 2.5 ,rec.rate = 0.05)
control <- control.net(type= "SIR",nsteps = 6, nsims = 1, skip.check = TRUE, depend = FALSE, verbose.int = 0)
sim <- netsim(est, param, init, control)_

**Comment by smjenness** [comment]
Use a **very** long dissolution:

```r
nw <- network.initialize(100, directed = FALSE)
est <- netest(nw, formation = ~edges, target.stats = 6, coef.diss = dissolution_coefs(~offset(edges),1e9))
param <- param.net(inf.prob = 0.5, act.rate = 2.5 ,rec.rate = 0.05)
init <- init.net(i.num = 1, r.num = 0)
control <- control.net(type= "SIR",nsteps = 100, nsims = 1, skip.check = TRUE, depend = FALSE, verbose.int = 0)
sim <- netsim(est, param, init, control)
as.data.frame(get_network(sim))
```

You can check about the stability of the network with the last line, which outputs the timed edgelist. Hope that helps.

**Comment by atilaajones** [comment]
**(Very thank for your attention)**
Yeah. It's working!!
But in my example the edges are fixed only after simulation started. I inicialize a network: ok. After, all the steps the network is fixed, but diferent from the first. I'llpaste all the code here, observe the difference between the first graph and the simulation graphs (_run more than once_).

```
library(EpiModel)

adjacency_matrix <- matrix( c(0,1,1,0,0,  1,0,1,1,0,  1,1,0,0,1,  0,1,0,0,1,  
                              0,0,1,1,0), nrow = 5, ncol =5, byrow = FALSE,
                            dimnames = list(c("A","B","C","D","E"),c("A","B","C","D","E")))
adjacency_matrix
g <- network(adjacency_matrix, directed= FALSE)
nw<- as.matrix.network(g, matrix.type= "adjacency") 
plot(g)

est <- netest(nw, formation = ~ edges, target.stats = 6, edapprox=TRUE, coef.diss = dissolution_coefs(~ offset(edges),1e9))

param <- param.net(inf.prob = 0.5, act.rate = 2.5 ,rec.rate = 0.05)

init <- init.net(status.vector=c("i","i","s","s","s"))

control <- control.net(type= "SIR",nsteps = 6, nsims = 1, skip.check = TRUE, depend = FALSE, verbose.int = 0) 

sim <- netsim(est, param, init, control)

par(mfrow = c(1, 1))
plot(sim, y = c("s.num", "i.num", "r.num"),
     mean.col = 1:4, qnts = 1, qnts.col = 1:4, legend = TRUE)

plot(sim, type = "network", at = 1, sims = "mean", col.status = TRUE, main = "Prevalence at t1")
plot(sim, type = "network", at = 2, sims = "mean", col.status = TRUE, main = "Prevalence at t2")
plot(sim, type = "network", at = 3, sims = "mean", col.status = TRUE, main = "Prevalence at t3")
plot(sim, type = "network", at = 4, sims = "mean", col.status = TRUE, main = "Prevalence at t4")
plot(sim, type = "network", at = 5, sims = "mean", col.status = TRUE, main = "Prevalence at t5")
plot(sim, type = "network", at = 6, sims = "mean", col.status = TRUE,main = "Prevalence at t6")
```

**Comment by smjenness** [comment]
I see. It's not just that you want the network to have fixed edges, but that you want to work with an observed network census. The built-in models are all based around the fitting statistical models (ERGMs) to observed data. Your edges model here with a target statistic of 6 is the simplest model for that. If you want to run an epidemic over the exact model structure here, we have an extension example in the EpiModel Gallery showing how to do that: https://github.com/EpiModel/EpiModel-Gallery/tree/master/2018-08-ObservedNetworkData. However, be aware of the caveats to doing that discussed in the README file there.

**Comment by atilaajones** [comment]
Exactly. 
The target statistic is 6 because i was testing some values to fix my problem. I don't' know about ERGM, only Graphs Theory, maybe it's a problem for me.

Very thank you for your suggestion and attention @smjenness

**Comment by smjenness** [comment]
Please feel free to browse through our Network Modeling for Epidemics course materials to get a sense of how to work within this framework: statnet.org/nme.
