### ISSUE TITLE
Getting error from deleteAttr function

### ISSUE THREAD

**Issue by lc5415** [statnet/EpiModel#388]
Hello, 

I am building a network model with custom modules, when I activate the option `delete.nodes = TRUE` in my `control.net()` declaration after some iterations (~simulation time steps) I get the following error:
```
Error in deleteAttr(dat$attr, inactive) : 
  attrList must be rectangular (same number of obs per element)
```
I've imported the `departures.net()` source code to debug through but I seem to be getting the error at a `return()` statement. Any idea?

The error goes away when disabling the `delete.nodes` functionality, though I would prefer to use it for the computational benefit of doing so. It would also be helpful if someone could answer the following questions (maybe that way I can understand where the error may be coming from):

* When is `deleteAtt()r` called within the EpiModel workflow? I've also tried to find this but I did not succeed.
* What does `delete.nodes = TRUE` do that is different to the `deactivate.vertices()` function?

Due to all the module definitions, it does not seem very feasible to share a reprex, but do let me know if you think it is necessary for me to share one and I will do so.

**Comment by smjenness** [comment]
`deleteAttr` is called within the `resim_nets` function here, if `delete.nodes` is `TRUE`.
https://github.com/statnet/EpiModel/blob/master/R/net.mod.simnet.R#L100-L104

As you can see in that code snippet, it runs `network.extract` and then `deleteAttr`. The former takes the networkDynamic object, and then collapses it down to the current cross-sectional structure by removing any inactive nodes. One can have nodes on a networkDynamic object that are still on the data structure but not "active" (thus, deactivated) meaning they are not able to form ties (e.g., if those nodes represented deceased persons). Then deleteAttr essentially does the same thing for the attribute list in dat$attr. It's hard to know what specifically is going on in your case, but I imagine there is an inconsistency in the attribute list stored on dat$attr. I would debug the process with 

```r
debug(deleteAttr)
```

and then take a look at the lengths of the vectors on dat$attr with:

```r
sapply(dat$attr, length)
```

Hope that helps. We are nearly finished with a major revision to our model extension API that makes all of this much more transparent and easy. Hopefully released in the next few weeks.

**Comment by lc5415** [comment]
Thanks for your reply, that was as much detail as I needed. My application has not required me to investigate any further but if I ever need it I will resort to your answer! 

PD: I am very excited about the release of EpiModel 2.0!
