### ISSUE TITLE
Use new tergmLite intialize/get/set_ functions in EpiModel workflow

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#401]
With these new functions: https://github.com/statnet/tergmLite/pull/40

Replacements:
- [ ] `network_initialize` replaces `network.initialize`
- [ ] `set_vertex_attribute` replaces `set.vertex.attribute`
- [ ] `get_vertex_attribute` replaces `get.vertex.attribute`

**Comment by andsv2** [comment]
Closed: https://github.com/statnet/EpiModel/pull/405
