### ISSUE TITLE
Organize/edit Rmd's for web tutorials and NME materials

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#410]
This will allow for easier, centralized revision and version control.

**Comment by smjenness** [comment]
@clchand23 : can you please manage this? I'll put all the materials in a shared Box folder.

**Comment by smjenness** [comment]
The materials, Rmds and R scripts, from the Box folder should go into separate subfolders under inst/. For NME, put everything in one big older across the days as the files are numbered.

**Comment by smjenness** [comment]
For all of the NME Rmd files, can you add a brief descriptor into the file name (e.g., d2-s5-TERGMs.Rmd)

**Comment by smjenness** [comment]
@sgoodreau @martinamorris : We originally were wary of putting the Rmds up on Github, but with the EpiModel 2.0 overhaul, I want to put them all in `inst/` here to: consolidate the various tutorials, including language that may differ across the web tutorials versus the NME materials;  make good use of version control so we can track our edits and run unit tests on the diffs.

**Comment by clchand23** [comment]
The files have been added with descriptors for the NME file names

**Comment by sgoodreau** [comment]
Works for me.

> @sgoodreau @martinamorris : We originally were wary of putting the Rmds up on Github, but with the EpiModel 2.0 overhaul, I want to put them all in `inst/` here to: consolidate the various tutorials, including language that may differ across the web tutorials versus the NME materials; make good use of version control so we can track our edits and run unit tests on the diffs.
