### ISSUE TITLE
Bipartite graphs in EpiModel

### ISSUE THREAD

**Issue by martinamorris** [statnet/EpiModel#413]
I noticed in one of the more recent comments on the EpiModel Intro #409 that there seems to be some conflation of bipartite and multi-group models.  In SNA, bipartite means 2-mode (think, people and places), defined so that all ties are between modes.  Multigroup is quite different, and refers to attributes on nodes of the same "mode".  Ties can be both within and between group.

In mathematical graph theory, bipartite simply refers to a partitioning, where all ties are between the partitions.  There is no notion of "modes".

We used a bipartite model for a "one mode" network in the past for the purely heterosexual mixing.   Essentially, we were using the mechanism of a bipartite graph to force no ties within groups.   This use of bipartite would make sense to a graph theorist, but might be seen as odd by someone coming from SNA.

Just worth being a bit careful how you talk about this.  Esp. as we may want to make use of SNA type bipartite graphs for other modeling efforts (like Covid).  Multi-group doesn't make bipartite "more flexible", it makes it not bipartite.

**Comment by smjenness** [comment]
Thanks @martinamorris. As you know, we've used the term bipartite to refer to the purely dissortative mixing models for years (e.g., in our tutorials http://statnet.org/nme/d3-s4.html and papers https://www.jstatsoft.org/article/view/v084i08), and we have always conflated modes and edge partitioning. We're happy to move away from this bipartite language with EpiModel 2.0, but just understand that it involves walking back our own use/misuse of the bipartite term in those earlier materials.

**Comment by martinamorris** [comment]
I am aware.  We should probably just note the issue in our existing written materials, and be clear moving forward.

**Comment by andsv2** [comment]
@martinamorris I am updating the EpiModel2 introduction document to be clearer in this regard; may I ask what SNA stands for?

**Comment by smjenness** [comment]
social network analysis. There are several "camps" that use network methods, and the language may different. SNA refers to people coming from the social sciences background, and network science and graph theory is more aligned with applied math, physics and computer science.

**Comment by martinamorris** [comment]
Social Network Analysis

It's an interdisciplinary subfield in the social sciences.
