### ISSUE TITLE
Accessor functions after simulation

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#414]
Is there any interest in this? Currently the accessor functions are only set up to be used during simulation (when the objects they are operating on are vectors). If so, this would need to be updated as the below returns an error.

```
nw <- network_initialize(100)
formation <- ~edges
target.stats <- 10
coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 20)
est <- netest(nw, formation, target.stats, coef.diss)

param <- param.net(inf.prob = 0.1, act.rate = 5)
init <- init.net(i.num = 10)
control <- control.net(type = "SI", nsteps = 100,
                       tergmLite = FALSE)

sim <- netsim(est, param, init, control)
get_epi(sim, "i.num", 50)
```
Returns an error.

**Comment by smjenness** [comment]
No, need as the as.data.frame method is used, and data frames have a standard and expected data structure for R users.

```r
df <- as.data.frame(sim)
df$i.num[50]
```
