### ISSUE TITLE
Sequential transitions vs. State transition matrix & one-to-many state transitions

### ISSUE THREAD

**Issue by lc5415** [statnet/EpiModel#417]
By default, `EpiModel` modules work as a pipeline through which the individuals (represented in the `dat` object) pass through at each time step (represented by the `at` counter). 

The pipeline is composed of the several modules (e.g. Susceptible-> Infected transition, Infected -> Recovered transition) and the dynamics are governed by rates/probabilities. To determine whether someone transitions to a different state we simply draw from a Bernouilli distribution to see whether individuals transition to a new state or remain in the current state. That is at least my interpretation of the default `EpiModel` implementation but please _do correct me if I am wrong_.

In the base SIR model, the state sequence is S -> I -> R, it is a one-way path with no branches. In such a scenario, modelling transitions in sequences at each time step is sensible and does not result in any undesired behaviour. I find myself modelling a more complex state-transition  set-up. It could be argued that these extra states are not essential but I think there is a place for it and I do not want to discuss this here.

My state transition graph looks like this (inspired from @timchurches work):
![IMG_0D5F533E26D7-1](https://user-images.githubusercontent.com/47890755/82340317-034b8f00-99e7-11ea-8b73-56dcb8974f05.jpeg)
In this case if I were to model state-to-state transitions one at a time (i.e. I->Q, I->H), the computations would not actually take place the way they are meant to be. This is somehow complex, so _I will try to illustrate my point further._

Let's consider the transition from I to either Q, H or R (as a subsystem). Let's consider having 100 infected individuals and:

* A probability of transitioning to the Q state of 0.2 (probability of remaining in I of 0.8) and then,
* A probability of transitioning to H of 0.05 (probability of remaining of 0.95) and finally,
* A probability of recovering of 0.2 (0.8 probability of remaining in I). 

Evidently these processes are presented as independent and isolated from one another, but of course, they are not. __One could easily see that in this case, the order in which we model the transitions from I to either state will impact the model output. If model sequentially, the probability of remaining in I is actually lower than it would if the problem were to be considered as one-step multi-state system (as presented in the next diagram).__ I am not sure if this a problem that has previously been raised or if it is actually considered a problem at all. To me at least, it seems to present a problem.

The way I would think of solving this issue is modelling all the transition with one-step matrix multiplication (similar to how transitions work in [Markov Chain modelling](https://en.wikipedia.org/wiki/Stochastic_matrix)). The dilemma is illustrated in the picture below
![IMG_B0B8E1BE651C-1](https://user-images.githubusercontent.com/47890755/82347636-cc2dab80-99ef-11ea-8ab3-cc9ce45ad18f.jpeg)

I still see problems with this solution because the state matrix (S) output will be deterministic at each time and a person will be attributed a given probability of being in either state at any given time instead of either a 0 or a 1 as it should be.

Please let me know what you think of this issue (and if you think it is an issue). Also do let me know if you have found other solutions to modelling one-to-many state transitions.

**Comment by AdrienLeGuillou** [comment]
I think the  [`markovchain` package](https://cran.r-project.org/web/packages/markovchain/index.html) allows such probabilistic matrix transition (I never used it though). You could build a module using it  I suppose.

I'd be interested to see this in action

**Comment by lc5415** [comment]
Thanks @AdrienLeGuillou for your response, I will try that in my experiments and see if the difference is significant. 

As per @sgoodreau advice, I will close this issue (as it's not really software related) and post it in the epimodel listserv.
