### ISSUE TITLE
Error when trying to set permanent edges

### ISSUE THREAD

**Issue by lc5415** [statnet/EpiModel#421]
I am trying to model a network of individuals where certain ties are fixed (i.e. `duration = Inf`) but I have come across several errors. If this is not a yet supported feature I think it would be a great feature to have. Please find below the description of a reprex:

In the below network with 100 nodes, 50 nodes have red as the colour attribute and 50 nodes have blue as the colour attribute. I wish to have all red nodes connected to all the other red nodes and all blue nodes connected to all blue nodes (permanently). To achieve this I am adding `offset("color", diff = FALSE)` and then setting `coef.form = Inf` in the `netest` call. This works and this achieves edges between nodes with the same colour to be always formed. BUT this nodes dissolution is governed by the dissolution coefficients terms. I have tried to set the edge duration to Inf for the `offset("color", diff = FALSE)` but I get the following error:
```
Error in if (form.length == 2 && t1.edges == TRUE && t2.term %in% c("nodematch",  : 
  missing value where TRUE/FALSE needed
```

Which I do not understand. I think that the use of `offset` in the formation formula is not properly documented either.

Please find below a short script for reproducibility:
```
library(EpiModel)

n=100
nw = network.initialize(n = n,
                        directed = FALSE)

nw = set.vertex.attribute(nw, "color", c(rep("red", n/2),
                                         rep("blue", n/2)))

formation = ~edges + 
  offset(nodematch("color", diff = FALSE))

mean_degree = 50

edges = n*mean_degree/2

target.stats = c(edges)

coef.diss = dissolution_coefs(dissolution = ~offset(edges)+offset("color", diff = FALSE),
                              duration = c(1, Inf))

est <- netest(nw,
              formation,
              target.stats,
              coef.diss,
              coef.form = Inf,
              set.control.ergm = control.ergm(MCMLE.maxit = 500)
)
```

**Comment by smjenness** [comment]
Instead of using a duration of Inf, try using a duration of some very large value, such as this:

```r
coef.diss = dissolution_coefs(dissolution = ~offset(edges)+offset(nodematch("color", diff = FALSE)),
                              duration = c(1, 1e6))
```

**Comment by lc5415** [comment]
Thanks for the quick reply @smjenness , I’ve tried this but it doesn’t behave as expected. I’ll post a proof of this over the weekend. In short, even though the edge duration can be set very high the edges do get dissolved.

**Comment by smjenness** [comment]
And just to clarify, you are seeing that the edges matched on color are dissolving?

**Comment by lc5415** [comment]
Yes, that’s what I am seeing, it will become clear with the visualisation I will provide. This comment is based on a different piece of code than the one provided above.

**Comment by lc5415** [comment]
Hello @smjenness find below my results with several values for the edge duration going from 10 timesteps to 1e15 steps. Unfortunately, the edges are never made permanent and if I try to go above 1e15 I get:
```
Error: The competing risk of departure is too high for the given the duration in place 2. Specify a lower d.rate
```

### Results

In each of the below images (which simply show the adjacency matrix at 20 timesteps) I change the edge duration term corresponding to the offset `nodematch("color", diff = FALSE)` that is passed into the `dissolution_coefs()` function:

<details> 
<summary> Expand to see code to reproduce these images</summary>

```
library(EpiModel)

dur = 1e16 # edge duration for nodes with the same value for the color attribute
n=60
nw = network.initialize(n = n,
                        directed = FALSE)

nw = set.vertex.attribute(nw, "color", c(rep("red", n/2),
                                         rep("blue", n/2)))

formation = ~edges + 
  offset(nodematch("color", diff = FALSE))

max.edges = n*(n-1)/2

edges = 0.55*max.edges

target.stats = c(edges)

coef.diss = dissolution_coefs(dissolution = ~offset(edges)+
                                offset(nodematch("color", diff = FALSE)),
                              duration = c(1, dur))

est <- netest(nw,
              formation,
              target.stats,
              coef.diss,
              coef.form = Inf,
              set.control.ergm = control.ergm(MCMLE.maxit = 500)
)

cores = parallel::detectCores()-1

dx <- netdx(est,
            nsims = 1e3,
            nsteps = 90,
            ncores = cores,
            dynamic = FALSE,
            nwstats.formula = ~edges + nodematch("color", diff = FALSE),
            set.control.ergm = control.simulate.ergm(MCMC.burnin = 1e6))

print(dx)
## model
d.rate = 0

param <- param.net(inf.prob = 0.3, 
                   rec.rate = 0.02,
                   a.rate = 0,
                   ds.rate = d.rate,#0.001,
                   di.rate = d.rate,# 0.001,
                   dr.rate = d.rate# 0.001,
)

init <- init.net(i.num = 10,
                 r.num = 0
)

control <- control.net(type = "SIR",
                       nsteps = 20,
                       nsims = 3)

# Simulate the model with new network fit
sim <- netsim(est, param, init, control)

### GIF
library(animation)

nw_object = get_network(sim)
ani.record(reset = TRUE)  # clear history before recording
for (at in c(1:20)){
  
  net_at = network.collapse(nw_object, at = at)
  graph = intergraph::asIgraph(net_at)
  adj = igraph::as_adjacency_matrix(graph, sparse = F)
  
  colnames(adj) = igraph::V(graph)$color
  rownames(adj) = igraph::V(graph)$color
  
  adj = adj[order(rownames(adj)), order(colnames(adj))]
  
  pheatmap::pheatmap(adj,
                     color = c("grey50","black"),
                     border_color = "white",
                     angle_col = 45,
                     angle_row = 45,
                     fontsize = 6,
                     legend_breaks = c(0,1),
                     legend = FALSE,
                     cluster_rows = FALSE,
                     cluster_cols = FALSE,
                     show_rownames = FALSE,
                     show_colnames = FALSE)
  ani.record()
}

oopts = ani.options(interval = 0.5)
# ani.replay()
# saveHTML(ani.replay(), img.name = "network")
saveGIF(ani.replay(), movie.name = paste0("network",dur,".gif"))
```

</details>


### duration = 10
![network10](https://user-images.githubusercontent.com/47890755/84573975-a64fb880-ad9b-11ea-8a8c-8ba18950851b.gif)

### duration = 1e4
![network10000](https://user-images.githubusercontent.com/47890755/84573976-a6e84f00-ad9b-11ea-88ce-0ebc4ba1a67a.gif)

### duration = 1e7
![network1e+07](https://user-images.githubusercontent.com/47890755/84573968-a059d780-ad9b-11ea-873a-3f7cebe4b787.gif)

### duration = 1e12
![network1e+12](https://user-images.githubusercontent.com/47890755/84573971-a485f500-ad9b-11ea-9d2b-3921386e8122.gif)

### duration = 1e15
![network1e+15](https://user-images.githubusercontent.com/47890755/84573974-a5b72200-ad9b-11ea-982f-71bb672bff5a.gif)

**Comment by smjenness** [comment]
@lc5415 Please post or email me (samuel.m.jenness@emory.edu) your run script that generated the above so I can diagnose further. Thanks

**Comment by smjenness** [comment]
@lc5415 : what's happening here is that EpiModel is treating the network model as a (cross-sectional) ERGM rather than a TERGM, because a subset of edges have a dissolution of 1. If you change the duration of the unmatched edges to 2, you'll get the behavior you seek. 

```r
coef.diss = dissolution_coefs(dissolution = ~offset(edges)+
                                offset(nodematch("color", diff = FALSE)),
                              duration = c(2, 1e6))
```

You can diagnose the durations like so:

```r
nw1 <- get_network(sim)
df <- as.data.frame(nw1)

color <- nw1 %v% "color"
summary(df$duration[which(color[df$head] == color[df$tail])])
summary(df$duration[which(color[df$head] != color[df$tail])])
```

This does allow for some unmatched edges to have a duration > 1, but the median is 1 in my simulation. If you need a hard constraint on the duration of 1 in one subnetwork but >1 in another subnetwork, you'll need to use a multi-layer network (multiple models of edges on the same nodeset), but this involves quite a bit more code complexity. 

Hope that helps...

**Comment by lc5415** [comment]
@smjenness  This is great! I’ll give this a try tomorrow. Do you know of any way to obtain the desired behaviour while keeping the default edge duration to 1?

**Comment by smjenness** [comment]
> @smjenness This is great! I’ll give this a try tomorrow. Do you know of any way to obtain the desired behaviour while keeping the default edge duration to 1?

Yes, with multi-layer networks, as described above.

**Comment by lc5415** [comment]
Ok, it proves to be working. Just some final questions

* Additionally, I notice that if I set the expected number of edges to 0, the edges between the nodes sharing attributes take a few steps to build up, how would you explain that?

     <details>
    <summary> See image for example</summary>

     ![network1e+06](https://user-images.githubusercontent.com/47890755/85149046-c0c8dc80-b248-11ea-8ce7-9a42d11b011c.gif)

     </details>

* Is there any caveat to using an edge duration of 1.1 or 1.01 instead of 2? 
* I am unaware of any `EpiModel` tutorial covering how to create subnetworks or permanent ties, if it is not yet available I think it could be valuable.
* Where could I read some more about how to implement TERGMs in R?

**Comment by smjenness** [comment]
1. Although the durations are long enough that the edges are effectively fixed, this is still a temporal ERGM, so it is modeling the incidence of edges. 
2. I don't think so, although there may bound to be some potential issues with using the "edges dissolution" approximation for a duration this short; please see the `edapprox` argument in `netest` and make sure you are diagnosing the network model (e.g., with `netdx` before running the epi simulations)
3. It's not something that we have formalized yet in tutorials. We use in many of our full-scale research models, though, for both [HIV/STIs](https://github.com/statnet/EpiModelHIV) and now [COVID](https://github.com/EpiModel/EpiModelCOVID). 
4. You might start with the [TERGM package vignette](https://cran.r-project.org/web/packages/tergm/vignettes/STERGM.pdf)

Hope that helps! Feel free to close the issue if so.

**Comment by lc5415** [comment]
Thank you @smjenness for all your swift replies!
