### ISSUE TITLE
Test EpiModel 2.0 against Github versions of Statnet packages

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#427]
@andsv2 : would you please run R CMD Check and run through the EpiModel2 and JSS2 scripts of EpiModel and tergmLite masters against the github masters of ergm and tergm (using `remotes::install_github(...)`), and report on any errors/bugs in this github issue to @chad-klumb.

cc: @martinamorris

**Comment by andsv2** [comment]
@smjenness will do.

**Comment by chad-klumb** [comment]
I did quickly `check` EpiModel and tergmLite master branches; EpiModel appears fine, while tergmLite is having some "equal but not identical" test failures.  The first one I looked into was due to `maxval` being an integer in one case and a numeric in the other (both equal to 100 though).  I'll try to track down exactly where that discrepancy is arising.

**Comment by andsv2** [comment]
@chad-klumb I've run into that error before; after I finish updating some other work, I can revisit notes in the case you haven't tracked it down.

**Comment by chad-klumb** [comment]
I believe the test failures are addressed by statnet/tergmLite#44; with those changes, both `EpiModel` and `tergmLite` master branches pass `R CMD check` for me, with other statnet `master` branches installed.

I'm not familiar with the scripts Sam mentioned so I haven't tested those, but if anything goes wrong there please let me know.

**Comment by andsv2** [comment]
Evening @chad-klumb: can I get a session info from you?
```
sessioninfo::package_info(pkgs = c("network", "networkDynamic", "statnet.common",
                                   "ergm", "tergm"), dependencies = FALSE)
```

**Comment by chad-klumb** [comment]
Here's that:

```
> sessioninfo::package_info(pkgs = c("network", "networkDynamic", "statnet.common",
+                                    "ergm", "tergm"), dependencies = FALSE)
 package        * version     date       lib source                                 
 ergm             3.10.4-5582 2020-07-15 [1] Github (statnet/ergm@0ea962e)          
 network          1.17.0-413  2020-07-15 [1] Github (statnet/network@78caa79)       
 networkDynamic   0.10.1      2020-07-15 [1] Github (statnet/networkDynamic@157dede)
 statnet.common   4.4.0-272   2020-07-15 [1] Github (statnet/statnet.common@dc49897)
 tergm            3.6.2-1955  2020-07-15 [1] Github (statnet/tergm@dd178d6) 
```

Also `statnet/rle` is now a dependency:

```
> sessioninfo::package_info(pkgs = c("rle"), dependencies = FALSE)
 package * version date       lib source                      
 rle       1.0-210 2020-07-15 [1] Github (statnet/rle@6447a83)
```

**Comment by andsv2** [comment]
@chad-klumb wonderful. And thanks for the `rle` heads up; glad to be rid of that warning message.

**Comment by andsv2** [comment]
@smjenness EpiModel 2.0 R CMD Check passed on master versions of `ergm` and `tergm` as well as JSS2 and EpiModel 2 migration document examples.

**Comment by smjenness** [comment]
Thanks! @chad-klumb I merged in https://github.com/statnet/tergmLite/pull/44, so I think we're good to go. If you agree, please close this issue.
