### ISSUE TITLE
netsim cannot handle input of fitted network object with block diagonal constraint

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#435]
Models fit using the netest() function using a block diagonal constraint give an error when used in netsim().

**The error produced is:** "Error in ergm_proposal.formula(constraints, control$MCMC.prop.args.form,  : 
  The combination of class (f), model constraints (blockdiag), reference measure (Bernoullic("MPLE", "CD", "zeros")), proposal weighting (default), and conjunctions and disjunctions is not implemented. Check your arguments for typos."

**Minimal working example:**

    nw2 <- network.initialize(n = 90, directed=F)
    nw2 %v% "com2" <- c(rep(as.character(c(1:9)), each=10 ))
    fit1 <- netest(nw2, formation = ~edges , constraints = ~blockdiag("com2"), target.stats = c(200), coef.diss = 
    dissolution_coefs(dissolution = ~offset(edges) , duration = 25))

    param <- param.net(inf.prob = 0.3, act.rate = 1)
    init <- init.net(i.num = 5, r.num = 0)
    control <- control.net(type = "SI", nsteps = 50, nsims = 1, epi.by = "community", ncores=2)

    sim <- netsim(fit1, param, init, control)

**Comment by smjenness** [comment]
@chad-klumb : could you look into this, following up from your solution to the estimation problem.

**Comment by ThomasKraft** [comment]
In case it is helpful, as far as I can tell this error originates in the ergm_proposal() function (https://rdrr.io/cran/ergm/src/R/ergm_proposal.R). 

With a blockdiag constraint, It's not clear to me why an error is thrown when simulating from a stergm/netest object, but not when using simulate() with an ergm object. It's possible this issue was raised with @krivit ~1 year ago but never resolved? (http://mailman13.u.washington.edu/pipermail/statnet_help/2019/002760.html)

**Comment by chad-klumb** [comment]
This is the same issue I raised in my earlier response:

> There do not appear to be good formation/dissolution proposals in tergm master for this problem.  We can fit the models (as ergms) and do static netdx, but dynamic netdx or dynamic simulation more generally would require either very long intervals with a rejection setup or using tergm dev.

The formation/dissolution proposal options in `master` are extremely limited, and do not include support for a `blockdiag` constraint:

https://github.com/statnet/tergm/blob/dd178d6d7eea1db1bdf102ba89189dfa7631bd59/R/zzz.R#L59-L66

Technically this problem can be recast as a `bd` constraint but the resulting rejection algorithm would not be efficient.

**Comment by martinamorris** [comment]
@smjenness you noted earlier that you had a similar setup for one of your Covid models.  could that be used here?

**Comment by ThomasKraft** [comment]
@chad-klumb am I understanding your last suggestion correctly that a possible workaround is to reformulate as a `bd` constraint?

    nw2 <- network.initialize(n = 90, directed=F)
    nw2 %v% "com2" <- c(rep(as.character(c(1:9)), each=10 ))

    # try recasting as bd instead of blockdiag
    coms <- nw2 %v% "com2"
    attribs_com <- sapply(as.character(c(1:9)), FUN= function(x) coms == x)
    maxout_attribs_com <- attribs_com
    maxout_attribs_com[which(maxout_attribs_com == T)] <- Inf

    fit1 <- netest(nw2, formation = ~edges , constraints = ~bd(attribs = attribs_com, maxout = maxout_attribs_com), 
    target.stats = c(200), coef.diss = dissolution_coefs(dissolution = ~offset(edges) , duration = 25))
    
    param <- param.net(inf.prob = 0.3, act.rate = 1)
    init <- init.net(i.num = 5, r.num = 0)
    control <- control.net(type = "SI", nsteps = 50, nsims = 1, epi.by = "community", ncores=2)

    #works (gives 100% homophily by community)  
    dx <- netdx(fit1, nsims = 2, nsteps = 100, nwstats.formula = ~edges + nodematch("com2"), ncores = 2)

    #also runs now without throwing error
    sim <- netsim(fit1, param, init, control)

Is the main associated issue speed or are there other things to be aware of? Alternatively, is it worth trying with the dev version of tergm?

**Comment by chad-klumb** [comment]
Yes, that's the idea (re. using `bd`).  It may work for small networks, but I don't think it would scale to the 9000 node, 900 level case.  (You're welcome to try, of course, but if you do, be sure to scrutinize the diagnostics.)

`dev` is currently "private" and while I am not opposed to using it here I also cannot unilaterally authorize its (limited) release for this purpose.

**Comment by ThomasKraft** [comment]
Thank you for the info. FYI I did test the `bd` solution with larger networks, including my empirical case, and indeed it fails hard in those situations despite working in the smaller test.

**Comment by martinamorris** [comment]
Would it be possible to use a `nodemix` term instead with offsets = c(Inf, -Inf, -Inf, Inf) and no constraints?

**Comment by ThomasKraft** [comment]
I know you said to scratch that idea, but is this what you had in mind?

    com_at <- matrix(-Inf, nrow=9, ncol=9)
    com_at[lower.tri(com_at)] <- NA
    diag(com_at) <- 200/9
    coef_vec <- as.vector(na.omit(as.vector(com_at)))
    fit1 <- netest(nw2, formation = ~edges + offset(nodemix("com2")), coef.form = coef_vec, target.stats = c(200), 
    coef.diss= dissolution_coefs(dissolution = ~offset(edges) , duration = 25))

That does seem to work for smaller networks, but exhausts the memory limit for slightly bigger cases.

Would a possible alternative be to set up a structural zero matrix as an edgecov term and use offset to set the coefficients?  I couldn't get this to run because netest won't recognize the edge term (I don't find any examples of using edge terms with netest):

    nw2 <- as.network(matrix(1, nrow=90, ncol=90))
    nw2 %v% "com2" <- c(rep(as.character(c(1:9)), each=10 ))

    #structural zero matrix
    attribs_com <- sapply(as.character(rep(c(1:9), 10)), FUN= function(x) coms == x)
    struct_zeros <- attribs_com*1
    network::set.edge.value(nw2, "struct_zeros", struct_zeros)
    fit1 <- netest(nw2, formation = ~edges + offset(edgecov("struct_zeros")), coef.form = rep(1, 45), target.stats = c(200), 
    coef.diss = dissolution_coefs(dissolution = ~offset(edges) , duration = 25))

**Comment by martinamorris** [comment]
Pavel also got the larger model to fit (after 62 iterations).  Info here: https://github.com/statnet/ergm/issues/156#issuecomment-664818697

**Comment by chad-klumb** [comment]
As far as dynamic simulation goes, this may be the best I can come up with using `master`.  The entire script takes ~ 2 hours but `netdx` results look reasonable.

```
require(EpiModel)

nw2 <- network.initialize(n = 9000, directed = F)
nw2 %v% "com2" <- c(rep(as.character(c(1:900)), each = 10))

fit2 <- netest(nw2, formation = ~edges + offset(absdiff(~as.integer(com2))), 
               coef.form = c(-Inf),
               target.stats = c(20000), 
               coef.diss = dissolution_coefs(dissolution = ~offset(edges), 
                                             duration = 25),
               set.control.ergm = control.ergm(init.MPLE.samplesize = 1e8,
                                               MCMC.burnin = 3e6, 
                                               MCMC.interval = 3e5, 
                                               SAN.control = control.san(SAN.nsteps = 1e8)))

dx2 <- netdx(fit2, nsims = 1, nsteps = 50, nwstats.formula = ~edges + nodematch("com2"), set.control.stergm=control.simulate.network(MCMC.burnin.min=2e7, MCMC.burnin.max=2e7))
plot(dx2)

param <- param.net(inf.prob = 0.3, act.rate = 1)
init <- init.net(i.num = 5, r.num = 0)
control <- control.net(type = "SI", nsteps = 50, nsims = 1, epi.by = "community", set.control.stergm=control.simulate.network(MCMC.burnin.min=2e7, MCMC.burnin.max=2e7))

sim <- netsim(fit2, param, init, control)
```

**Comment by ThomasKraft** [comment]
@chad-klumb could you please verify that the code in your previous reply is correct? Using the exact same code and running on a fast cluster, it took ~10 hours for the model to converge (iteration 124) and the netdx results are not close (-83% diff). As seen in the attached graph, the edges statistic starts around the target but then rapidly decreases. The differences don't seemed to be explained by the circumstances in this previous post (http://mailman11.u.washington.edu/mailman/htdig/epimodel/2015-December/000047.html).

The reason I suspect this could have been a pasting issue with your code is that you use the arguments "init.MPLE.samplesize" (I think this should be "MPLE.samplesize") and you did not include a "MCMLE.maxit" argument (in a 2 hour run I'm guessing you exceeded 20 iterations).

My relevant sessionInfo is the following:
[1] EpiModel_1.8.0        tergm_3.6.1           ergm_3.10.4           networkDynamic_0.10.1 network_1.16.0


![tergm_dx_plot](https://user-images.githubusercontent.com/9221007/89106966-233dfc80-d3f3-11ea-84a9-731fa01d548f.png)

**Comment by chad-klumb** [comment]
Those are not `master` package versions.

This is the install stack I'm using, with `R 4.0.x`:

```
remotes::install_github(c("statnet/rle@master", 
                          "statnet/statnet.common@master", 
                          "statnet/network@master", 
                          "statnet/networkDynamic@master", 
                          "statnet/ergm@master", 
                          "statnet/tergm@master", 
                          "statnet/tergmLite@master", 
                          "statnet/EpiModel@master"), force=TRUE, dependencies=FALSE)
```

The script I posted previously runs on a single core in ~ 1 to 2 hours (depending on the core), with < 5% of that time being spent on estimation (which typically completes in 2 iterations).

These are the `netdx` results; the min, mean, and max are all within 1.25% of the target.

![netdx](https://user-images.githubusercontent.com/10733914/89109929-723b6000-d3fa-11ea-9095-ada1a8e385fb.jpeg)

**Comment by ThomasKraft** [comment]
Yes indeed, I forgot that the cluster was not using the same version as my local machine. My apologies. Thank you for the help and workaround!

I will note that there is still a time dependent decrease in the edges terms when using a shorter (3) dissolution duration, but I believe that is an issue associated with the constraint and available tie partners.

**Comment by chad-klumb** [comment]
Shorter duration with the same edges target stat would require changing more dyads each time step, which would require (further) increasing the MCMC run length parameters, specifically `MCMC.burnin.min/max` for dynamic simulation.
