### ISSUE TITLE
short dissolution duration causes poor diagnostics

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#438]
Reducing the duration term of the following example causes edges diagnostic to indicate issues for a simple model:

    # poor diagnostics
    toy <- network_initialize(n=100)
    fit_test <- netest(toy, 
                 formation = ~edges , 
                 target.stats = c(100), 
                 coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 3) 
                 )
    dx <- netdx(fit_test, nsims = 2, nsteps = 50)
    plot(dx)

Changing duration to 25 eliminates the problem. Based on a previous suggestion from @chad-klumb I tried increasing the MCMC.burnin and MCMC.burnin.min parameters in `control.ergm` but this did not resolve the issue.

**Comment by smjenness** [comment]
@ThomasKraft : this is an issue with the default "edges dissolution approximation" to fitting a temporal ergm. see the help doc for netest, and the accompanying paper by Carnegie et al. The solution is to fit a full stergm with `edapprox = TRUE`.
