### ISSUE TITLE
control legend in plot.netdx

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#440]
The help file for `plot.netdx` lists a "legend" argument for which "If TRUE, plot default legend." However, changing this parameter (to FALSE, NA, or NULL) does not remove the legend. It also does not appear to be possible to modify the default legend position with normal syntax. If there is an existing way to do this, some clarification in the help file might be warranted.

Adding a new custom legend currently works as expected.

Example:
```     
toy <- network_initialize(n=100)
toy <- set_vertex_attribute(toy, "gender", sample(c("M", "F"), network.size(toy), replace=T))
fit_test <- netest(toy, 
             formation = ~edges + nodematch("gender"), 
             target.stats = c(100, 50), 
             coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20) 
             )
dx <- netdx(fit_test, nsims = 2, nsteps = 50)
plot(dx, legend=FALSE)
```

**Comment by smjenness** [comment]
@ThomasKraft: thanks for the report. This was a bug that is now fixed on `master`.
