### ISSUE TITLE
EpiModel 2.0 migration: what happened to get_prev.net?

### ISSUE THREAD

**Issue by lc5415** [statnet/EpiModel#441]
Hello I had a custom module for `get_prev.net` and I cannot see a reference to that function in the new documentation, has it changed to `prevalence.net`?

**Comment by smjenness** [comment]
Yes, the name of the module is now `prevalence.FUN` in the `control.net` parameters.

**Comment by smjenness** [comment]
@andsv2 : please make sure our migration doc references this change.

**Comment by lc5415** [comment]
Ok! thanks for the quick reply!
