### ISSUE TITLE
Error in control.net instantiation when migrating to EpiModel 2.0

### ISSUE THREAD

**Issue by lc5415** [statnet/EpiModel#442]
I have built a series of custom modules and I am now getting the following error, which is hard to debug as it does not point anywhere specifically in the code:
```R
Error in p$f.args[index[i]] <- as.character(user.args[[user.indx[i]]]) : 
  replacement has length zero
```

This happens when I run:

```R
  control = EpiModel::control.net(
    nsims = nsims, 
    nsteps = nsteps,
    # delete.nodes = T,  this does not work for now
    ncores = cores,
    initialize.FUN = custom.initialize.net, 
    exposure.FUN = exposure,
    infect.FUN = infect,
    epi.by = "age",
    quarantine.FUN = quarantining,
    hospitalize.FUN = RequireHospitalization,
    recover.FUN = recover,
    fatality.FUN = fatality,
    recovery.FUN = NULL,
    infection.FUN = NULL,
    departures.FUN = EpiModel::departures.net,
    prevalence.FUN = custom.get_prev.net, ## changed from get_prev.FUN
    skip_check = FALSE,
    resimulate.network = T ## changed from depend = T
  )
```

Could anyone point at where this error is coming from, the `.traceback()` does not trace anywhere else that the `EpiModel::control.net` function call

**Comment by smjenness** [comment]
@lc5415 : we will investigate this. For now, please considering using the set of package versions you started out your project with. I highly recommend using `renv` for this purpose.

**Comment by andsv2** [comment]
@lc5415 can you remove: 
```
    recovery.FUN = NULL,
    infection.FUN = NULL,
``` 

from your control settings and let me know what happens.

**Comment by lc5415** [comment]
@andsv2 thanks for the quick reply, now I get a Warning instead of an Error:
```R
Warning message:
In p$f.args[index[i]] <- as.character(user.args[[user.indx[i]]]) :
  number of items to replace is not a multiple of replacement length
```

But then my code fails when I run `netsim()`, here's the traceback:
```R
 Error in EpiModel::get_control(dat, "type") : 
  There is no control value called type in the control list of the Master list object (dat) 
10.
stop(paste("There is no control value called", item, "in the control list of the Master list object (dat)")) 
9.
EpiModel::get_control(dat, "type") at SEIQHRFNetModules.R#1353
8.
(function (dat, at) 
{
    active <- EpiModel::get_attr(dat, "active")
    type <- EpiModel::get_control(dat, "type") ... 
7.
do.call(control[["prevalence.FUN"]], list(dat, at = 1)) at SEIQHRFNetModules.R#982
6.
(function (x, param, init, control, s) 
{
    if (control$start == 1) {
        dat <- list() ... 
5.
do.call(control[["initialize.FUN"]], list(x, param, init, control, 
    s)) 
4.
netsim_loop(x, param, init, control, s) 
3.
FUN(X[[i]], ...) 
2.
lapply(seq_len(control$nsims), function(s) {
    netsim_loop(x, param, init, control, s)
}) 
1.
netsim(est, param, init, control) 
```

`SEIQHRFNetModules.R` is a custom set of modules I made, which are all based in how you write the base modules in the source code

I also have a `custom.netsim()` function which outputs a slightly different traceback:

```R
 Error in EpiModel::get_control(dat, "type") : 
  There is no control value called type in the control list of the Master list object (dat) 
7.
stop(paste("There is no control value called", item, "in the control list of the Master list object (dat)")) 
6.
EpiModel::get_control(dat, "type") at SEIQHRFNetModules.R#1353
5.
(function (dat, at) 
{
    active <- EpiModel::get_attr(dat, "active")
    type <- EpiModel::get_control(dat, "type") ... 
4.
do.call(control[["prevalence.FUN"]], list(dat, at = 1)) at SEIQHRFNetModules.R#982
3.
(function (x, param, init, control, s) 
{
    if (control$start == 1) {
        dat <- list() ... 
2.
do.call(control[["initialize.FUN"]], list(x, param, init, control, 
    s)) at SEIQHRFNetModules.R#612
1.
custom.netsim(est, param, init, control) 
```

**Comment by andsv2** [comment]
@lc5415 apologies for not catching this in your previous code: in the section "Epidemic Type Specification" of the migration document we have detailed the changes that have been made in regards to specifying epidemic type with EpiModel. Because you are using non-standard modules, you must specify  `type = NULL` in your control settings. 

Please let me know if this handles the above.

**Comment by lc5415** [comment]
Thanks @andsv2 , adding `type = NULL` is fixing some of the behaviour but I am still getting the warning when I run the `control.net` command:
```R
Warning message:
In p$f.args[index[i]] <- as.character(user.args[[user.indx[i]]]) :
  number of items to replace is not a multiple of replacement length
```

Also, I'm calling `EpiModel::departures.net` as I am package that wraps EpiModel functions. I am getting some more errors which I on't post here yet as I believe they are errors to do with my code rather than yours. I guess my situation is perhaps rare as I had some code-base that slighlt changed `netsim` and other core functions of EpiModel, so that know that the code has been refactored I need to change all the code! Hopefully I'll be done soon! Thanks for the support!

**Comment by andsv2** [comment]
@lc5415 the warning is from `control.net` trying to parse `EpiModel::departures.net`; `departures.net` works, but I will investigate why `EpiModel::departures.net` does not.

Also, slightly related to the above, if you could give some feedback on the EpiModel migration document itself, that would be really useful; if you have the time of course. You can send that feedback to shawnee.marcel.anderson@emory.edu.

**Comment by jtm6** [comment]
Greetings:

I believe I have a similar or related issue in control.net at the bottom of fxn, line 128

Browse[2]> as.character(user.args[[user.indx[i]]])

Error in as.character(user.args[[user.indx[i]]]) : 
  cannot coerce type 'closure' to vector of type 'character'

The error is returned for each element in user.args[user.indx].  Each element is indeed a closure/fxn. To control.net(), I add a bunch of user-specific functions, e.g., transmission.FUN=function(dat,at){...} (actually, transmission.FUN=transmission_function). This setup was working in EpiModel_1.8.

thanks,
James

**Comment by smjenness** [comment]
@jtm6 Can you include your `control.net` call so I can try to reproduce?

@lc5415 : I am trying to reproduce the error with this. When I do this and remove the `recovery.FUN = NULL` and `infection.FUN = NULL` inputs, there is no error or warning. Could you verify?

```r
f <- function(x) x
control = EpiModel::control.net(
  nsims = 10, 
  nsteps = 10,
  # delete.nodes = T,  this does not work for now
  ncores = 1,
  initialize.FUN = f, 
  exposure.FUN = f,
  infect.FUN = f,
  epi.by = "age",
  quarantine.FUN = f,
  hospitalize.FUN = f,
  recover.FUN = f,
  fatality.FUN = f,
  recovery.FUN = NULL,
  infection.FUN = NULL,
  departures.FUN = f,
  prevalence.FUN = f, ## changed from get_prev.FUN
  skip_check = FALSE,
  resimulate.network = T ## changed from depend = T
)
```

It looks like when

**Comment by jtm6** [comment]
Sorry for delayed response. EpiModel messages go into folder, I was checking  only sporadically.
Apologies in advance if this example is unclear.

#######################################
#user-specified fxns
f1=function(dat,at){return(dat)}
f2=function(dat,at){return(dat)}
###################################

# a few different examples, all differ just by "module_order" arg, where I got it in my head
#that may be the issue

#same error returned for each example:
#Error in p$f.args[index[i]] <- as.character(user.args[[user.indx[i]]]) : 
#  replacement has length zero


# module.order  = c("resim_nets.FUN","f1.FUN","f2.FUN","nwupdate.FUN"),
control.net(type=NULL,
            nsteps=300,
            start = 1,
            nsims =  1,
            ncores =  1,
            resimulate.network = TRUE,
            tergmLite = TRUE,
            save.nwstats = TRUE,
            nwstats.formula = "formation",
            verbose = TRUE,
            verbose.int = 1e6,
            skip.check = TRUE,
            raw.output = FALSE,
            module.order  = c("resim_nets.FUN","f1.FUN","f2.FUN","nwupdate.FUN"),
            save.other    = c("attr"),
            f1.FUN=f1,
            f2.FUN=f2,
            initialize.FUN = initialize.net,
            resim_nets.FUN = resim_nets,
            infection.FUN = NULL,
            recovery.FUN = NULL,
            departures.FUN = NULL,
            arrivals.FUN = NULL,
            nwupdate.FUN = nwupdate.net,
            prevalence.FUN = NULL,
            verbose.FUN = verbose.net)     
  


#module.order  = c("initialize.FUN","resim_nets.FUN","f1.FUN","f2.FUN","nwupdate.FUN","verbose.FUN"),
control.net(type=NULL,
            nsteps=300,
            start = 1,
            nsims =  1,
            ncores =  1,
            resimulate.network = TRUE,
            tergmLite = TRUE,
            save.nwstats = TRUE,
            nwstats.formula = "formation",
            verbose = TRUE,
            verbose.int = 1e6,
            skip.check = TRUE,
            raw.output = FALSE,
            module.order  = c("initialize.FUN","resim_nets.FUN","f1.FUN","f2.FUN","nwupdate.FUN","verbose.FUN"),
            save.other    = c("attr"),
            f1.FUN=f1,
            f2.FUN=f2,
            initialize.FUN = initialize.net,
            resim_nets.FUN = resim_nets,
            infection.FUN = NULL,
            recovery.FUN = NULL,
            departures.FUN = NULL,
            arrivals.FUN = NULL,
            nwupdate.FUN = nwupdate.net,
            prevalence.FUN = NULL,
            verbose.FUN = verbose.net)     


# module.order  = c("f1.FUN","f2.FUN"),
control.net(type=NULL,
            nsteps=300,
            start = 1,
            nsims =  1,
            ncores =  1,
            resimulate.network = TRUE,
            tergmLite = TRUE,
            save.nwstats = TRUE,
            nwstats.formula = "formation",
            verbose = TRUE,
            verbose.int = 1e6,
            skip.check = TRUE,
            raw.output = FALSE,
            module.order  = c("f1.FUN","f2.FUN"),
            save.other    = c("attr"),
            f1.FUN=f1,
            f2.FUN=f2,
            initialize.FUN = initialize.net,
            resim_nets.FUN = resim_nets,
            infection.FUN = NULL,
            recovery.FUN = NULL,
            departures.FUN = NULL,
            arrivals.FUN = NULL,
            nwupdate.FUN = nwupdate.net,
            prevalence.FUN = NULL,
            verbose.FUN = verbose.net)     

#no "module_order arg"
control.net(type=NULL,
            nsteps=300,
            start = 1,
            nsims =  1,
            ncores =  1,
            resimulate.network = TRUE,
            tergmLite = TRUE,
            save.nwstats = TRUE,
            nwstats.formula = "formation",
            verbose = TRUE,
            verbose.int = 1e6,
            skip.check = TRUE,
            raw.output = FALSE,
            #module.order  = c("f2.FUN","f1.FUN"), #no module_orger argument
            save.other    = c("attr"),
            f1.FUN=f1,
            f2.FUN=f2,
            initialize.FUN = initialize.net,
            resim_nets.FUN = resim_nets,
            infection.FUN = NULL,
            recovery.FUN = NULL,
            departures.FUN = NULL,
            arrivals.FUN = NULL,
            nwupdate.FUN = nwupdate.net,
            prevalence.FUN = NULL,
            verbose.FUN = verbose.net)

**Comment by lc5415** [comment]
I thought the module order was the order in which the modules were laid out, is that feature gone? i.e. is then always necessary to explicitly state `module.order`?

**Comment by lc5415** [comment]
Would this be the right syntax?

```R
  control = EpiModel::control.net(
    type = NULL,
    nsims = nsims, 
    nsteps = nsteps,
    # delete.nodes = T,  this does not work for now
    ncores = cores,
    initialize.FUN = custom.initialize.net, # this bit is just so that I can extract time
    exposure.FUN = exposure,
    infect.FUN = infect,
    epi.by = "age",
    quarantine.FUN = quarantining,
    hospitalize.FUN = RequireHospitalization,
    recover.FUN = recover,
    fatality.FUN = fatality,
    departures.FUN = EpiModel::departures.net,
    prevalence.FUN = custom.get_prev.net,
    skip_check = FALSE,
    resimulate.network = T,
    module.order = c('initialize.FUN', 'exposure.FUN', 'infect.FUN',
                     'quarantine.FUN', 'hospitalize.FUN', 'recover.FUN',
                     'fatality.FUN', 'departures.FUN', 'prevalence.FUN')
  )
 ```

**Comment by lc5415** [comment]
I am a bit confused at module order, I've read the code for the `netsim_loop()` function, should I only pass module which take `dat` and `at` as arguments? As suggested by:
```R
      for (i in seq_along(morder)) {
        dat <- do.call(control[[morder[i]]], list(dat, at))
      }
```

in the `netsim_loop` source code.

**Comment by lc5415** [comment]
My issue is solved so I will close this for now but feel free to open again if it reminds you of bugs to investigate @smjenness @andsv2
