### ISSUE TITLE
departures.net cannot handle type = NULL for custom modules

### ISSUE THREAD

**Issue by lucharo** [statnet/EpiModel#445]
I am using some custom modules and some base modules. Given that now `type = NULL` must be specified when calling non-base models I've got the following error:

```R
Error in if (type == "SIR") { : argument is of length zero  
```
Which comes from the `EpiModel::departures.net` function. This occurs because if `type` is NULL, `NULL == 'SIR'` evaluates to logical(0), which cannot be handle. I think you need to call `isnull()` and then handle non standard models appropriately.

My current `control.net` call is as follows:
```R
  control = EpiModel::control.net(
    type = NULL,
    nsims = nsims, 
    nsteps = nsteps,
    # delete.nodes = T,  this does not work for now
    ncores = cores,
    initialize.FUN = custom.initialize.net, # this bit is just so that I can extract time
    exposure.FUN = exposure,
    infect.FUN = infect,
    epi.by = "age",
    quarantine.FUN = quarantining,
    hospitalize.FUN = RequireHospitalization,
    recover.FUN = recover,
    fatality.FUN = fatality,
    departures.FUN = EpiModel::departures.net,
    prevalence.FUN = custom.get_prev.net,
    skip_check = FALSE,
    resimulate.network = T,
    module.order = c('exposure.FUN', 'infect.FUN',
                     'quarantine.FUN', 'hospitalize.FUN', 'recover.FUN',
                     'fatality.FUN', 'departures.FUN', 'prevalence.FUN')
  )
```

All the functions in module.order have `(dat, at)` as params. I'll fork the repo and submit a PR which could satisfy you. Which things need to be handle if `type = NULL` that would be different from `type %in% c('SIR', 'SI')`?

**Comment by lc5415** [comment]
Do you perhaps not want people to use custom modules and base modules at the same time?

**Comment by smjenness** [comment]
@lc5415 : I think the short-term solution is to modify your departures module to remove references to `type`. 

@andsv2 : we need to have the built-in flexible modules not reference type, because if these will be used in any extension, they will error. In this particular case, this could be done by looking up whether `dr.rate` is NULL instead of `type`. https://github.com/statnet/EpiModel/blob/master/R/net.mod.vital.R#L28-L30

**Comment by andsv2** [comment]
Note: check all functions for references to `type == NULL` for built in modules to make sure they work for base and extension users.

**Comment by andsv2** [comment]
@smjenness currently R CMD Check is failing due to `test-net-long.R`. In one of the tests, status is passed through to the network, so the solution implemented above leads to an error in the scenario below:
```
## "SIR, 1M, CL: 2 sim, set status.vector"
  param <- param.net(inf.prob = 0.5, rec.rate = 0.1)
  init <- init.net(status.vector = rep(c("s", "i"), each = 50))
  control <- control.net(type = "SIR", nsims = 2, nsteps = 25,
                         verbose = FALSE)
```

**Comment by AdrienLeGuillou** [comment]
@smjenness 

> @lc5415 : I think the short-term solution is to modify your departures module to remove references to `type`.

I agree with this. I made a simple PR to implement this. #571 and open a discussion #572 on what to do more generaly
