### ISSUE TITLE
Can't get any population dynamics to work--a.rate, di.rate, and ds.rate are not functioning

### ISSUE THREAD

**Issue by ashleyhazel** [statnet/EpiModel#447]
In trying to migrate my SEIR models from EpiModel 1.x to 2.0, I ran the code for creating the arrivals.net and departures.net functions and specified them in the control.net function but they are not being incorporated into the model. Population size is totally static. Infection dynamics seem to be working normally but the population size at t=0 (N=118) never changes and when I print out the model output, I can see that the population size is static and that there are no variables for a.rate, di.rate, or ds.rate. Also, if I don't specify these module extensions, the model population is totally static. Is anyone else having this problem? I am not a great coder, so I don't know if there was something I needed to change in the module code to tailor it for my script but I didn't have to do that for the previous (1.x version) SEIR extension code.

A particular aspect of my model is that I am not initializing a theoretical network (so I am not using the initialization function). I am calling in a 'netest' class that was built from an actual network and a formation model and target stats determined from a best-fit ERGM.

Here's my script:
source("/Users.../SEIRModuleExtension.R") #I took this directly from the EpiModel 2.0 introduction page at statnet.org
source("/Users.../ArrivalsAndDepartures.R") #I took this directly from the github code

param <-param.net(inf.prob=0.0004, act.rate=40, ei.rate=0.0074, ir.rate=0.0064, a.rate=0.00058,
                   ds.rate=0.00253, di.rate=0.0123)

init <-init.net(s.num=116, e.num=0, i.num=2, r.num=0) 

control <-control.net(type=NULL, nsteps=520, nsims=2, arrivals.FUN=arrivals.net, departures.FUN=departures.net, infection.FUN=infect2, progress.FUN = progress)

ambala_2 <-netsim(netest.ambala, param, init, control)

**Comment by lc5415** [comment]
Could you provide the code that you are mentioning:
```R
source("/Users.../SEIRModuleExtension.R") #I took this directly from the EpiModel 2.0 introduction page at statnet.org
source("/Users.../ArrivalsAndDepartures.R") #I took this directly from the github code
```
as well as perhaps the code to either obtain `netest.ambala` for reporducibility, otherwise it is really hard to debug your problem.

__My main guess would be that your arrival and departure are very low: about 6 arrivals for every 10000 steps and 2 departures every 1000 steps, hence in 512 steps it is theoretically possible that you won't be seeing any change in population size over 118 individuals.__

**Comment by ashleyhazel** [comment]
Thank you very much for your response!

I do not think the problem is the arrivals departures because I've tried giving them huge values and nothing changes. Also, I was using these values before the EpiModel updates and they gave me the expected population dynamics (all our parameters are adjusted to weekly rates).

I'm linking to a github repository with three scripts—the model code including the netest and the two extension modules, which should be identical to the code posted on github by the EpiModel team (although I commented out the code for the example model in the SEIRModuleExtension script and the code for bipartite models in the ArrivalsAndExtension script)—and the ambala_net network object so you can run the netest.

https://github.com/ashleyhazel/Madagascar-script

I made you a collaborator on the repository linked above.

I'm sorry if this is not the clearest way to share my code with you. I've barely used github and I still really don't know how to navigate it.

**Comment by andsv2** [comment]
@ashleyhazel  we would need to see the code to properly debug this; your repo is currently set to private however.

**Comment by ashleyhazel** [comment]
Oops, sorry. I've just made it public. Thank you.

**Comment by andsv2** [comment]
Afternoon @ashleyhazel; a couple of things:

* Since you are extending the functionality of EpiModel, care needs to be taken on the functions that are supplied for your workflow. In the case of `departures.net`, this is the built in version of the departures module that may not work for a user extending EpiModel: in your case, since `type = NULL`, the logic check in `departures.net` will fail. Removing this logic check and running the code within solves this issue (based on your current repo).
* In line with the above, no departure rate for recovered individuals is provided. 

Fixing the above this is what I get for `num` (the total population size) after running the simulation 10 times:

![num](https://user-images.githubusercontent.com/42519638/90052079-9e7e9880-dca6-11ea-8c6d-72386a44a324.jpeg)

Let me know if this makes sense/fixes your issue.

**Comment by ashleyhazel** [comment]
Hi, thank you for your time! I think what you are saying is that I should drop the extension code for arrivals and departures and remove the call for those functions from the control.net function. Is that right?

If so, this doesn't solve my problem. I'm still getting no population dynamics. Can you show me what changes you made to my code so that I understand?

**Comment by andsv2** [comment]
@ashleyhazel no there is no need to remove the extension modules, just update them to work with your code (I would also rename them to something like arrivals2 or departures2). As for code changes there were only two:

* Adding a departure rate to the list of parameters
```
param <-param.net(inf.prob=0.0004, act.rate=40, ei.rate=0.0074, ir.rate=0.0064, a.rate=0.00058,
                                 ds.rate=0.00253, di.rate=0.0123, dr.rate = 0.00253)
```

* Removing logic checks `type == SIR` from `departures.net`. For example:
```
 if (type == "SIR") {
    rates.rec <- get_param(dat, "dr.rate")
  }
```

should only be

```
rates.rec <- get_param(dat, "dr.rate")
```

Similar updates throughout your code. Making those changes produced the desired results. If you're still having issues can you do: 

```
sessioninfo::package_info(pkgs = c("network", "networkDynamic", "statnet.common",
+                                    "ergm", "tergm", "tergmLite", "EpiModel"), dependencies = FALSE)
```

and paste the results here. Thanks.

**Comment by ashleyhazel** [comment]
Yes, that worked! Thank you. This helped me understand the code much better. I appreciate your help and time.

**Comment by andsv2** [comment]
@ashleyhazel in speaking with @smjenness, the behavior I described for using `departures.FUN` and any base modules was erroneous: these should still work out of the box if you are using them in developing your own modules and should require no modification on your part. This will be updated shortly.

**Comment by ashleyhazel** [comment]
Hi, @andsv2. Sorry for the delayed reply.

Oddly, the code only began to work after I made the changes you suggested, so I don't know why it wasn't working "out of the box." Nevertheless, I'm grateful for your help. I'll keep an eye out for the updates. Thanks!
