### ISSUE TITLE
Printing of Module Functions

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#449]
Should `print.netsim` only print out the module names themselves and not the actual functions assigned to them?

**Comment by AdrienLeGuillou** [comment]
As I said to @smjenness and @andsv2, I am of the opinion that just printing the name of the modules (`something.FUN`) if they are not `NULL` is the cleanest option. It reduces code complexity and printing the bound name of the functions only helps in corner cases you might get to if you already are pretty familiar with EpiModel tweaking.

**Comment by smjenness** [comment]
I agree at this point, given our conversation. @andsv2 : would you please implement that for the next release (we'll target end of September)?
