### ISSUE TITLE
When tergmLite = TRUE, option to save transmat

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#451]
With the update to EpiModel 2.0, saving of the transmission matrix (`transmat`) has been folded into the use of `tergmLite`: if `TRUE`, the transmission matrix is not saved at the end of the simulation; alternatively, when `FALSE` this is saved. This is all done automatically. Instead:

- [x] Saving of the transmission matrix should be independent of `tergmLite` usage.
- [x] Use `microbench` to test any reduction in speed.

**Comment by smjenness** [comment]
@andsv2 note to the right how to add a milestone -- it's not a label ;)
