### ISSUE TITLE
netdx function fails with edgecov attribute

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#455]
A model fit using `netest` works fine when using a matrix to define an edgecov term. However, diagnostics for this model cannot be assessed because `netdx` throws an error: "Error in { : task 1 failed - "object 's' not found"

It would thus appear that netdx is unable to access the info needed in the edgecov term matrix, 

MWE to reproduce the error:
```
library(EpiModel)
toy <- network_initialize(n=20, directed=F)

# create matrix for edgecov term
s <- matrix(sample(seq(0,.5, .1), 400, replace=T),20)
s[lower.tri(s)] = t(s)[lower.tri(s)]  # make the attribute matrix symmetric
diag(s) <- 0

fit_test <- netest(toy, 
                   formation = ~edges + edgecov(s) , 
                   target.stats = c(30, 10), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20), edapprox = T) 

# both of the following fail
dx <- netdx(fit_test, nsims = 2, nsteps = 50, nwstats.formula = ~edges + edgecov(s), ncores = 2)

dx <- netdx(fit_test, nsims = 2, nsteps = 50, ncores = 2)
```

**Comment by smjenness** [comment]
@ThomasKraft : similar to #456, I am unable to replicate this error. So a `sessionInfo()` would be helpful to start.

**Comment by smjenness** [comment]
@ThomasKraft : are you still having trouble with this edgecov term issue? I am not able to replicate. Thanks

**Comment by ThomasKraft** [comment]
I believe that this turns out to be a duplicate of #456 , most likely would be resolved by the same fix.
