### ISSUE TITLE
netsim failure when running on multiple cores with edgecov term

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#456]
This problem appears to be specific to using `netsim` for models that include an edgecov term, but only arises when instructed to use multiple cores (run in parallel). The same routine has no problems on a single core. When object `s` is the edgecov input matrix, the error message is:
"Error in { : task 1 failed - "object 's' not found"

Presumably this error is actually coming from `foreach` or `doParallel` routines, although the error message looks specifically similar to that reported for a separate but related issue using `netdx` (https://github.com/statnet/EpiModel/issues/455#issue-686542717). 

MWE:
```
library(EpiModel)
toy <- network_initialize(n=20, directed=F)

# create matrix for edgecov term
s <- matrix(sample(seq(0,.5, .1), 400, replace=T),20)
s[lower.tri(s)] = t(s)[lower.tri(s)]  # make the attribute matrix symmetric
diag(s) <- 0

fit_test <- netest(toy, 
                   formation = ~edges + edgecov(s) , 
                   target.stats = c(30, 10), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20), edapprox = T) 

param <- param.net(inf.prob = 0.3, act.rate = 1)
init <- init.net(i.num = 5, r.num = 0)

## WORKS
control <- control.net(type = "SI", nsteps = 50, nsims = 1, ncores=1)
sim <- netsim(fit_test, param, init, control)

## DOES NOT WORK
control <- control.net(type = "SI", nsteps = 50, nsims = 2, ncores=2)
sim <- netsim(fit_test, param, init, control)
```

**Comment by smjenness** [comment]
@ThomasKraft : I am not able to reproduce the error. I ran the multi-core scenario 100 times just to see if there was a stochastic trigger, but no errors there either. Could you provide your `sessionInfo()` and also try changing the name of the `s` object to something else (`s` is used to index the simulation number internally, so I wonder if there is a name collision there).

**Comment by ThomasKraft** [comment]
Here is my session info:

 sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ndtv_0.13.0              animation_2.6            EpiModel_2.0.3           tergmLite_2.2.1         
 [5] deSolve_1.28             statnet_2019.6           tsna_0.3.1               sna_2.5                 
 [9] statnet.common_4.4.0-273 ergm.count_3.4.0         tergm_3.7.0-1955         networkDynamic_0.10.2   
[13] ergm_3.11.0-5659         network_1.17.0-413       truncdist_1.0-2          evd_2.3-3               
[17] lubridate_1.7.9          forcats_0.5.0            stringr_1.4.0            dplyr_1.0.2             
[21] purrr_0.3.4              readr_1.3.1              tidyr_1.1.1              tibble_3.0.3            
[25] ggplot2_3.3.2            tidyverse_1.3.0          lme4_1.1-23              Matrix_1.2-18           

loaded via a namespace (and not attached):
 [1] nlme_3.1-148       fs_1.5.0           doParallel_1.0.15  RColorBrewer_1.1-2 httr_1.4.2         tools_4.0.2       
 [7] backports_1.1.7    R6_2.4.1           DBI_1.1.0          lazyeval_0.2.2     colorspace_1.4-1   withr_2.2.0       
[13] tidyselect_1.1.0   base64_2.0         compiler_4.0.2     cli_2.0.2          rvest_0.3.6        xml2_1.3.2        
[19] scales_1.1.1       DEoptimR_1.0-8     robustbase_0.93-6  askpass_1.1        minqa_1.2.4        pkgconfig_2.0.3   
[25] dbplyr_1.4.4       rlang_0.4.7        readxl_1.3.1       rstudioapi_0.11    generics_0.0.2     jsonlite_1.7.0    
[31] magrittr_1.5       Rcpp_1.0.5         munsell_0.5.0      fansi_0.4.1        ape_5.4-1          lifecycle_0.2.0   
[37] stringi_1.4.6      MASS_7.3-51.6      grid_4.0.2         blob_1.2.1         parallel_4.0.2     crayon_1.3.4      
[43] lattice_0.20-41    haven_2.3.1        splines_4.0.2      hms_0.5.3          pillar_1.4.6       boot_1.3-25       
[49] codetools_0.2-16   lpSolve_5.6.15     rle_0.9.1-223      reprex_0.3.0       glue_1.4.1         trust_0.1-8       
[55] modelr_0.1.8       vctrs_0.3.2        nloptr_1.2.2.2     foreach_1.5.0      cellranger_1.1.0   openssl_1.4.2     
[61] gtable_0.3.0       assertthat_0.2.1   xfun_0.16          broom_0.7.0        coda_0.19-3        iterators_1.0.12  
[67] tinytex_0.25       statmod_1.4.34     ellipsis_0.3.1

**Comment by andsv2** [comment]
@smjenness @ThomasKraft not to be a third wheel, but I was able to reproduce Thomas' error on my end (Windows environment).

**Comment by ThomasKraft** [comment]
Good idea about the conflict with `s`: I did try this also and it does not fix the error.

**Comment by smjenness** [comment]
Ok, so it is something Windows-specific. I am unable to debug further for that reason, so could you please help @andsv2?

**Comment by ThomasKraft** [comment]
In case this is related, here is a note from the following document (https://cran.r-project.org/web/packages/doParallel/vignettes/gettingstartedParallel.pdf) which states:

"To use multicore-like functionality, we would specify the number of cores to use instead (but
note that on Windows, attempting to use more than one core with parallel results in an error):"

**Comment by ThomasKraft** [comment]
I'm not sure if this is a viable workaround, but could this potentially be solved by modifying the following location:    https://github.com/statnet/EpiModel/blob/03ac578f40015e50ffd110b0ebb6e1fc76d3e0d0/R/netsim.R#L145:

You could first detect if a system is running windows and then:
```
cluster <- makeCluster(4)
    doParallel::registerDoParallel(cluster)
    sout <- foreach(s = 1:nsims) %dopar% {
```

**Comment by martinamorris** [comment]
I don't know if this is relevant, but I've been using parallel throughout my estimation/dx workflow on a windows laptop using the following:


```
np <- max(0, parallel::detectCores() - 4)
if (np==0) ptype=NULL else ptype='PSOCK' # for setting parallel.type

control_main <- control.ergm.ego(
  ppopsize = ppop, 
  ppop.wt = ppopwt,
  ergm.control = control.ergm(MCMC.interval = 1e5,
                              parallel = np,
                              parallel.type = ptype)
fit_main <- ergm.ego(model_main,
                     offset.coef = offset_main,
                     control = control_main,
                     verbose = T)
plot(gof(fit_main),
     control.gof.ergm(parallel = np, parallel.type = ptype))

staticdx <- netdx(netest_main, nsims = 50, dynamic = F, ncores = np)

dyndx <- netdx(netest_main, nsims = 5, dynamic = T, nsteps = 1000,
            set.control.ergm = control.simulate.ergm(MCMC.burnin = 1e5),
            set.control.stergm =  control.simulate.network(MCMC.burnin.min = 1e4),
              ncores = np)
```

**Comment by ThomasKraft** [comment]
Thanks for the suggestion Martina. Making changes like this doesn't seem to help, but I did notice that setting `dynamic = F` as you have done gets `netdx` to run. So I would be curious if your code runs for you if you set `dynamic = T` on your machine.

**Comment by martinamorris** [comment]
@ThomasKraft the last call (dyndx) does set dynamic=T, and it runs on my machine

**Comment by ThomasKraft** [comment]
Oops, yes OK that same line will run on my machine, but **only** if I removed the edgecov() term from the model first.

**Comment by smjenness** [comment]
@ThomasKraft : are you still having trouble with this edgecov term issue?

**Comment by ThomasKraft** [comment]
Yes unfortunately the issue persists, and does appear to be windows specific. Further tests do indicate that the error arises due to the combination of 1) multiple cores, 2) windows environment, and 3) inclusion of edgecov term.

**Comment by martinamorris** [comment]
Ok, this sounds like something it might be worth handing over to @chad-klumb to track down.  @ThomasKraft can you put together a minimal reprex -- I'm not sure given the thread whether the one up top isolates the issue you're having precisely.

**Comment by ThomasKraft** [comment]
@martinamorris I'm not exactly sure how much of a better example I can provide than the original one, but here is a slightly pared down version that demonstrates that the problem is caused by the combination of the `edgecov` term and the the use of multiple cores (and I can verify that this is only an issue on Windows).

```library(EpiModel)
toy <- network_initialize(n=20, directed=F)

# create matrix for edgecov term
emat <- matrix(runif(400, min = 0, max=.5), 20, 20)
emat <- emat %*% t(emat)

fit_test <- netest(toy, 
                   formation = ~edges + edgecov(emat) , 
                   target.stats = c(30, 30), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20), edapprox = T) 

param <- param.net(inf.prob = 0.3, act.rate = 1)
init <- init.net(i.num = 5, r.num = 0)

# 1) Test that parallel with multiple cores is causing the problem
## WORKS
control <- control.net(type = "SI", nsteps = 50, nsims = 1, ncores=1)
sim <- netsim(fit_test, param, init, control)

## DOES NOT WORK
control <- control.net(type = "SI", nsteps = 50, nsims = 2, ncores=2)
sim <- netsim(fit_test, param, init, control)


# 2) Test multiple cores WITHOUT the edgecov term
fit_test2 <- netest(toy, 
                   formation = ~edges , 
                   target.stats = c(30), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20), edapprox = T) 

## WORKS
control <- control.net(type = "SI", nsteps = 50, nsims = 1, ncores=1)
sim <- netsim(fit_test2, param, init, control)

## WORKS
control <- control.net(type = "SI", nsteps = 50, nsims = 2, ncores=2)
sim <- netsim(fit_test2, param, init, control)
```

**Comment by chad-klumb** [comment]
New warnings from `network@master` appear to have broken this further:

```
remotes::install_github(c("statnet/rle@master", 
                          "statnet/statnet.common@master", 
                          "statnet/network@master", 
                          "statnet/networkDynamic@master", 
                          "statnet/ergm@master", 
                          "statnet/tergm@master", 
                          "statnet/tergmLite@master", 
                          "statnet/EpiModel@master"), force=TRUE, dependencies=FALSE)

require(EpiModel)

toy <- network_initialize(n=20, directed=F)

# create matrix for edgecov term
emat <- matrix(runif(400, min = 0, max=.5), 20, 20)
emat <- emat %*% t(emat)

fit_test <- netest(toy, 
                   formation = ~edges + edgecov(emat) , 
                   target.stats = c(30, 30), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20), edapprox = T) 

param <- param.net(inf.prob = 0.3, act.rate = 1)
init <- init.net(i.num = 5, r.num = 0)

# 1) Test that parallel with multiple cores is causing the problem
## WORKS
control <- control.net(type = "SI", nsteps = 50, nsims = 1, ncores=1)
sim <- netsim(fit_test, param, init, control)
```

gives

```
> sim <- netsim(fit_test, param, init, control)

Starting Network Simulation...Error in netsim_cond_msg("ERROR", current_mod, at, e) : 
  object 'at' not found
```

while with `network@91b3c070421cdc6d69c3e2bc7d5aa5f1a75567c6` the above example does run.

**Comment by chad-klumb** [comment]
The multicore edgecov case is failing on my windows laptop with `network@91b3c070421cdc6d69c3e2bc7d5aa5f1a75567c6` and `master` versions of other packages, but the error message is different from that in the OP.

```
> ## DOES NOT WORK
> control <- control.net(type = "SI", nsteps = 50, nsims = 2, ncores=2)
> sim <- netsim(fit_test, param, init, control)
Error in { : task 1 failed - "object 'at' not found"
```

(Same error message for me regardless of whether the OP example or today's example is used.)

**Comment by chad-klumb** [comment]
The `at` error appears to be related to the introduction of the calling handlers in `netsim_loop`.

Beyond that, there appears to be an error when there are substitutions in the model formula, but not restricted to the `edgecov` term.

**Comment by martinamorris** [comment]
@chad-klumb so are these both errors in the EpiModel code base?  Or is the substitution error in the statnet codebase?

**Comment by chad-klumb** [comment]
It might be best characterized as a windows problem.

From https://www.r-bloggers.com/2019/06/parallel-r-socket-or-fork/:

In the R parallel package, there are two implementations of parallelism, e.g. fork and socket, with pros and cons.

For the fork, each parallel thread is a complete duplication of the master process with the shared environment, including objects or variables defined prior to the kickoff of parallel threads. Therefore, it runs fast. However, the major limitation is that the fork doesn’t work on the Windows system.

On the other hand, the socket works on all operating systems. Each thread runs separately without sharing objects or variables, which can only be passed from the master process explicitly. As a result, it runs slower due to the communication overhead.

-----

When we pass a formula to a child process on windows and try to evaluate a term argument that was specified by a variable name (like `s` in the original `edgecov` example), we get an error, because that variable doesn't exist as far as the child process is concerned.

I don't know of a really "good" way to fix this.  We could potentially allow the user to pass an environment to copy to the child processes if they want to do so, but I think we would want them to set the environment up themselves, rather than trying to do it for them.  In general, the same variable name can mean different things in different formulas (passed to the same child process), and it's not clear we can support that in this case (which the user needs to be aware of).

**Comment by martinamorris** [comment]
@chad-klumb am i right that `socket` is what i'm using on Rstudio server here?  if so, and that's what is used also on windows, here's how i got around that problem.  in my case, i needed to export my default library, which i had assigned the name `pkglib`.

```
cl <- makeCluster(np)
  clusterExport(cl, "pkglib")

  clusterEvalQ(cl, {
    .libPaths(c(pkglib, .libPaths()))
    library(ergm.ego)
    sessionInfo()
})
```
Would something like that work here?

**Comment by chad-klumb** [comment]
`clusterExport`ing the variables in the environment passed by the user (if we allow them to pass an environment to export) is basically what I was referring to when I said 

> We could potentially allow the user to pass an environment to copy to the child processes if they want to do so

However this is just a hack; in general it won't produce an identical evaluation environment to that in the master process.  Still, it might work in practice (if the user doesn't do anything "weird"), and atm I don't see a better option.

**Comment by ThomasKraft** [comment]
Does this mean that a similar error is not produced for nodefactor variables because they are stored internally to the fitted network model object?

If so, would it not be possible to explicitly define edge attributes within the network object (e.g. `toy %e% "s" <- s`) rather than storing them externally in the environment?

**Comment by smjenness** [comment]
> Does this mean that a similar error is not produced for nodefactor variables because they are stored internally to the fitted network model object?

@chad-klumb I was also wondering this too. We have never had reports of with parallel simulations from Windows users, but probably because users rarely/never implement edge covariate models.

**Comment by martinamorris** [comment]
> Does this mean that a similar error is not produced for nodefactor variables because they are stored internally to the
> fitted network model object?
> 
> If so, would it not be possible to explicitly define edge attributes within the network object (e.g. toy %e% "s" <- s)
> rather than storing them externally in the environment?

yes, that should work.

**Comment by ThomasKraft** [comment]
For what it's worth, ~1 month ago I tried implementing an edgecov like this (storing it as an edge attribute in the network object), and IIRC `netest` threw some kind of an error when I did so. Which may explain why @chad-klumb did not go this direction.

**Comment by martinamorris** [comment]
Can you try that again and if it fails send a reprex?  We might be able to track down the error, if there is one.

**Comment by chad-klumb** [comment]
The fundamental issue here can arise with any term that takes arguments, including `nodefactor`.  However, *typical* use may see some term arguments (such as vertex attribute names) *almost* always passed by value, such as

```
nodefactor("race")
```

This will not lead to an error because `"race"` is specified explicitly, by value, not by a variable name.

However, if we have defined

```
attr_name <- "race"
```

then 

```
nodefactor(attr_name)
```

is a perfectly legitimate `ergm` term, and will work on a single core, but not the windows parallel setup we're dealing with now.

-----

As far as the immediate problem with `edgecov` goes, you can work around it this way (the `network` warning thing appears to have been fixed, so it should be okay to use `network` `master` again):

```
remotes::install_github(c("statnet/rle@master", 
                          "statnet/statnet.common@master", 
                          "statnet/network@master", 
                          "statnet/networkDynamic@master", 
                          "statnet/ergm@master", 
                          "statnet/tergm@master", 
                          "statnet/tergmLite@master", 
                          "statnet/EpiModel@master"), force=TRUE, dependencies=FALSE)

require(EpiModel)
toy <- network_initialize(n=20, directed=F)

# create matrix for edgecov term
emat <- matrix(runif(400, min = 0, max=.5), 20, 20)
emat <- emat %*% t(emat)

toy %n% "emat" <- emat

fit_test <- netest(toy, 
                   formation = ~edges + edgecov("emat") , 
                   target.stats = c(30, 30), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 20), edapprox = T) 

param <- param.net(inf.prob = 0.3, act.rate = 1)
init <- init.net(i.num = 5, r.num = 0)

# 1) Test that parallel with multiple cores is causing the problem
## WORKS
control <- control.net(type = "SI", nsteps = 50, nsims = 1, ncores=1)
sim <- netsim(fit_test, param, init, control)

## now also works
control <- control.net(type = "SI", nsteps = 50, nsims = 2, ncores=2)
sim <- netsim(fit_test, param, init, control)
```

Note that `emat` is set as a network attribute, not an edge attribute.  The only reason this works is that the `edgecov` term has logic for handling a string first argument, which it tries to look up in the network attribute list here:

https://github.com/statnet/ergm/blob/c51f1c6c29bb540abce5c7d08e66d5f5087e77ce/R/InitErgmTerm.R#L1818-L1819

**Comment by chad-klumb** [comment]
In general there is no requirement for terms to offer the kind of functionality that `edgecov` does above; they are free to require a complex object as an argument, with no convenient alternative that is easily specified by value.

More generally, if something is at risk of breaking when going from one core to multiple cores (on a particular platform, in this case), then I think at a minimum we should inform the user about that.

**Comment by chad-klumb** [comment]
This is beside the main point of this issue, but it appears the `at` error may arise when an error is generated in the initialization function, since `at` is not defined until the time loop lower down:

https://github.com/statnet/EpiModel/blob/9e67e8046ac54f8cfaf290490a1e1011f1723e0c/R/netsim.R#L169-L214

This may result in the actual (original) error message being masked.

**Comment by smjenness** [comment]
I will have @AdrienLeGuillou take a look at that last issue, @chad-klumb

**Comment by martinamorris** [comment]
I'm guessing this calls for a vignette.  We've needed one for a while for the parallel functionality.  I'll put it on the list for 2021.

re: `clusterExport`

I was actually pretty happy when I found this utility -- it's functional, and easy to use, and while it doesn't clone the parent environment, I'm not sure what the limitations are on what you can export.  The main drawback seems to be that you need to specify everything explicitly.

**Comment by ThomasKraft** [comment]
@martinamorris A vignette addressing parallel functionality is something I looked for awhile ago and would have been tremendously useful. Two other potential topics that I haven't found any materials for: 1) edgecov terms and how to set their target statistics (topic of this thread), 2) changing the shape of the degree distribution, e.g. longer tailed vs more symmetric (something I still haven't figured out).

**Comment by AdrienLeGuillou** [comment]
@chad-klumb @smjenness  I see the issue, this PR correct it:

**Comment by smjenness** [comment]
@ThomasKraft : do you consider this issue closed now, with Martina's solution?
