### ISSUE TITLE
debugger with EpiModel not working for PC?

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#461]
I am alternately using 2 computers with EpiModel, one of which is mac and the other is pc. I am surprised to see that when running the same set of code on both computers using the same package versions, I only get the option to use the debugger on mac.

Is this expected? My apologies if there is an obvious explanation for this behavior!

Here is an EpiModel example which generates an error (bonus if you know what is triggering the cryptic error!):

```
toy <- network_initialize(n=100, directed=F)

fit_test <- netest(toy, 
                    formation = ~edges, 
                    target.stats = c(250), 
                    coef.diss = dissolution_coefs(dissolution = ~offset(edges),
                                                  duration = 5), edapprox = T)

param <- param.net(inf.prob = 0.05)
init <- init.net(i.num = 10)

aggregation_fx <- function(dat, at) {
  
  # aggregation parameters
  aggreg_prop <- .2
  aggreg_freq <- 7
    
  #every 7 days generate spike in ties
  if( (at %% aggreg_freq) == 0 ){
    
    aggreg_nodes <- which(sample(c(TRUE, FALSE), 
                                 network.size(dat$nw[[1]]), 
                                 replace=T, 
                                 prob=c(aggreg_prop,1-aggreg_prop) ))		
    
    existing.net <- as.sociomatrix(dat$nw[[1]])
    
    added.net <- existing.net
    added.net[which(rownames(existing.net) %in% aggreg_nodes), which(colnames(existing.net) %in% aggreg_nodes)] <- 1
    diag(added.net) <- 0
    
    difference.net <- added.net - existing.net
    
    difference.net <- upper.tri.remove(difference.net, remove.val = 0)
    
    el.add <- as.edgelist(as.network(difference.net))
    
    dat$nw[[1]] <- add.edges.active(dat$nw[[1]], head=el.add[,1],
                                              tail=el.add[,2],
                                              onset=at,
                                              terminus=at+1)
  }
  return(dat)
}

control <- control.net(tergmLite = F, type = NULL, nsteps = 100, nsims = 1, ncores = 1,
                       resimulate.network = TRUE, 
                       nwstats.formula = ~edges + 
                         meandeg,
                       aggregation_fx.FUN = aggregation_fx,
                       infection.FUN = infection.net,
                       nwupdate.FUN = nwupdate.net, 
                       prevalence.FUN = prevalence.net, verbose.FUN = verbose.net)
sim <- netsim(fit_test, param, init, control)
```

My session info on PC (not working): > sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ndtv_0.13.0              animation_2.6            statnet_2019.6           tsna_0.3.1              
 [5] sna_2.5                  statnet.common_4.4.0-273 ergm.count_3.4.0         truncdist_1.0-2         
 [9] evd_2.3-3                lubridate_1.7.9          lme4_1.1-23              Matrix_1.2-18           
[13] EpiModel_2.0.3           tergmLite_2.2.1          tergm_3.7.0-1955         ergm_3.11.0-5659        
[17] networkDynamic_0.10.2    network_1.17.0-413       deSolve_1.28             forcats_0.5.0           
[21] stringr_1.4.0            dplyr_1.0.2              purrr_0.3.4              readr_1.3.1             
[25] tidyr_1.1.1              tibble_3.0.3             ggplot2_3.3.2            tidyverse_1.3.0

**Comment by andsv2** [comment]
@ThomasKraft what are you trying to debug and what error are you getting?

**Comment by ThomasKraft** [comment]
I am trying to debug the working example that I pasted in the first message, specifically the module `aggregation_fx`. I am getting the error: "Error in if (!is.null(am) && am[nrow(am), 2] == times[1]) { : 
  missing value where TRUE/FALSE needed"

I have traced this back to the `networkDynamic.apply.changes` function from stergm, but no luck from there.

**Comment by smjenness** [comment]
@chad-klumb : any insights into this issue? I am less concerned about the debugging issue (which may be a problem with the user's Windows setup) than about the networkDynamic error. Thanks!

**Comment by chad-klumb** [comment]
I will look into this.

**Comment by chad-klumb** [comment]
The issue appears to arise from adding edges that start at time `at` and then *subsequently* simulating edges that start at the same time `at`.  You can address this by reordering the modules so `aggregation_fx` runs after `resim_nets` (and presumably before the infection module) on each time step.  Doing so eliminates the error for me.

**Comment by ThomasKraft** [comment]
Thank you, this works. It might be worth noting in the documentation that setting `resimulate.network = TRUE` will override your custom `module.order` call, even if it explicitly includes the resim_nets module.

**Comment by smjenness** [comment]
thanks @ThomasKraft : I'll open a separate issue to update the docs accordingly.
