### ISSUE TITLE
Set Functions

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#462]
The new set functions (`set_epi` for example) work at simulation start by adding structure to the `dat` object when none exists. This creates a problem with functionality in previous bespoke work (`EpiModelHIV` for example): 

```
dat$epi$ir100[at] <- (dat$epi$incid[at] / sum(status == 0 & race == 1, dat$epi$incid[at], na.rm = TRUE)) * 5200
```
works, as an example, because `ir100` does not exist at the moment and the right handside is creating the assignment (even if there is nothing there, which there isn't). However, this:

```
 dat <- set_epi(dat, "ir100", at, (get_epi(dat, "incid", at, override.null.error = TRUE) / 
                                   sum(status == 0, get_epi(dat, "incid", at, override.null.error = TRUE), 
                                   na.rm = TRUE)) * 5200
                        )
```

as the list `ir100` is created through the `set_epi` process on and then attempting to update with an value that has length of zero. 

My only thought of a solution is to add (another) override check for assignments that are of length zero noting

* this is a solution to a specific scenario (initialization of epi trackers)
* might allow people to make mistakes in coding/development if they aren't exactly aware of the behavior of R.

**Comment by smjenness** [comment]
@andsv2 : I don't follow this sentence: "the list ir100.B is created through the set_epi process on and then attempting to update with an value that has length of zero." There is no `ir100.B` in your example, or use of `set_epi` to create it.

**Comment by andsv2** [comment]
@smjenness updated. Meant `ir100`.

**Comment by smjenness** [comment]
Ok, what does this mean: "ir100 is created through the set_epi process on and then attempting to update..." Are there words missing here?

**Comment by smjenness** [comment]
`set_epi` should both initialize a value (if an epi does not exist) and update it (if it does)

```r
dat <- list(
  attr = list(
    active = rbinom(100, 1, 0.9)
  ),
  epi = list(),
  param = list(),
  init = list(),
  control = list(
    nsteps = 150
  )
)

dat <- set_epi(dat, "ir100", at = 2, 10)

dat$epi

dat <- set_epi(dat, "ir100", at = 3, 20)

dat$epi
```

**Comment by andsv2** [comment]
This is the behavior of `set_epi`, however it does not explicitly replicate the behavior of code from `EpiModel 1.x`: 

```
dat <- list(
  attr = list(
    active = rbinom(100, 1, 0.9)
  ),
  epi = list(),
  param = list(),
  init = list(),
  control = list(
    nsteps = 150
  )
)

dat <- set_epi(dat, "ir100", at = 2, numeric(0))
```
```
Error in dat[["epi"]][[item]][at] <- value : replacement has length zero
```

At the moment this is only an issue when running modules that look for values or statistics that haven't been created yet (i.e. initialization step 1 in EpiModelHIV) and is likely only an issue for `EpiModel` extensions.

**Comment by smjenness** [comment]
Any summary stats like these can be set in the relevant modules instead (e.g., this calculation could go in the HIV transmission module that directly counts `incid`, right)? I agree this is not necessarily a core Epimodel issue; if you agree, feel free to close the issue.

**Comment by andsv2** [comment]
@smjenness sounds good.
