### ISSUE TITLE
deactivate.edges not functioning within netsim module

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#463]
It should be possible to use `deactivate.edges` to remove certain edges from a dynamic network object as it is simulated with `netsim`. In the simplest case, however, this does not appear to work.

Consider the example below, which runs and reproduces the problem. In this case, a module is added that simply tries to get rid of all edges of active nodes using `deactivate.edges`. Oddly, however, this seems to have no effect (there are many ties still in the network).

Simple working example:
```
toy <- network_initialize(n=100, directed=F)

fit_test <- netest(toy, 
                   formation = ~edges, 
                   target.stats = c(250), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges),
                                                 duration = 5), edapprox = T)

param <- param.net(inf.prob = 0.05)
init <- init.net(i.num = 10)




remove_edge_fx <- function(dat, at) {
  
  active <- get_attr(dat, "active")
  
  del <- which(active == 1)
  e = NULL
  
  for (vert in del) {
    e = c(e, get.edgeIDs.active(dat$nw[[1]], v=vert, at=at, neighborhood="combined"))
  }
  if (length(e) > 0) {
    dat$nw[[1]] <- deactivate.edges(dat$nw[[1]], onset=at, terminus=Inf, e=unique(e))
  }
  
  return(dat)
}




control <- control.net(tergmLite = F, type = NULL, nsteps = 50, nsims = 1, ncores = 1,
                       resimulate.network = TRUE, 
                       nwstats.formula = ~edges + 
                       remove_edge_fx.FUN = remove_edge_fx,
                       infection.FUN = infection.net,
                       nwupdate.FUN = nwupdate.net, 
                       prevalence.FUN = prevalence.net, verbose.FUN = verbose.net)
sim <- netsim(fit_test, param, init, control)

print(sim$network$sim1[[1]])
```

**Comment by smjenness** [comment]
@chad-klumb : could you please take a look at this issue?

**Comment by chad-klumb** [comment]
Will do.

**Comment by chad-klumb** [comment]
The `networkDynamic` printed at the end has the full history of edges, not just the extant edges at the end of the simulation.

You can obtain the network state at a specific time point by (e.g.) using `network.collapse`:

```
require(EpiModel)

toy <- network_initialize(n=100, directed=F)

fit_test <- netest(toy, 
                   formation = ~edges, 
                   target.stats = c(250), 
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges),
                                                 duration = 5), edapprox = T)

param <- param.net(inf.prob = 0.05)
init <- init.net(i.num = 10)

remove_edge_fx <- function(dat, at) {
  
  active <- get_attr(dat, "active")
  
  del <- which(active == 1)
  e = NULL
  
  for (vert in del) {
    e = c(e, get.edgeIDs.active(dat$nw[[1]], v=vert, at=at, neighborhood="combined"))
  }
  if (length(e) > 0) {
    dat$nw[[1]] <- deactivate.edges(dat$nw[[1]], onset=at, terminus=Inf, e=unique(e))
  }
  
  return(dat)
}

control <- control.net(tergmLite = F, type = NULL, nsteps = 50, nsims = 1, ncores = 1,
                       resimulate.network = TRUE, 
                       nwstats.formula = ~edges,
                       remove_edge_fx.FUN = remove_edge_fx,
                       infection.FUN = infection.net,
                       nwupdate.FUN = nwupdate.net, 
                       prevalence.FUN = prevalence.net, verbose.FUN = verbose.net)

sim <- netsim(fit_test, param, init, control)

nwd <- sim$network$sim1[[1]]

print(nwd)

print(network.collapse(nwd, at=1))
print(network.collapse(nwd, at=2))
print(network.collapse(nwd, at=3))
print(network.collapse(nwd, at=4))
# ...
print(network.collapse(nwd, at=47))
print(network.collapse(nwd, at=48))
print(network.collapse(nwd, at=49))
print(network.collapse(nwd, at=50))
```

The `networkDynamic` prints with ~ 2500 edges, the full history of the simulation.

The `network` at time `1` prints with ~ 250-300 edges, and the remaining `network`s at times `2, ..., 50` print with an average of ~60some edges each.  This is consistent with initializing near the target stat, and then removing all edges in between each subsequent time step, understanding that the target duration of 5 is low enough to cause partial failure of the EDA.

I don't see a problem here.

**Comment by smjenness** [comment]
Thanks @chad-klumb. 

@ThomasKraft please let me know if you have any further questions. I would suggest you use the `get_network` function within EpiModel to extract the networkDynamic object. It includes arguments to collapse the network at a particular time step.

```r
help("get_network")
get_network(x, sim = 1, network = 1, collapse = FALSE, at)
```

**Comment by ThomasKraft** [comment]
Thank you both. This partially makes sense. If I'm understanding correctly, the remaining edges reported for the collapsed networks are the per step additions (~300/5 = 60), and these are reported because of the timing at which the network object is saved at each iteration.

But I still don't understand why transmission occurs at all in the example model from @chad-klumb. Given the module order, my expectation is that after resimulation of the network ALL edges would be deactivated prior to the infection function. So infection should be impossible from at=2 onwards, yet the prevalence increases as netsim runs. That seems problematic.

If you wanted to deactivate all edges so as to stop transmission, how would you modify the above functions?

**Comment by smjenness** [comment]
The default module order is to first run the built-in specified modules in the order they are listed in control.net (so network resimulation, then infection, ...) and then run any newly defined modules (like your remove edge module). So the edge removal would be happening after transmission within a time step. The module.order argument allows you to modify this default ordering. Can you try that out?

**Comment by ThomasKraft** [comment]
At first I thought this was working, but now I see that this only functions as expected if resim_nets.FUN is omitted from the module order. For example, the following shows no transmission:

```
control <- control.net(tergmLite = F, type = NULL, nsteps = 50, nsims = 1, ncores = 1,
                       resimulate.network = TRUE, 
                       nwstats.formula = ~edges,
                       remove_edge_fx.FUN = remove_edge_fx,
                       infection.FUN = infection.net,
                       nwupdate.FUN = nwupdate.net, 
                       prevalence.FUN = prevalence.net, verbose.FUN = verbose.net,
                       module.order = c("remove_edge_fx.FUN","infection.FUN","nwupdate.FUN", "prevalence.FUN"))
```

But if resim_nets.FUN is added to the module order (something I expected would happen automatically if `resimulate.network = T`), then transmission carries on. But it sounds like you also expect that this should not be the case with the removal module coming right before infection.

```
control <- control.net(tergmLite = F, type = NULL, nsteps = 50, nsims = 1, ncores = 1,
                       resimulate.network = TRUE, 
                       nwstats.formula = ~edges,
                       remove_edge_fx.FUN = remove_edge_fx,
                       infection.FUN = infection.net,
                       nwupdate.FUN = nwupdate.net, 
                       prevalence.FUN = prevalence.net, verbose.FUN = verbose.net,
                       module.order = c("resim_nets.FUN", "remove_edge_fx.FUN","infection.FUN","nwupdate.FUN", "prevalence.FUN"))
```

**Comment by ThomasKraft** [comment]
Oh I think maybe I see what's going on. Looks like `resimulate.network = TRUE` is overriding the `module.order` argument. So if I delete `resimulate.network = TRUE` in the last example then no transmission happens.

**Comment by smjenness** [comment]
@ThomasKraft : do you consider this issue resolved now? I will update the docs accordingly.

**Comment by ThomasKraft** [comment]
Yes thank you for the help! This can be closed. Just one last question -- how would one get netsim to save the network object (`get_network(x, sim = 1, network = 1, collapse = TRUE, at=5)`) such that it tells you what the network looked like at the time when transmission/infection are simulated? 

I could be wrong, but I would think that most users would want to know the network structure at the point where infection happens. Any other configuration would lead to the possibility that a visualization of the saved networks includes an infection event on two nodes that are not connected by a tie.

**Comment by smjenness** [comment]
This should in theory do just for nearly all use cases. I haven't tested it in your specific case where you are modifying the nD object directly in another module outside the resim_nets module but I'll take a look at this too.
