### ISSUE TITLE
Simulating networks with migration

### ISSUE THREAD

**Issue by thednainus** [statnet/EpiModel#483]
[proposed Label] helpQ

I'm trying to set a simulation using EpiModel and adding migration between two locations (global and region). I've contacted Samuel Jenness who suggested I create a large network with a nodal attribute for "place". He suggested that I could also add a nodemix term to specify that there is no edges between two locations. 

I am having a hard time to understand how nodemix would work. For example, if my formation formulae I have:
`formation <- ~edges + nodemix("place") + nodefactor("risk.group") + nodematch("risk.group") + concurrent`

So what is the above formula doing? Do I specify the total number of edges in the target statistics an that would be the sum of` mix.place.global.global`,` mix.place.global.region`, and `mix.place.region.region`?

How about the target.stats for `nodefactor`, `nodematch` and `concurrent`? That would be the total for the 2 populations? What happen if the 2 populations have different target statistics?

Sorry, I'm very new to this type of modeling and this might be an obvious question.

Thanks!
Fabricia.

**Comment by smjenness** [comment]
Hi @thednainus : 

first, this table may be helpful (http://statnet.org/nme/d2-ergmterms.html)

second, here is an example of how nodemix works:

```r
library("EpiModel")
data("faux.mesa.high")

faux.mesa.high
s <- summary(faux.mesa.high ~ nodemix("Grade"))
cbind(s)

mixingmatrix(faux.mesa.high, "Grade")
```
In an ERGM, nodemix is the count of edges between persons in each cell of the mixing matrix. For undirected networks, it is the count on the upper triangle of that matrix (the `mixingmatrix` function symmetrizes both halves). 

In fitting the ERGM you need to make decisions about which levels of nodemix you fit data to, and which remain free. A fully saturated model with an edges term (`nw ~ edges + nodemix("attr"))`) would include 1 less than the number of combinations (so, 20 values in the above example). To specify levels to fit data to, you can use the `levels2` argument to declare which are linked to target stats (the default is all values). 

```r
summary(faux.mesa.high ~ nodemix("Grade"))
summary(faux.mesa.high ~ nodemix("Grade", levels2 = c(2, 4, 7, 11, 16)))
summary(faux.mesa.high ~ nodemix("Grade", levels2 = -c(2, 4, 7, 11, 16)))
```

These show — respectively — dropping no levels, keeping only the off-diagonals for 7th graders, and keeping everything but those levels.

**Comment by smjenness** [comment]
> Do I specify the total number of edges in the target statistics an that would be the sum of` mix.place.global.global`,` mix.place.global.region`, and `mix.place.region.region`?

Yes, `edges` would be the sum of the cells in the (upper triangle of the) mixing matrix by this or any other attribute.

**Comment by smjenness** [comment]
> How about the target.stats for `nodefactor`, `nodematch` and `concurrent`? That would be the total for the 2 populations? What happen if the 2 populations have different target statistics?

These would be the totals across the full network. `concurrent` has a `by` argument so you can have it stratified by a variable like location. `nodefactor` allows for interaction terms (e.g., `nodefactor(c("place", "risk.group"))`). For `nodematch`, you would need to code up a dummy variable that would be that interaction. With all of these, to see how they work, set the attributes on the network object, and then use the `summary` function to see how they are handled as network terms. Then you can try out how to parameterize the model by estimating a simple model (e.g., only edges) with netest and then diagnosing (i.e., getting summary statistics for) a more complete model (here's an example: http://statnet.org/nme/d4-s5-Serosort.html).

**Comment by thednainus** [comment]
Hello, I'm opening this question because I'm still trying to figure out how to implement migration. Thanks for all the explanations. I'm still confused on how to make sure that the proper edges have been deleted. For example: I did use levels as you suggested to nodemix to allow to fit the model to two possibilities (region-region and global-global). Imagine that a migration happened and a "person" in _global_ migrated to _region_, but this "person" transmitted the disease to another person in _global_ (it's correct to say that an edge was created, right?). 

My question is: Should I remove this edge once a migration happens using a function within network_update module using something like `deactivate.edges(dat$nw[[1]], onset = at, terminus = Inf, e = migrations)` where `migrations` would be the ids for migrants. Or nodemix will take this into account?

Thanks!

**Comment by smjenness** [comment]
You could handle this process in either a deterministic, hard-coded way (the way that you have suggested above) or through the TERGM parameterization itself. I'm not sure what specific model form you are implementing, but if you use nodemix in the formation it is likely that you will also want to use it in the dissolution model as well. The latter ensures that the existing edges between non-matched pairs will not persist. I had a quick example related to age mixing prepared earlier, and I'm copying it below for reference:

```r
# Initialize network and set up binary age group attribute
nw <- network_initialize(n = 1000)
age.grp <- sample(1:2, 1000, TRUE)
nw <- set_vertex_attribute(nw, "age.grp", age.grp)

# formation model and target stats (overall edges, edges b/t 1-2, edges b/t 2-2)
form <- ~edges + nodemix("age.grp", levels2 = -1)
target.stats <- c(450, 125, 40)

# duration model and target stats (duration in 1-1, duration in 1-2, duration in 2-2)
durs <- c(60, 2, 80)
diss <- dissolution_coefs(~offset(edges) +
                            offset(nodemix("age.grp", levels2 = -1)),
                          duration = durs)

# Fit the TERGM
fit <- netest(nw, form, target.stats, diss)

# Simulate one long time series to examine timed edgelist
dx <- netdx(fit, nsims = 1, nsteps = 5000, keep.tedgelist = TRUE)

# Extract timed-edgelist
te <- as.data.frame(dx)
head(te)

# Limit to non-censored edges
te <- te[which(te$onset.censored == FALSE & te$terminus.censored == FALSE),
         c("head", "tail", "duration")]
head(te)

# Look up the age group of head and tail nodes
te$ag.head <- age.grp[te$head]
te$ag.tail <- age.grp[te$tail]
head(te)

# Calculate mean durations in each age-mixed group
mean(te$duration[te$ag.head == 1 & te$ag.tail == 1])
mean(te$duration[te$ag.head != te$ag.tail])
mean(te$duration[te$ag.head == 2 & te$ag.tail == 2])

# Compare to targets
durs
```
Hope that helps. One note: it is necessary to use a duration of 2 for non-matched pairs because EpiModel treats models with duration of 1 structurally differently.

**Comment by thednainus** [comment]
Thanks; I have run your example and trying to apply to my own example. 
I'm trying to fit a model to HIV epidemics in MSM only. However, I need to have migration in my model. I initially tried to use EpiModelHIV; however I need to implement a simpler model and wrote my own functions.

Would you mind clarifying the meaning of duration? Would that be the duration of the relationship?
Your comment in below says "duration model and target stats (duration in 1-1, duration in 1-2, duration in 2-2)". Just to make sure I understood correctly: Because your target stats you have **450** for overall edges,  **125** for edges b/t 1-2 and **40** for edges b/t 2-2. That means you will still have edges between 1-1 because the overall edges is 450? 
If you don't want any edges between 1-1 you would set up the target stats for edges b/t 1-2 and edges b/t 2-2 something as that the sum would be 450?

Thanks!

**Comment by smjenness** [comment]
> Would you mind clarifying the meaning of duration? Would that be the duration of the relationship?

Correct

> Because your target stats you have 450 for overall edges, 125 for edges b/t 1-2 and 40 for edges b/t 2-2. That means you will still have edges between 1-1 because the overall edges is 450?

Correct. The sum of the nodemix target stats = edges. Therefore, if you use an edges term in a model, you need to drop at least one level of nodemix to have enough degrees of freedom. So the number of 1-1 edges = 450 - 125 - 40 = 285.

> If you don't want any edges between 1-1 you would set up the target stats for edges b/t 1-2 and edges b/t 2-2 something as that the sum would be 450?

Right. Because the ERGM algorithms handle zeros structurally different than non-zero values, I would reparameterize the model by dropping a different level of nodemix:

```r
form <- ~edges + nodemix("age.grp", levels2 = -2)
target.stats <- c(450, 0, 40)
```

> I guess I am confused why specify duration for 1-1, if you are using nodemix("age.grp", levels2 = -1)

The dissolution model parameterization is slightly different (I realize this is confusing and we are currently doing a bit of work on dissolution model parameterization that will address this confusion). The first value (of duration) corresponds to the overall reference category (if the nodemix was zeroed-out). The help page for `dissolution_coefs` describes the different parameterizations for each dissolution model allowed.

Hope that helps!

**Comment by thednainus** [comment]
Thanks! I think I know understand it. At least my diagnostics makes sense now. 
If I also use `nodematch` and `nodemix` in my formation; I should also added it to the dissolution model as well?

Thanks very much for taking the time to reply my questions.

**Comment by smjenness** [comment]
> If I also use `nodematch` and `nodemix` in my formation; I should also added it to the dissolution model as well?

Not necessarily. However, for the time being, if you have one of those terms in the dissolution it must also be in your formation (the dissolution should be a subset of the formation).

**Comment by thednainus** [comment]
Thanks! I think I am almost there with my code including migration. Just to double check, I am re-using some code that uses `get.dyads.active` to get the pairs for a transmission to happen. So, do I have to hard code something to **not** allow transmissions between pairs that come from different places? For example, if I get a pair that one is from _region_ and the other is from _global_, do I have to hard code in the transmission module for that transmission **not** to happen?
I'm asking that because in my `nodemix` I set to zero the pair region-global. So, I tought that no transmission would happen. However, I still observe that transmission between _region_ and _global_ are happening (assuming that my code is free of bugs).

**Comment by smjenness** [comment]
> do I have to hard code something to not allow transmissions between pairs that come from different places? For example, if I get a pair that one is from region and the other is from global, do I have to hard code in the transmission module for that transmission not to happen? I'm asking that because in my nodemix I set to zero the pair region-global.

If the TERGM is parameterized correctly, this modification to get.dyads.active should not be necessary. It's worth double checking the model fit with netdx before you run the epidemic simulation with netsim.

**Comment by thednainus** [comment]
Thanks! I did run a diagnostics test before and it shows I have zero edges between global-region. This is all invented numbers as I still don't have access to the data I will fit my model to. 

My formation is :
`formation <- ~edges + nodemix("origin", levels2 = c(1, 2))`
`target.stats <- c(450, 225, 0)`

And my coefficient of dissolution is:
```
durs <- c(60, 60, 2)
coef.diss <- dissolution_coefs(~offset(edges) +
                            offset(nodemix("origin", levels2 = c(1, 2))),
                          duration = durs, d.rate = mean(dr_vec))
```

I saved transmission matrix and I included as additional information to the transmission matrix the _origin_ of both susceptibles and infected individuals. A small percentage of my transmissions are between _region_ and _global_. 
Any idea where I could have introduced an error on my functions to have these not expected pairs of transmissions?


Below is my diagnostics results:

```
EpiModel Network Diagnostics
=======================
Diagnostic Method: Dynamic
Simulations: 1
Time Steps per Sim: 1000


Formation Diagnostics
----------------------- 
                         Target Sim Mean Pct Diff Sim SD
edges                       450  473.808    5.291 17.010
mix.origin.global.global    225  228.378    1.501 10.837
mix.origin.global.region      0    0.000      NaN  0.000

Dissolution Diagnostics
----------------------- 
               Target Sim Mean Pct Diff Sim SD
Edge Duration  60.000   56.414   -5.977 55.026
Pct Edges Diss  0.017    0.016   -1.108  0.006
----------------------- 
* Heterogeneous dissolution model results averaged over
```

**Comment by smjenness** [comment]
> Do you have any idea where I could have introduced an error on my functions to have these not expected pairs of transmissions?

If you have a migration process, whereby persons move from global to region, it would be possible that they would be connected while in the same area but later disconnected after the migration. Just looking at the transmission matrix may not be able to differentiate when that migration occurred. Just a guess...

**Comment by thednainus** [comment]
How is the structure for the size of a network using the function `network.size(nw)`? I mean, during the course of a simulation, if a "person" dies, than it is fully removed from the network?

I set migration to zero, so I am expecting to see only pairs of _region_-_region_ or _global_-_global_ at the time of transmission and that should be reflected on my transmission matrix. I may have introduced some errors when using the `match` R function and the _uid_ (unique identifier).

**Comment by smjenness** [comment]
> I mean, during the course of a simulation, if a "person" dies, than it is fully removed from the network

No, if you are not using tergmLite (which does not retain the network object at all after the initialization module) then exiting nodes are "deactivated" (which means they can no longer form ties) but they are not removed from the network. It sounds like your TERGM is working but that you may have errors elsewhere in your new code. Good luck!

**Comment by thednainus** [comment]
Thanks for all the explanations! It seems that my code is now behaving much better and as expected regarding migrations and the use of `nodemix` when I set migrations to zero. I started from scratch and tried not to modify the core functions as much as I could, and the ones I had to modify, I kept the maximum as a could as the original version. I also used the `set_att`, `append_attr`, `get_attr` function and I added migrationTime to the `append_core_attr` function. I don't really know what I did that made the difference, but now I don't see any transmissions between different origin places (at least not in the few simulations I did to test the code). 

However, when I set migrations to happen I observe some transmissions between not allowed regions. But when checking the    transmissions, I see that for example, I have a transmission from _region_ to _global_, where the "individual" from _region_ was previously from _global_. Almost as if somewhere in the network is keeping the attributes from when it was actually global. 

So maybe it is possible that the edges have not been deactivated properly?
At the moment I am using:
`dat$nw[[1]] <- deactivate.edges(dat$nw[[1]], onset = at, terminus = Inf, e = get.edgeIDs(x = dat$nw[[1]], v = migrations21))`
Where migrations are the id for the index for the node as in `migrations21 <- which(migrants == 21 & active == 1 & migrationTime == at)`

The reason I am insisting on that is because I work with phylodynamics. I'm doing all this simulations so I know who infected whom in my phylogenetic tree and I will also need to know the origin of each tip in the phylogenetic tree.

**Comment by thednainus** [comment]
A bit more information:
I used the library `ndtv` to plot the interactions.
For that I used `activate.vertex.attribute` to track the change in _origin_ so I could plot the interactions.

I noticed that when I migration happen, the edges are not getting deactivated (I am using `deactivate.edges` function for that).  For example, there are 6 nodes connected with edges. At a time point, one of these nodes "migrate", and they keep connected for some steps until it disappears.

**Comment by thednainus** [comment]
I think I now fixed this. 
I just copied the solution described in the EpiModel function `deactivate.vertices`
And I added this to my code

```
      e = NULL
      for (vert in migrations12){
        e = c(e, get.edgeIDs.active(dat$nw[[1]], v = vert, onset = at,
                                    terminus = Inf, neighborhood = "combined"))
      }
      if (length(e) > 0) {
        dat$nw[[1]] <- deactivate.edges(dat$nw[[1]], onset = at, terminus = Inf,
                         e = unique(e))
      }
```

And it finally seems to work! Thanks for all the help!

**Comment by smjenness** [comment]
Great to hear, thanks!

**Comment by thednainus** [comment]
Hello, I am reopening this question because I think this is related to the fact I have two "different" populations within a single network.
I would like to do pos-modelling diagnosis of my simulations to check whether I have preserved the mean degree as expected.
However, the term `meandeg`, if I understood correctly, does not allow something that I could get the values by an attribute. Here my attribute would be _origin_. Something similar to use` concurrent(by = "origin")`.
So I guess what I am getting as `meandeg` is a result of the complete network. 
How is the best way of getting `meandeg` to check posmodelling diagnosis in this case?

Thanks!
Fabricia.

**Comment by sgoodreau** [comment]
Hi Fabricia, I am not sure I fully follow your question, but I *think* you are asking about how you can get the mean degree for different sets of nodes distinguished by the value of an attribute?  If so then you want to start with the term `nodefactor`, which will give the total degree for all nodes by levels of `nodefactor`.  You would then divide by the number of nodes in each level (which you can get using `get.vertex.attribute` with R's `table` or `tabulate` command).

**Comment by thednainus** [comment]
@sgoodreau Thanks! I managed to create a plot and see the mean degree **after** the simulation had finished.
I can see that my mean degree is **not** preserved with fluctuations in population size.
You can see an example of plot [here](https://github.com/thednainus/HIVepisim/blob/master/Analyses/Examples/example.pdf).
In this example, origin starts with _1000_ nodes and _global_ starts with 3000 nodes. 
I divided `nodefactor_origin/total_nodes_origin`. Also, note that in the third plot I sometimes observe some edges, and I thought I should always observe zero edges as my target stat for that formation was zero (see below), maybe I am not dissolving these edges properly.

Here is a summary of my model:
I have one single network with an attribute named **origin** that can take two values: _global_ or _region_
Using `nodemix` in my formation I allow edges to be formed between nodes in _global_ and between nodes in _region_. However, an edge should **not** be formed between a node in _global_ and a node in _region_.
The idea is to have two populations within a single network as suggested by @smjenness.
I allow individuals to migrate between populations. When they migrate, they start to belong to the other population. 
So, my population can grow with time because of individuals migrating and also because of individuals arriving in the network (similar to birth rate).



**So, maybe my dissolution coefficient is not quite right?**
I used the following for formation and dissolution:
```
formation <- ~edges + nodemix("origin", levels2 = c(1, 2))

#1.19 is the mean degree
target.stats <- c((1.19 * n_pop1/2 + 1.19 * n_pop2/2), 1.19 * n_pop2/2, 0)

durs <- c(23.7, 23.7, 2)
coef.diss <- dissolution_coefs(~offset(edges) +
                      offset(nodemix("origin", levels2 = c(1, 2))),
                      duration = durs, d.rate = mean(unlist(lapply(dr_vec, mean))))
```


[Here](https://github.com/thednainus/HIVepisim/blob/master/Analyses/Simulate_MSMpop_14Dec2021_OSG_checkpoint.R) is an example of a script to run my simulations. However, this requires the installation of the [R package ](https://github.com/thednainus/HIVepisim) I am trying to develop.

**Comment by sgoodreau** [comment]
Hi @thednainus, I'm sorry that I had quite the crazy quarter and am just now catching back up again.  I'm happy to take a look at this now, if it's still useful to you.  Is that the case or have you resolved it?  Also note that the link you have above to the script is broken now - not sure if it's a permissions issue or you moved things.  In either case, when I look at the code that you show above (with the mean degree of 1.19), it all looks right to me. 

BTW I don't know what your arrival rate is, but it can be possible for the growing edge count that you see in your plot to map onto a roughly constant mean degree, if the population is growing rapidly.  
Best,
Steve
