### ISSUE TITLE
Add a UID attribute to network nodes

### ISSUE THREAD

**Issue by AdrienLeGuillou** [statnet/EpiModel#485]
related to these two issues: #478 #482 

the goal would be to have a Unique Identifier (uid) attribute for each node in the network. 

it can be stored either as an `integer` (up to 4 billions unique values, negatives and positive) or `double` (way more values but larger memory requirements)

it would probably be beneficial to create a function for adding new nodes that ensures every attributes required by core EpiModel are set (`active` and `uid`).  This function would in turn be available for modules creators to ensure the compatibility with core EpiModel machinery.

**Comment by smjenness** [comment]
> it would probably be beneficial to create a function for adding new nodes that ensures every attributes required by core EpiModel are set (active and uid). This function would in turn be available for modules creators to ensure the compatibility with core EpiModel machinery.

Related to this, it would be good also to standardize the writing and appending of all the core attributes needed for open population models: http://statnet.org/tut/EpiModel2.html#extending-arrivals-departures

**Comment by smjenness** [comment]
Closed with #488
