### ISSUE TITLE
Implement new edges dissolution approximation method 

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#492]
This would implement the methodological work that @chad-klumb has done. The general idea is to build in the new value of the subtracted term for the formation model into `dissolution_coefs`. This would get saved, but not output with the print function. Then that value would get used in `netest` in replacement of the operation here: https://github.com/statnet/EpiModel/blob/master/R/netest.R#L201-L204.

Please feel free to use this issue for specific algorithms for EpiModel. I am going to set up another (private) repo for work on the general methods and translation to the methods paper.

cc: @martinamorris @sgoodreau

**Comment by martinamorris** [comment]
for efficiency/speed, is it worth using the new approximation (which doesn't subtract 1 from the edges adjustment term: log(D))?

**Comment by smjenness** [comment]
@chad-klumb : I'd like to work towards publishing the next version of EpiModel on CRAN within the next week, if possible. Could you implement the simple version of the new approximation (subtracting D instead of D-1) for this version, and then we can implement the more flexible version that does not require nesting of the dissolution model in the formation model for the next EpiModel version. In fact, I'd like to split off this issue that tackles the simple approach, and make a new one that handles the flexible approach. Let me know what you think. Thanks!

**Comment by chad-klumb** [comment]
Is the application in `netest` the only one we need to modify in `EpiModel` itself?

**Comment by smjenness** [comment]
> Is the application in `netest` the only one we need to modify in `EpiModel` itself?

Yes

**Comment by chad-klumb** [comment]
I've uploaded an implementation to the `EDA_update` branch.  The package tests pass (locally), and I ran a short duration edges-only model by hand; it appears to be functioning as intended.

Here's the test script:

```
require(EpiModel)
nw <- network_initialize(n = 100)

# Set formation formula
formation <- ~edges

# Set target statistics for formation
target.stats <- c(50)

# Obtain the offset coefficients
coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 2)

# Estimate the STERGM using the edges dissolution approximation
est <- netest(nw, formation, target.stats, coef.diss)

est

netdx(est, nsim = 100, nsteps = 1000)
```

Results with `EDA_update`:

```
Formation Diagnostics
----------------------- 
      Target Sim Mean Pct Diff Sim SD
edges     50   49.747   -0.506  7.011

Dissolution Diagnostics
----------------------- 
               Target Sim Mean Pct Diff Sim SD
Edge Duration     2.0    1.998   -0.077  1.413
Pct Edges Diss    0.5    0.500   -0.029  0.072
```

Results with `master`:


```
Formation Diagnostics
----------------------- 
      Target Sim Mean Pct Diff Sim SD
edges     50   97.897   95.794   9.84

Dissolution Diagnostics
----------------------- 
               Target Sim Mean Pct Diff Sim SD
Edge Duration     2.0    1.998   -0.080  1.413
Pct Edges Diss    0.5    0.500   -0.026  0.051
```

**Comment by smjenness** [comment]
Thanks @chad-klumb ! I created a PR #500 for this - I may add a few new unit tests but will then merge into master.
