### ISSUE TITLE
Question about netsim_loop

### ISSUE THREAD

**Issue by adam-s-elder** [statnet/EpiModel#496]
I was wondering what the reason is for the following lines of code inside of `netsim_loop` [here](https://github.com/statnet/EpiModel/blob/7bf5abcc3a376d1e1ecc288e77d9f94d7acfe12a/R/netsim.R#L188):

```r
for (at in max(2, control$start):control$nsteps) {
      morder <- control$module.order
      if (is.null(morder)) {
        lim.bi.mods <- control$bi.mods[-which(control$bi.mods %in% 
          c("initialize.FUN", "verbose.FUN"))]
        morder <- c(control$user.mods, lim.bi.mods)
      }
```

In particular, why do we use `max(2, control$start)` instead of just `control$start`?  Is there something that will go wrong if `at == 1` when calling the various modules?  I would be happy for an answer from anyone, but maybe @smjenness may be the best person to ask.  Thanks!

**Comment by smjenness** [comment]
@AdrienLeGuillou please comment

**Comment by AdrienLeGuillou** [comment]
Theoretically their should not be a problem to use `control$start` if it is set up correctly by the user. 

When I created `netsim_loop` I just extracted the previously existing code into a function. So the current check is what was in place before. https://github.com/statnet/EpiModel/pull/348/files

From what I understand, only the initialization module is ran when `at == 1`. Several things in the code (especially EpiModelHIV) seems to assume this behavior. For sake of not breaking things I tried to change as little as possible while doing the refactoring.

**Comment by adam-s-elder** [comment]
Ok!  Thanks for getting back to me so quickly about this!

**Comment by AdrienLeGuillou** [comment]
From my perspective, having the modules run from `at == 1` onward would be "cleaner" but I don't really know what side effects it could produce. If it helps for https://github.com/EpiModel/EpiModelHIV-p/issues/60, I suggest you try locally to see if it solves your issue.

**Comment by adam-s-elder** [comment]
Ok!  Sounds good.  Thank you!

**Comment by martinamorris** [comment]
@smjenness since this was in your original code, was the purpose to use step 1 to have mod.initialize simulate the network(s), and step 2 to get the rest of the process started?

**Comment by smjenness** [comment]
That's correct - the time loop starts at t_2
