### ISSUE TITLE
reimplement "save.network" outside of tergmLite

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#502]
It would be useful to be able to specify `save.network = F` in addition to `tergmLite = F` within the same call to `netsim`. This is desirable in a situation where tergmLite cannot be used due to the inclusion of an `edgecov` term, but saving the underlying network is problematic due to memory constraints. 

To my knowledge this was previously possible with the now deprecated `save.network` argument.

**Comment by smjenness** [comment]
@ThomasKraft : that makes sense, we can add it back. I will put in on the list for the next release.

**Comment by ThomasKraft** [comment]
Perfect, thank you!

**Comment by ThomasKraft** [comment]
@smjenness one quick follow-up here: is it the case that setting `save.network = F` will clear up memory at the end of each individual simulation, or just at the end of the entire call to `netsim`?

In other words, if I set `nsims = 10` and `ncores = 5`, will the network objects get removed after the first 5 sims are finished and then later from the last 5 when they finish? Or will all 10 network objects get cleared at the end of netsim?

**Comment by smjenness** [comment]
@ThomasKraft : thanks for your patience with this. This is now implemented. Note that `save.network = FALSE` is a "hidden" argument to `control.net`, meaning it is not listed in the documentation but it will be honored upon running netsim. This version of EpiModel will go up on CRAN hopefully sometime in the next week.

Regarding your question above: yes, the network object gets overwritten at the end of each block of simulations.

**Comment by ThomasKraft** [comment]
@smjenness that's fantastic, thank you! Am I right in assuming that the new EpiModel version for CRAN will still only be compatible with CRAN version of ergm/tergm? Or is there a chance it will work with ergm/tergm 4.0.x on master? I ask because otherwise I will continue using the dev version of EpiModel, which presumably wont have these changes to `save.network` just yet (is that correct?).

**Comment by smjenness** [comment]
Correct, master is a CRAN-compatible branch. @chad-klumb is routinely pulling EpiModel@master into EpiModel@dev so these updates should be there too. @chad-klumb : can you merge now?

**Comment by chad-klumb** [comment]
should be up to date now
