### ISSUE TITLE
new dev branch edgecov error

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#520]
Transitioning to the dev version of EpiModel, there is a new error that arises (without changing anything else) in how edgecov variables are handled. Specifically, there is now an error thrown if an edgecov is passed from the global env (e.g. `edgecov(variable)` ), but not if it is passed as a network attribute of a model (e.g. `net %n% "variable"; edgecov("variable")`). In the former case, the following error arises:

"A ERROR occured in module 'initialize.FUN' at step `Initialization Step` (1): 
	Error: In term ‘edgecov’ in package ‘ergm’: ‘x’ argument is not of any of the expected (matrix,network,character) types."

But in fact the input variable is of class matrix. Reprex:
```
library(EpiModel)

num=200
toy <- network_initialize(n=num, directed=F)
toy <- set_vertex_attribute(toy, "com_id", c(rep("1", num/4),rep("2", num/4),rep("3", num/2)))
toy <- set_vertex_attribute(toy, "family_id", c(rep("a", num/4), rep("a2", num/4) ,rep("b", num/8),rep("c", num/8), rep("d", num/8), rep("e", num/8)))

df <- data.frame(pid = toy %v% "vertex.names", 
                 com_id = toy %v% "com_id",
                 family_id = toy %v% "family_id")

kin<-matrix(sample(seq(0,.5, .1), num^2, replace=T),num)
kin[lower.tri(kin)] = t(kin)[lower.tri(kin)]
diag(kin) <- 0

dist<-matrix(sample(1:10000, num^2, replace=T),num)
dist[lower.tri(dist)] = t(dist)[lower.tri(dist)]
diag(dist) <- 0
dist <- log(dist+1)


for(i in unique(df$family_id)){
  for(j in unique(df$family_id)){
    dist[which(df$family_id == i), which(df$family_id == j)] <- rnorm(1, 8, sd=2)
  }
}

## Case 1
fit_test <- netest(toy,
                   formation = ~edges + nodematch("family_id") + edgecov(kin) + edgecov(dist),
                   constraints = ~blocks(attr = "com_id", levels2 = !diag(TRUE, 3)),
                   target.stats = c(30*num/20, 15, 30*.2*num/20, 8*num),
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 3), edapprox = T)

## Case 2
toy2 <- toy
toy2 %n% "log_dist_mat" <- dist
toy2 %n% "kin" <- kin

fit_test2 <- netest(toy2,
                   formation = ~edges + nodematch("family_id") + edgecov("kin") + edgecov("log_dist_mat"),
                   constraints = ~blocks(attr = "com_id", levels2 = !diag(TRUE, 3)),
                   target.stats = c(30*num/20, 15, 30*.2*num/20, 8*num),
                   coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 3), edapprox = T)


# Simulate epidemic
param <- param.net(inf.prob = 0.1, act.rate = 1, ei.rate = 1/3, ir.rate=1/10)  # day at which infections in town are finished
                   

init <- init.net(i.num = 2, r.num = 0)   # this alternative version randomly seeds a given number

control <- control.net(type = NULL, nsteps = 50, nsims = 2, ncores = 1,
                       epi.by = "com_id",
                       initialize.FUN = initialize.net,
                       resim_nets.FUN = resim_nets,
                       nwupdate.FUN = nwupdate.net, 
                       prevalence.FUN=prevalence.net,
                       tergmLite = F,
                       resimulate.network = T,
                       set.control.stergm=control.simulate.network(MCMC.burnin.min=5e3, MCMC.burnin.max=5e3),
                       module.order = c("resim_nets.FUN",  "nwupdate.FUN", "prevalence.FUN"))

# simulate!
sim <- netsim(fit_test, param, init, control)    # Error
sim <- netsim(fit_test2, param, init, control)   # Works
```

Session info:

! package        * version    date       lib source                                 
   EpiModel       * 2.0.4      2021-04-13 [1] Github (statnet/EpiModel@5432e25)      
   ergm           * 4.0-6210   2021-04-23 [1] Github (statnet/ergm@200fdd7)          
 P network        * 1.17.0-666 2021-04-23 [2] Github (statnet/network@918e4ee)       
   networkDynamic * 0.10.2     2021-03-30 [2] Github (statnet/networkDynamic@e275b94)
 P statnet.common * 4.5.0-340  2021-04-23 [2] Github (statnet/statnet.common@e6275f2)
   tergm          * 4.0.0-2177 2021-04-23 [1] Github (statnet/tergm@d67cbf7)         
   tergmLite      * 2.2.1      2021-04-13 [1] Github (statnet/tergmLite@959d239)

**Comment by smjenness** [comment]
@chad-klumb : could you take a look at this?
cc: @martinamorris

**Comment by chad-klumb** [comment]
I've updated a utility function in tergm to better handle environments, and that appears to have fixed the error for me.  Can you try re-installing `tergm` and seeing if the problem persists for you?

**Comment by ThomasKraft** [comment]
For whatever reason re-installing `tergm` has somehow caused problems with `devtools` such that ergm_3.11.0 is being loaded via namespace, causing EpiModel to have lots of other problems. I'm still trying to figure out how to workaround this so I can test your solution. I very much appreciate the effort and will get back to you as soon as this is working.

**Comment by ThomasKraft** [comment]
OK I was able to get `tergm` updated and this does seem to have resolved the issue for me. Thanks @chad-klumb !
