### ISSUE TITLE
Best way of simulating large networks

### ISSUE THREAD

**Issue by thednainus** [statnet/EpiModel#522]
Hello,

I am trying to simulate large networks but I am having problems when checking the diagnostics and reaching the target statistics.
For example, when I simulate small network sizes with less than 50,000 nodes, it runs fine. 
However, when I increase it to network sizes of 150,000, the target statistics for formation are not met (see below). 
I might be missing something when running these analysis.

Thanks!

```
est <- netest(nw, formation, target.stats, coef.diss, edapprox = TRUE)

# Model diagnostics
dx <- netdx(est, nsims = 1, nsteps = 1000, keep.tedgelist = TRUE)
```

Results for large networks:

```
EpiModel Network Diagnostics
=======================
Diagnostic Method: Dynamic
Simulations: 1
Time Steps per Sim: 10000

Formation Diagnostics
----------------------- 
                         Target Sim Mean Pct Diff Sim SD
edges                      2200 1495.537  -32.021  68.11
mix.origin.global.global    200    0.000 -100.000   0.00
mix.origin.global.region      0    0.000      NaN   0.00

Dissolution Diagnostics
----------------------- 
               Target Sim Mean Pct Diff Sim SD
Edge Duration  23.700   23.607   -0.394 23.083
Pct Edges Diss  0.042    0.042    0.153  0.005
----------------------- 
* Heterogeneous dissolution model results averaged over
```

Results for smaller networks.

```
EpiModel Network Diagnostics
=======================
Diagnostic Method: Dynamic
Simulations: 1
Time Steps per Sim: 1000

Formation Diagnostics
----------------------- 
                         Target Sim Mean Pct Diff Sim SD
edges                       600  622.131    3.688 24.609
mix.origin.global.global    200  207.708    3.854 14.600
mix.origin.global.region      0    0.000      NaN  0.000

Dissolution Diagnostics
----------------------- 
               Target Sim Mean Pct Diff Sim SD
Edge Duration  23.700   23.055   -2.720 22.287
Pct Edges Diss  0.042    0.042    0.568  0.008
----------------------- 
* Heterogeneous dissolution model results averaged over
```

**Comment by smjenness** [comment]
I believe for simulating very large networks bumping up some of the MCMC simulation parameters is necessary for both estimation and simulation. @chad-klumb @martinamorris @sgoodreau @dth2 could you comment with your experiences?

**Comment by dth2** [comment]
There are four different control arguments that I have found to be useful for simulating larger networks:  

MCMC.prop.form
MCMC.init.maxchanges
MCMC.burnin.min
MCMC.burnin.max

Given that you are underfitting your edge count it may be that you are simply not proposing enough edges, in which case bumping up the MCMC.init.maxchanges to something like 1e7 should get your edge count to the 2200 target. I am currently estimating a 500K node network with 

MCMC.init.maxchanges = 1e7
MCMC.burnin.min= 1.5e5
MCMC.burnin.max  =1.5e5

Depending on the structure of the network you are trying to estimate it may be helpful to specify the MCMC.prop.form to increase the efficiency of the proposals but that will be specific to your network.

**Comment by thednainus** [comment]
Thanks!! You mean setting these parameters inside netdx function as
 `set.control.ergm = control.simulate.ergm(MCMC.init.maxchanges = 1e7, MCMC.burnin.min= 1.5e5, MCMC.burnin.max =1.5e5)`

My model is simple (well it is a complex HIV epidemix but simpler than epimodelHIV). I also implement migration between 2 population that @smjenness kindly helped me. Ideally I should simulate a very large network size for one of my populations. So I started to play with the numbers to see how big I can go.

**Comment by dth2** [comment]
Also be aware that the MCMC control arguments are different for ergm and tergm so they will be slightly different for estimation and dynamic simulation. In estimation the MCMC burnin is not specified as a min or max and the MCMC.interval can also be directly specified. 
 
MCMC.burnin=1e6,
MCMC.interval=1e5 

And in the estimation step you can also specify control for SAN that will improve efficiency.

**Comment by dth2** [comment]
Yes, your two lines of code would look like this

est <- netest(nw, formation, target.stats, coef.diss, edapprox = TRUE,
                       set.control.ergm = list(MCMC.burnin=1e6,
                                      MCMC.interval=1e6,
                                      MCMC.samplesize=10000,
                                      init.MPLE.samplesize = 1e7
                                      SAN.nsteps = 1e7)))

# Model diagnostics
dx <- netdx(est, nsims = 1, nsteps = 1000, keep.tedgelist = TRUE,
                                                         set.control.stergm = list(MCMC.init.maxchanges = 1e8,
                                                                                                MCMC.burnin.min =1.5e5,
                                                                                                MCMC.burnin.max =1.5e5)))

**Comment by thednainus** [comment]
Should I set `set.control.stergm` in model diagnostics even tough the `edapprox = TRUE` in `netest`?

**Comment by dth2** [comment]
Yes, because you want to increase the number of proposals in the MCMC.

**Comment by smjenness** [comment]
@thednainus : did these suggestions help? Can we consider this issue closed?

**Comment by thednainus** [comment]
Yes, you can close it. Thanks!
Just a fix to the above reply (I cannot edit the answer).

instead of `list` it should read `control.ergm`, similarly for `SAN.nsteps = 1e8`:

```
est <- netest(nw, formation, target.stats, coef.diss, edapprox = TRUE,
              set.control.ergm = control.ergm(MCMC.burnin=1e7, MCMC.interval=1e7,
                                              MCMC.samplesize=20000,
                                              init.MPLE.samplesize = 1e8,
                                              SAN.control = control.san(SAN.nsteps = 1e8)))
```


```
dx <- netdx(est, nsims = 1, nsteps = 1000, keep.tedgelist = TRUE,
            set.control.ergm = control.simulate.stergm(MCMC.init.maxchanges = 1e8,
                                                     MCMC.burnin.min= 1.5e5,
                                                     MCMC.burnin.max =1.5e5))


```
