### ISSUE TITLE
memory management problem arising with module

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#523]
When I run a netsim with custom modules and monitor memory usage across cores using htop (on a linux HPC), I am seeing the memory usage increase dramatically over the course of the run (until it crashes with each core eating ~100 GB). As far as I can tell, this problem only occurs when including custom modules. I am trying to troubleshoot this problem but with great difficulty. Some clues:

1) If I do a shorter run that is able to finish, htop is showing me that ~26 GB of memory are being used. If I run `library(pryr)` and then `object_size(sim)` on my netsim object, however, the object shows up as being just 2 MB! `mem_used()` shows only 180 MB. So I suspect there is something wonky going on with environments.

2) Setting `save.network = F` does not change anything

3) I was running identical modules previously on the CRAN version of EpiModel and this problem did not occur. My current session info:
package        * version    date       lib source                                 
 EpiModel       * 2.0.4      2021-04-16 [1] Github (statnet/EpiModel@5432e25)      
 ergm           * 4.0-6288   2021-05-05 [1] Github (statnet/ergm@08c09bb)          
 network        * 1.17.0-666 2021-05-05 [1] Github (statnet/network@650cbf2)       
 networkDynamic * 0.10.2     2021-04-16 [1] Github (statnet/networkDynamic@e275b94)
 statnet.common * 4.5.0-346  2021-05-05 [1] Github (statnet/statnet.common@1dcd24f)
 tergm          * 4.0.0-2177 2021-05-05 [1] Github (statnet/tergm@941db24)         
 tergmLite      * 2.2.1      2021-04-16 [1] Github (statnet/tergmLite@959d239)    

4) When a run is over, if I clear the workspace with `rm(list=ls())` and then run `gc()` it fails to reduce the memory usage shown in htop. This again suggests something going on with environments?

5) Watching on htop would seem to suggest a non-linear memory expansion over the course of the run.

In my modules I do sometimes create temporary objects, but nothing very large. Anything obvious going on here? Any thoughts or insights on this problem greatly appreciated.

**Comment by ThomasKraft** [comment]
Another big clue that I forgot: after letting `netsim` finish (htop is now reading 26 GB used), and I re-run the same `netsim` command, then the second time every process starts out using 26 GB, and continues to increase from there over the course of the run. So this would mean that something I'm not seeing in the (global?) environment is getting added to each iteration, but I can't for the life of me figure out where.

**Comment by smjenness** [comment]
@krivit , @chad-klumb : this likely due to changes in the recent 4.0 versions of Statnet as this problem did not occur with CRAN versions. Could you provide input here?

**Comment by martinamorris** [comment]
@ThomasKraft can you verify that this model doesn't have memory problems with the CRAN versions?

**Comment by smjenness** [comment]
@martinamorris : he says so above in point 3

**Comment by ThomasKraft** [comment]
I did that check, but not on the HPC (having some problems with dev_mode() on the cluster...). I'm overwriting the with the CRAN version now to run a test on the same system with CRAN versions -- will report back in a few minutes.

**Comment by martinamorris** [comment]
@smjenness Sorry!  multitasking.

**Comment by ThomasKraft** [comment]
OK yes I can confirm that this appears to be a problem that arises due to the tools in 4.0. BUT, the unavoidable difference between switching versions is that with ergm/tergm 4.0 I am employing a different form of constraint in my model: `constraints = ~blocks("com_id", levels2=~!diag(TRUE, length(unique(.nw%v%"com_id"))))...`

Versus this kind of structure for the older version: `offset(absdiff(~as.integer(com_id))) , coef.form = c(-Inf)...`

It is not possible to include the first constraint structure above without using 4.0. This actually leads me to suspect that the use of `blocks` could be the source of the problem. In one respect this has already been helpful, because the obvious workaround is for me to go back to using the CRAN version of ergm/tergm for now with master EpiModel, although I would like to make the switch for the lovely speed benefits when possible!

**Comment by chad-klumb** [comment]
Can you try re-running the 4.0 install stack but with `ergm` and `tergm` versions given by

`"statnet/ergm@d2a8e54ffff8dbd1b9763227c5b7078a58462cc8"`

and

`"statnet/tergm@1e83e1b71e8280653c514e6806f8b43e5d488743"`

and see if you still get the memory explosion?

**Comment by chad-klumb** [comment]
I would stick with whatever you were using before.

**Comment by ThomasKraft** [comment]
Using those commits does not seem to alleviate the problem.

**Comment by ThomasKraft** [comment]
OK confirmed, reverting the version did not change the outcome. The effect is more easily observable when using a large `netest` object (larger underlying network). The memory usage appears to continually increase as the run continues all the way to the end.

**Comment by ThomasKraft** [comment]
Thanks @chad-klumb, here are some answers:

1) **Yes**, the simulation is using several large `edgecov` matrices (3 to be specific). 2 of these are "in the environment" (e.g. a syntax of `edgecov(variable)`, whereas the third is included as a network covariate (e.g. a syntax of `edgecov("variable")`). You also guessed correctly -- the one that is included as a network covariate is modified **at every step of the simulation**. Incidentally, I include it as an network covariate for exactly this reason: so that I can update it dynamically and have that taken into account (e.g. in my module I can do something like `dat$nw[[1]] <- new_matrix`.

2) This is a `tergm` simulation.

3)  This is only on a cluster. Because I am on windows and am still having problems running in parallel, I can't do exactly the same test. But with a single run the memory quickly crashes my local machine, so I think this problem exists on both. I will try some smaller tests to be sure.

4) **Correct**, as far as I can tell this only happens with my custom modules (likely culprit the modified edgecov variables perhaps?).

**Comment by chad-klumb** [comment]
In that case, can I trouble you for a reproducible example using only built-in functionality?

**Comment by ThomasKraft** [comment]
@chad-klumb yes, absolutely (my apologies for not sending one sooner -- I thought it was more related to my specific modules and didn't realize it would generalise). I just ran a test on the code below, and it definitely reproduces the problem!

reprex:
```
library(EpiModel)

num=3000
toy <- network_initialize(n=num, directed=F)
#toy <- set_vertex_attribute(toy, "com_id", c(rep("1", num/4),rep("2", num/4),rep("3", num/4)))
toy <- set_vertex_attribute(toy, "com_id", c(rep("1", num/3),rep("2", num/3),rep("3", num/3)))

kin<-matrix(sample(seq(0,.5, .1), num^2, replace=T),num)
kin[lower.tri(kin)] = t(kin)[lower.tri(kin)]
diag(kin) <- 0

dist<-matrix(sample(1:10000, num^2, replace=T),num)
dist[lower.tri(dist)] = t(dist)[lower.tri(dist)]
diag(dist) <- 0
dist <- log(dist+1)


df <- data.frame(pid = toy %v% "vertex.names", com_id = toy %v% "com_id",
                 home_community = toy %v% "home_community",
                 age_cat_CFR = toy %v% "age_cat_CFR",
                 com_id = toy %v% "com_id",
                 community_id = toy %v% "com_id",
                 family_id = toy %v% "family_id",
                 house_id = toy %v% "family_id")

for(i in unique(df$family_id)){
  for(j in unique(df$family_id)){
    dist[which(df$family_id == i), which(df$family_id == j)] <- rnorm(1, 8, sd=2)
  }
}

age_cat_CFR <- c("10_20", "21_30", "31_40", "41_50", "51_60", "61_70", "71_80", "80_plus")

toy <- set_vertex_attribute(toy, "home_community", toy %v% "com_id")
toy <- set_vertex_attribute(toy, "time_out_of_home", rep(0, num))
toy <- set_vertex_attribute(toy, "age_cat_CFR", sample(unique(age_cat_CFR)))
# toy <- set_vertex_attribute(toy, "family_id", c(rep("a", num/4), rep("a2", num/4) ,rep("b", num/4),rep("c", num/8), rep("d", num/8)))
toy <- set_vertex_attribute(toy, "family_id", c(rep("a", num/6), rep("a2", num/6) ,rep("b", num/6),rep("c", num/6), rep("6", num/8), rep("6", num/8)))

df <- data.frame(pid = toy %v% "vertex.names", com_id = toy %v% "com_id",
                 home_community = toy %v% "home_community",
                 age_cat_CFR = toy %v% "age_cat_CFR",
                 com_id = toy %v% "com_id",
                 community_id = toy %v% "com_id",
                 family_id = toy %v% "family_id",
                 house_id = toy %v% "family_id")


toy %n% "log_dist_mat" <- dist

ft <- netest(toy,
             formation = ~edges + edgecov(kin) + edgecov("log_dist_mat"),
             constraints = ~blocks("com_id", levels2=~!diag(TRUE, length(unique(.nw%v%"com_id")))),
             target.stats = c(3000, mean(kin)*num, mean(dist)*num),
             coef.diss = dissolution_coefs(dissolution = ~offset(edges), duration = 10), edapprox = T)


param <- param.net(inf.prob = 0.3, act.rate = 1)
init <- init.net(i.num = 10, r.num = 0)
control <- control.net(type = NULL, nsteps = 100, nsims = 3, ncores = 3,
                       epi.by = "com_id",
                       tergmLite = F,
                       resimulate.network = T,
                       set.control.stergm=control.simulate.network(MCMC.burnin.min=5e4, MCMC.burnin.max=5e4))

simz <- netsim(ft, param, init, control)
```

**Comment by chad-klumb** [comment]
Can you try re-running the 4.0 install stack but with `tergm` version

`"statnet/tergm@simulate_update"`

and see if the problem persists?

**Comment by ThomasKraft** [comment]
I installed the `simulate_update` branch of `tergm` but that doesn't seem to have changed the outcome on the reprex above. Just in case I've done something wrong, here is my session info:

! package        * version    date       lib source                                                                    
   EpiModel       * 2.0.4      2021-05-07 [1] Github (statnet/EpiModel@bfd60c1)      
   ergm           * 4.0-6298   2021-05-07 [1] Github (statnet/ergm@26a42e7)          
   network        * 1.17.0-666 2021-05-07 [1] Github (statnet/network@650cbf2)       
   networkDynamic * 0.10.2     2021-05-07 [1] Github (statnet/networkDynamic@e275b94)
   statnet.common * 4.5.0-348  2021-05-07 [1] Github (statnet/statnet.common@d281c24)
   tergm          * 4.0.0-2177 2021-05-07 [1] Github (statnet/tergm@57ca5bf)         
   tergmLite      * 2.2.1      2021-05-07 [1] Github (statnet/tergmLite@d996efa)     

Is this currently working for you?

**Comment by chad-klumb** [comment]
With the install stack

```
remotes::install_github(c("statnet/rle@master",
                          "statnet/statnet.common@master",
                          "statnet/network@master",
                          "statnet/networkDynamic@master",
                          "statnet/ergm@master",
                          "statnet/tergm@simulate_update",
                          "statnet/tergmLite@dev",
                          "statnet/EpiModel@dev"), dependencies = FALSE, force = TRUE)
```

I am able to run your example to completion without ever using more than ~2-3 GB on each core.  There is some fluctuation in the instantaneous memory usage, but it doesn't rise steadily at any significant rate, and the amount used at the end is more or less what it was using at the beginning.

**Comment by ThomasKraft** [comment]
That is odd, the only difference with my install stack is that I didn't have `dependencies` or `force` set. Memory increases over the course of the run to >70 GB per core (when I cut it off). Is there any reason to think think this would make a difference? Here is my install stack:

```
remotes::install_github(c("statnet/rle@master",
                          "statnet/statnet.common@master",
                          "statnet/network@master",
                          "statnet/networkDynamic@master",
                          "statnet/ergm@master",
                          "statnet/tergm@simulate_update",
                          "statnet/tergmLite@dev",
                          "statnet/EpiModel@dev"))
```

**Comment by chad-klumb** [comment]
I wouldn't expect a difference in this case, but you could try mine anyway, if you haven't already.

Assuming that doesn't work, can you try running it locally, even if it's on a single core?  Both a multi-core run on a unix server (the closest thing I have to a linux cluster) and a single-core run on a windows laptop exhibited the memory issue with `tergm` `master` but not with the `simulate_update` branch.

**Comment by ThomasKraft** [comment]
I re-ran on a single core on my windows desktop, and it worked just fine using the `simulate_update` branch! This has me a baffled but I'll try with a clean install on the cluster and see if I can't get it to replicate. For now the same version seems to be producing different outcomes on each... if something systematic comes up I'll let you know.

Will `simulate_update` be merged with `tergm` master or should I keep using that branch for the time being?

**Comment by chad-klumb** [comment]
For the time being I've made changes in `master` that are similar to those in `simulate_update`, although `master` will likely undergo more changes in the near future pending some further discussion on this topic (in a soon-to-be-created `tergm` issue).

Can you test your example with `master` and let me know if you have any further concerns here?

**Comment by ThomasKraft** [comment]
@chad-klumb I have now tested this with `master` and can confirm that it has solved the memory issue.
