### ISSUE TITLE
Installing EpiModel from GH master prompts to install statnet GH master versions

### ISSUE THREAD

**Issue by martinamorris** [statnet/EpiModel#524]
From my install just now:

```
> remotes::install_github("statnet/EpiModel@master",
+                         lib = master_lib)
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo statnet/EpiModel@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                               
2: CRAN packages only                                
3: None                                              
4: colorspace (2.0-0        -> 2.0-1       ) [CRAN]  
5: network    (54867ca5d... -> ec2ab4879...) [GitHub]
6: ergm       (0baa072de... -> 26a42e7ac...) [GitHub]
```

This is a problem, right?  The master versions of the statnet packages are now the 4.0 release candidates.  My understanding of Sam's policy for EpiModel master is that it is compatible with CRAN versions of the statnet packages.  So if someone did what this prompt suggests, they would end up with incompatible versions.

I also don't understand why I'm getting this prompt -- the EpiModel DESCRIPTION file doesn't identify any remote dependencies.

**Comment by smjenness** [comment]
The issue is that you have the Github version of ergm and network installed before running remotes::install_github for EpiModel. EpiModel's DESCRIPTION enforces a minimum version number but not a maximum (where github versions > CRAN versions). You would need to uninstall those github versions or just run install.packages to get the cran versions instead.

**Comment by smjenness** [comment]
Secondarily, and not the real issue here, you can avoid checking for package dependency upgraded versions with install_github(..., upgrade = FALSE).
