### ISSUE TITLE
Allow random parameters to be generated from correlated distribution

### ISSUE THREAD

**Issue by AdrienLeGuillou** [statnet/EpiModel#533]
The idea would be to allow correlation between two or more random parameters

```r
my_randoms <- list(
  act.rate = param_random(c(0.25, 0.5, 0.75)),
  tx.prob = function() rbeta(1, 1, 2),
  stratified.test.rate = function() c(
    rnorm(1, 0.05, 0.01),
    rnorm(1, 0.15, 0.03),
    rnorm(1, 0.25, 0.05)
  ),
  list(
    params = c("p1", "p2", "p3"),
    generator = function() list(runif(1), rbinom(1, 10, 0.3), rnorm(1))
  )
)
```

**Comment by smjenness** [comment]
that looks great. I think the correlated parameters sublist should be named.

**Comment by AdrienLeGuillou** [comment]
I think so too, but I don't know what name / name template to use. We might have several of such list

**Comment by AdrienLeGuillou** [comment]
Here is a more complete example of how the interface to use such parameters would look like:

``` r
# Defining a parameter generator function
correlated_params1 <- function() {
  p1 <- runif(1)
  p2 <- p1 + runif(2)
  p3 <- rnorm(2) + p2

  # The result MUST be a list as p1, p2 and p3 may be of different sizes
  return(list(p1, p2, p3))
}

# Defining a parameter generator function
correlated_params2 <- function() {
  pA <- runif(1)
  pB <- pA * 2

  # The result MUST be a list as pA, pB may be of different sizes
  return(list(pA, pB))
}

# Defining the list of random parameters
my_randoms <- list(
  act.rate = param_random(c(0.25, 0.5, 0.75)),
  tx.prob = function() rbeta(1, 1, 2),
  stratified.test.rate = function() c(
    rnorm(1, 0.05, 0.01),
    rnorm(1, 0.15, 0.03),
    rnorm(1, 0.25, 0.05)
  ),
  # for correlated parameters, we must define the name of the parameters and
  # the function that will produce them
  list(
    params = c("p1", "p2", "p3"),
    generator = correlated_params1
  ),
  list(
    params = c("pA", "pB"),
    generator = correlated_params2
  )
)

param <- param.net(rec.rate = 0.02, random.params = my_randoms)
```

In this example, the parameters are actually correlated and there is two sets of them. Because of this, we cannot name the lists. A solution if we absolutely want the correlated parameters sublist to be named would be to allow only one of it's kind:

``` r
# Defining a parameter generator function
correlated_params <- function() {
  p1 <- runif(1)
  p2 <- p1 + runif(2)
  p3 <- rnorm(2) + p2

  pA <- runif(1)
  pB <- pA * 2

  return(list(p1, p2, p3, pA, pB))
}

# Defining the list of random parameters
my_randoms <- list(
  act.rate = param_random(c(0.25, 0.5, 0.75)),
  tx.prob = function() rbeta(1, 1, 2),
  stratified.test.rate = function() c(
    rnorm(1, 0.05, 0.01),
    rnorm(1, 0.15, 0.03),
    rnorm(1, 0.25, 0.05)
  ),
  # for correlated parameters, we must define the name of the parameters and
  # the function that will produce them
  correlated_parameters = list(
    params = c("p1", "p2", "p3", "pA", "pB"),
    generator = correlated_params
  ),
)

param <- param.net(rec.rate = 0.02, random.params = my_randoms)
```
@smjenness, which option do you prefer? Or do you see something better?

**Comment by smjenness** [comment]
Thanks for this. It might be a little too general and thus a little too complex for the use case I am envisioning, which is just working from a nice rectangular data.frame of posterior distributions (e.g., from ABC). What we need is an extension of the `EpiModel::param_random` that you built that randomly samples from rows of a data.frame (or matrix). The data.frame should come in with named columns. 

```r
# something like this comes from ABC
df <- data.frame(matrix(runif(25), nrow = 5, ncol = 5))
names(df) <- paste0("param", 1:5)

# then we pass in like this
# Defining the list of random parameters
my_randoms <- list(
  act.rate = param_random(c(0.25, 0.5, 0.75)),
  tx.prob = function() rbeta(1, 1, 2),
  stratified.test.rate = function() c(
    rnorm(1, 0.05, 0.01),
    rnorm(1, 0.15, 0.03),
    rnorm(1, 0.25, 0.05)
  ),
  param_random_set = df
)
```

what do you think?

**Comment by AdrienLeGuillou** [comment]
I really like this idea of providing a rectangular set of data for this. But we still need a way to deal with multi-dimensional parameters like `stratified.test.rate` above. 

This can be done with `tibble` and `data.table` that accept "list columns", but not with regular `data.frame` or `matrix`. In base R, `list`s are the only option. We could also use suffixes as you suggested for #554. But the suffix way might be problematic here as it forces to use a rigid naming scheme so we can programmatically assume what column is a parameter and what is part of one.

The closest to what you propose would be to have named list of parameters, allowing arbitrary parameter size. netsim would then  check that each parameter have the same number of "row". And pick one at random before the actual simulation.

**Comment by smjenness** [comment]
Maybe this is more complicated than necessary. How about:
1. All scalar random parameters should use dot case (e.g., `rec.rate`) in the data frame column names
2. Any stratified random parameters (vectors) should use dot case plus underscore order (e.g., `rec.rate_1`, `rec.rate_2`) in the data frame column names

For any stratified random parameters, you then match on the substr before _ and put into a vector. 

This is not generalizable to all possible use cases, but to the immediate one I have in my head. 

Thoughts?

**Comment by smjenness** [comment]
Regarding the "rigid naming scheme", this like a reasonable convention to me. And it would be generally backwards compatible because these parameter values would only get parsed if the user implemented the random parameter API, which is new.

**Comment by AdrienLeGuillou** [comment]
I agree with you and this will be pretty easy to implement.

It is actually a pretty general approach as it leaves the user with the choice of how to generate these values. We would only provide a way to give them to the model.

Should this be added inside `param$random.params` or as a separated element? I feel it could be separated as with this approach we could put all the random parameters in this format and not use the `param$random.params` list of function at all. This might be more familiar to user not used to passing functions as arguments.

**Comment by smjenness** [comment]
I think it should be included in param$random.params
