### ISSUE TITLE
Warnings about isTERGM line

### ISSUE THREAD

**Issue by jmittler** [statnet/EpiModel#547]
When we run some code (EvoNetHIV) that depends on EpiModel, we the following warning:

 WARNING occured in module 'resim_nets.FUN' at step 6932: 
	simpleWarning in if (isTERGM == TRUE) {: the condition has length > 1 and only the first element will be used

The offending line seems to be

isTERGM <- ifelse(nwparam$coef.diss$duration > 1, TRUE, FALSE)

Our values for this parameter are:
 
nwparam$coef.diss$duration
[1]  730.00 1632.33 3650.00

Can you take a look?

Thanks,
John Mittler
Univ of Washington
jmittler at uw dot edu

**Comment by smjenness** [comment]
Thanks @jmittler : I will get this fixed in the next EpiModel version. For the time being, you can use EpiModel v2.0.2 without any likely impact on EvoNet code.

**Comment by smjenness** [comment]
@jmittler : this is now fixed on master. Feel free to use either the older CRAN version or this Github version.
