### ISSUE TITLE
Decide on specs for output data to facilitate comparing output from multiple runs

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#55]
**Migrated from trac ticket 338**:
Comparison of output is the main goal of the simulation laboratory. We would like to facilitate the following nested comparisons:

1. transmission replications:  multiple transmission runs from a single network realization from a single model
2. network replications:  multiple network realizations from a single model
3. multiple models (e.g., serial monogamy vs. concurrency)

What we want to compare:
Ideally, we want to create a `data.frame` with the input and output data from each run, where the replications are numbered sequentially 

1. S, I, R number and prevalence, births/deaths -- at each time step
2. run parameters (model params)
3. replication numbers (net replication within model, trans replication within network)

These data should conform to the input data specs for the `R` functions "aov" "lm" and "glm".  I think of this as a "flat file" -- which is not the most efficient way to store it, but may be the only form we can use as input for the analysis functions.

**Comment by smjenness** [comment]
Issues was DOA

**Comment by martinamorris** [comment]
DOA?

On Thu, 30 Jun 2016, Samuel Jenness wrote:

> 
> Issues was DOA
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[AH0J4roKoZyxWJNZxoeoFSYsb-yhKlDTks5qQ_VdgaJpZM4CU7EB.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/
