### ISSUE TITLE
possible redundancy and inconsistency in nwstats handling

### ISSUE THREAD

**Issue by chad-klumb** [statnet/EpiModel#551]
With `sim_nets_t1` now being called in `initialize.net` here

https://github.com/statnet/EpiModel/blob/502330ac71653e0edcc1b79d09f4b9812a7c31a8/R/net.mod.init.R#L41

the later setup of `nwstats` for `tergmLite` here

https://github.com/statnet/EpiModel/blob/502330ac71653e0edcc1b79d09f4b9812a7c31a8/R/net.mod.init.R#L76-L94

may be redundant.

The `sim_nets_t1` function also drops statistics with duplicated names here

https://github.com/statnet/EpiModel/blob/502330ac71653e0edcc1b79d09f4b9812a7c31a8/R/net.mod.simnet.R#L101-L102

while this is not currently done in `tergmLite` handling of stats.

**Comment by smjenness** [comment]
Yes, good find. It would be good to move the tergmLite nwstats set up in initialize.net all to sim_nets_t1. I am thinking that initialize.net would be outward user facing (i.e., more readily readable and editable by epidemiologists) whereas sim_nets_t1 is internal and not intended to be editable. If you agree, would you move your new tergmLite nwstats bits to sim_nets_t1? IMO, any duplicated stats should be dropped (e.g., if the ERGM formula is ~edges but the monitored formula is ~edges + isolates, edges should not be repeated).
