### ISSUE TITLE
I am getting an error with EpiModel 2.1.0 when the control object is checked

### ISSUE THREAD

**Issue by dth2** [statnet/EpiModel#557]
At this line:
https://github.com/statnet/EpiModel/blob/a67a82aaf9778c512f2b2adb700518199423783f/R/netsim.R#L125

check.control.class("net", "EpiModel netsim")

check.control.class uses as.control.list from statnet.common and I get the following error.

Error in UseMethod("as.control.list") : 
  no applicable method for 'as.control.list' applied to an object of class "control.net"

**Comment by smjenness** [comment]
Is this for core EpiModel or EpiModelHIV?

**Comment by dth2** [comment]
I was running EpiModelHIV. I switched to the install stack Chad was using and it works now, so it must have been a compatibility issue.

**Comment by DamienGeorges** [comment]
Hi Deven,

I have the exact same issue since I have updated EpiModel to its latest version.
Whould you mind to be a bit more explicit about the fix you use?
Thanks,

Damien

**Comment by DamienGeorges** [comment]
Fixed. I had to change the class of my (custom) control object to c("control.net", "control.list", "list") as in the latest version of EpiModel.

Best
