### ISSUE TITLE
set_transmat function

### ISSUE THREAD

**Issue by thednainus** [statnet/EpiModel#563]
Hello,

If I understood the code correctly, I noticed that maybe it would be better to change this line code here:
https://github.com/statnet/EpiModel/blob/e402f7a427c9170108f714c10709efe5d2fe2686/R/net.mod.infection.R#L376

to something like:

```
if(!is.null(dat$stats$transmat) == TRUE){
    del <- rbind(dat$stats$transmat, del)
}
```

that is because the first transmission may not happen at time = 2, for example. So https://github.com/statnet/EpiModel/blob/e402f7a427c9170108f714c10709efe5d2fe2686/R/net.mod.infection.R#L376
will always evaluate to true. 

And it will do the same "command" twice:
https://github.com/statnet/EpiModel/blob/e402f7a427c9170108f714c10709efe5d2fe2686/R/net.mod.infection.R#L377
and
https://github.com/statnet/EpiModel/blob/e402f7a427c9170108f714c10709efe5d2fe2686/R/net.mod.infection.R#L380

Cheers,
Fabricia.

**Comment by smjenness** [comment]
@AdrienLeGuillou : can you take a look at this?

**Comment by AdrienLeGuillou** [comment]
@smjenness : I agree with @thednainus 

checking the existence of `dat$stats$transmat` is a more general solution as it does not assume anything of when this code should run. Also, it makes the code easier to understand if the reader is not already familiar with EpiModel.

I will make a PR changing this

**Comment by AdrienLeGuillou** [comment]
@smjenness, actually there is an even simpler solution, we can remove the condition altogether. As `param$stats$transmat` evaluate to `NULL` if it was not created (as a consequence of how R list works), `del <- rbind(param$stats$transmat, del)` is equivalent to `del <- rbind(del)` (because `rbind` first argument is `...` so `NULL` is discarded)

the whole function could look like this:

``` r
set_transmat <- function(dat, del, at) {
  del <- del[!duplicated(del$sus), ]
  # Convert the Discordant Edglist indexes to the corresponding unique_ids
  del[["sus"]] <- get_unique_ids(dat, del[["sus"]])
  del[["inf"]] <- get_unique_ids(dat, del[["inf"]])

  # when `dat$stats$transmat` is `NULL` the right hand side evaluate to `del`
  dat$stats$transmat <- rbind(dat$stats$transmat, del)

  return(dat)
}

```

instead of 

``` r
set_transmat <- function(dat, del, at) {
  del <- del[!duplicated(del$sus), ]
  # Convert the Discordant Edglist indexes to the corresponding unique_ids
  del[["sus"]] <- get_unique_ids(dat, del[["sus"]])
  del[["inf"]] <- get_unique_ids(dat, del[["inf"]])

  if (at != 2) {
    del <- rbind(dat$stats$transmat, del)
  }

  dat$stats$transmat <- del

  return(dat)
}
```

this avoid an unnecessary check but if you think the code loses clarity I can add it anyway. The overhead is negligible.

**Comment by smjenness** [comment]
@thednainus : this is now fixed on the Github master
