### ISSUE TITLE
Plot function in SEIRS with leaky vax

### ISSUE THREAD

**Issue by DhruvaJ7** [statnet/EpiModel#577]
Hello, 
I'm currently trying to use the leaky vaccination extension model to simulate a 3 age group network. I'm doing this by adding an age group attribute. The simulation works and the resultant data frame contains data on everything except for susceptibility rates within the 3 groups and the number of nodes within each group. However, it does have the total number of nodes, and the total number that are susceptible.
When I use the plot function with type = "network", the resulting cross sectional data does not accurately reflect the timestep that I specify. It instead produces a network plot using the initial parameters that I specify. I have resimulate.networks = "TRUE" so I'm not sure why this is happening. Does the plot function not work with extension models? Is this happening because it can't keep track of the number of nodes in each group?

I'm quite new to this so any help is appreciated!

**Comment by AdrienLeGuillou** [comment]
Hi @DhruvaJ7 , could you provide a minimal example of what you are doing? Ideally a github repo with the files as they are in your project. This way I would be able to run it here to better understand what is going on.

**Comment by DhruvaJ7** [comment]
Hi @AdrienLeGuillou, here is the link to the repo - https://github.com/DhruvaJ7/VaxNetwork. It has my main file - VaxNW and the source file for leaky vaccination from the EpiModel GitHub gallery which I use for the SEIRS extension. 
The last line of VaxNW has the plot function, and with col.status = TRUE, it is clear that the resultant graph does not have the correct number of infected nodes. In my simulations, the data frame showed that there were no infected nodes by the end, however the cross-sectional plot shows that the number of infected nodes is the same as the initial number (50).

**Comment by AdrienLeGuillou** [comment]
Hi @DhruvaJ7 , sorry for the delay in answering you. 

I am looking at your code and see the problem with the network plot. I honnestly don't understand whats going on :-/

However, I have the number of node per age group when running your code:  `num.age.grp1`, `num.age.grp2`, `num.age.grp3` 

Also, I see you are defining   `inf.prob.age.grp2 = 0.4` and `inf.prob.age.grp3 = 0.3` in the parameters. However, they are never used in the actual model (unless I am missing something). I suppose you were trying to replicate the `group` syntax of the examples. Unfortunately, to have a different infection rate by `age.grp`, you need to manually code that in the "infection module".

I will try to understand whats going on with the network plots, but I have to say I am a bit lost for now.

**Comment by AdrienLeGuillou** [comment]
I found where the issue was, in `control.net` you forgot the "nwupdate.FUN" module in `module.order`

with this version it will work:

``` r
control <- control.net(
  type = NULL,
  nsteps = 200,
  nsims = 3,
  epi.by = "age.grp",
  infection.FUN = infect,
  progress.FUN = progress,
  departures.FUN = dfunc,
  arrivals.FUN = afunc,
  resimulate.network = TRUE,
  verbose = TRUE,
  module.order = c(
    "resim_nets.FUN", "departures.FUN",
    "arrivals.FUN", "infection.FUN",
    "progress.FUN", "nwupdate.FUN",  "prevalence.FUN"
  )
)

```

beware, the simulation is way longer this way, but it actually works. The `nwupdate` module copies the attributes from the `dat` object back to the network. With your code, the attributes in the network was never updated, hence the plots matching the initial number of infected.

**Comment by DhruvaJ7** [comment]
Hi @AdrienLeGuillou, yep I realized that I needed to add the age group attribute to incoming nodes which is how I was able to get the number of nodes in each group. Thank you very much for pointing out the missing nwupdate module, the network plot works now!
