### ISSUE TITLE
Reference for equation

### ISSUE THREAD

**Issue by thednainus** [statnet/EpiModel#582]
Hello,

Do you have the reference for the equation in this module:
https://github.com/statnet/EpiModel/blob/master/R/net.mod.infection.R#L90

I am following some scripts like this one here:
http://statnet.org/nme/d5-s6-COVIDScreen.html#Infection
in which there is a lower risk of transmission parameter: `inf.prob.a.rr` 

What happen if I am interested in the opposite? Some individuals have a much higher risk of transmission? Let's say that the risk ratio is 10. Should I multiply my base inf.probability to 10? I think I am missing something and this may be very basic statistics that I am getting confused.

But if that is the case, and I should multiply my base inf.probability parameter to 10, then the final transmission rate will evaluate to NA (because of the negative number inside the parenthesis).

Thanks,
Fabricia.

**Comment by smjenness** [comment]
Thanks for your patience (I was away on paternity leave).

The equation is a standard "escape probability" based on a series of independent events. Here's a snapshot from my modeling class lecture slides where I explain this:

<img width="1023" alt="Screen Shot 2021-10-11 at 9 44 47 AM" src="https://user-images.githubusercontent.com/2521570/136800665-b3825d97-8c04-4d36-85dd-87eebc0fbc40.png">

Sure, you can have multipliers that either increase or decrease the base probability of infection per contact. Be careful about laws of probability; for example, if you base probability and you multiply it by 10, you have a probability above 1. Instead, it may make sense to convert the base probability into a log odds, apply modifications on that base log odds, then reconvert it to a probability. Here is an example of that: https://github.com/statnet/EpiModelHIV/blob/CombPrev/R/mod.hivtrans.R#L107-L145.

I hope that helps. If so, please feel free to close this issue.
