### ISSUE TITLE
Add network model shiny app

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#68]
Probably needs to start with independent only models for speed reasons.

**Comment by smjenness** [comment]
@ebey When you have a good working model, please make sure to modify the `epiweb` function to accept a `net` argument.

**Comment by ebey** [comment]
@smjenness If you want to take a look before we meet tomorrow, I published the current version at https://statnet.shinyapps.io/epinet

Specific questions: Are there other nw stats the user should be able to choose from to track?
Should the two different model specification methods apply only to formation, and have a single option for how to specify dissolution? (Because currently the two inputs for dissolution are very similar).

**Comment by smjenness** [comment]
Thanks, this looks great!

> Are there other nw stats the user should be able to choose from to track?

No, the ones in the formation formula you have listed are sufficient.

> Should the two different model specification methods apply only to formation, and have a single option for how to specify dissolution? (Because currently the two inputs for dissolution are very similar).

No, we'll just keep the simple dissolution model for now.

Three other requests:
1. Have the mean degree slider range from 0.1 to 1.5
2. Change the page name from Network Diagnostics to Model Estimation
3. Have a check box toggle for network diagnostics for plots.joined = TRUE/FALSE (default to TRUE), passed to plot.netdx

Thank you!

**Comment by ebey** [comment]
@smjenness I have added the updates we talked about on Friday, including a friendlier catch for errors in estimation and a shell of a front page that is ready for more details. One thing to note is that birth and death rates still aren't connected to epidemic simulation.

**Comment by smjenness** [comment]
Great, thank you. Let's remove the birth and death rate parameters for now (you can just comment them out in the code) and we can return to it in the next version.

**Comment by smjenness** [comment]
Note to myself to write the front page for the app before release

**Comment by smjenness** [comment]
Hi @ebey, can you please address the following issues for the shiny network app before we release Epimodel to CRAN next week?

- [ ] Read through details page to check for any errors. I decided to drop your little pictures on the side for now. Want to keep the overall package size as small as possible. 
- [ ] Can you do code highlighting on the names of the functions in the details page? netest, netdx, netsim rendered like this `netsim` in the html?
- [ ] I think the network plots and data page are conceptually better as tabs within the epidemic simulation page. What do you think? If you agree, could you change?

Thanks!

**Comment by smjenness** [comment]
Made my edits here: b1f99a5ebfbbe1135485c698be29bf4ed585ef06
