### ISSUE TITLE
Develop update.attribute helper function that provides simple unified means of conducting main classes of attribute updating.

### ISSUE THREAD

**Issue by sgoodreau** [statnet/EpiModel#89]
I am envisioning something like: update_attributes(all, attrname, type, params, exclude.inactive=T)

Examples of type include:

- fixed: everyone's attribute is updated the same amount every time (a la age).

- transmat: there are a fixed set of n discrete categories (which are passed as the first element in params), and an n x n Markovian transition matrix (which is passed as the second element of params)

- ordered: there are a fixed set of n discrete categories (which are passed as the first element in params), and they occur in a single natural progression. Thus the transition probs only need to be a n-1 vector, not an n x n Matrix.

- multiple other options involving time already spent in the state - here the details depend on whether TEAs are being used or not

etc.

Lots of error checking needed.  

If exclude.inactive=F, then inactive people will also have their attributes updated.  Perhaps this is overkill. Or, more literally in this case, underkill :-)

Perhaps this should actually go into networkDynamic, but I think there will be enough specificity to EpiModel that it's worth having it well integrated.

This may supplant #57, which I think is no longer the way to go.

**Comment by smjenness** [comment]
Handled in extension modules and submodules, for example #128
